// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_add_permission",
    feature = "op_cancel_message_move_task",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_create_queue",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_message_move_tasks",
    feature = "op_list_queue_tags",
    feature = "op_list_queues",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_start_message_move_task",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
pub use crate::types::error::_invalid_address::InvalidAddress;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_cancel_message_move_task",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_create_queue",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_message_move_tasks",
    feature = "op_list_queue_tags",
    feature = "op_list_queues",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_start_message_move_task",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
pub use crate::types::error::_invalid_security::InvalidSecurity;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_receive_message",
    feature = "op_set_queue_attributes"
))]
pub use crate::types::error::_over_limit::OverLimit;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_queue_tags",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
pub use crate::types::error::_queue_does_not_exist::QueueDoesNotExist;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_cancel_message_move_task",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_create_queue",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_message_move_tasks",
    feature = "op_list_queue_tags",
    feature = "op_list_queues",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_start_message_move_task",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
pub use crate::types::error::_request_throttled::RequestThrottled;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_cancel_message_move_task",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_create_queue",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_message_move_tasks",
    feature = "op_list_queue_tags",
    feature = "op_list_queues",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_start_message_move_task",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
pub use crate::types::error::_unsupported_operation::UnsupportedOperation;

#[cfg(any(
    feature = "op_cancel_message_move_task",
    feature = "op_list_message_move_tasks",
    feature = "op_start_message_move_task"
))]
pub use crate::types::error::_resource_not_found_exception::ResourceNotFoundException;

#[cfg(feature = "op_change_message_visibility")]
pub use crate::types::error::_message_not_inflight::MessageNotInflight;

#[cfg(any(feature = "op_change_message_visibility", feature = "op_delete_message"))]
pub use crate::types::error::_receipt_handle_is_invalid::ReceiptHandleIsInvalid;

#[cfg(any(
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message_batch",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_batch_entry_ids_not_distinct::BatchEntryIdsNotDistinct;

#[cfg(any(
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message_batch",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_empty_batch_request::EmptyBatchRequest;

#[cfg(any(
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message_batch",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_invalid_batch_entry_id::InvalidBatchEntryId;

#[cfg(any(
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message_batch",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_too_many_entries_in_batch_request::TooManyEntriesInBatchRequest;

#[cfg(any(
    feature = "op_create_queue",
    feature = "op_get_queue_attributes",
    feature = "op_set_queue_attributes"
))]
pub use crate::types::error::_invalid_attribute_name::InvalidAttributeName;

#[cfg(any(feature = "op_create_queue", feature = "op_set_queue_attributes"))]
pub use crate::types::error::_invalid_attribute_value::InvalidAttributeValue;

#[cfg(feature = "op_create_queue")]
pub use crate::types::error::_queue_deleted_recently::QueueDeletedRecently;

#[cfg(feature = "op_create_queue")]
pub use crate::types::error::_queue_name_exists::QueueNameExists;

#[cfg(feature = "op_delete_message")]
pub use crate::types::error::_invalid_id_format::InvalidIdFormat;

#[cfg(feature = "op_purge_queue")]
pub use crate::types::error::_purge_queue_in_progress::PurgeQueueInProgress;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_kms_access_denied::KmsAccessDenied;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_kms_disabled::KmsDisabled;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_kms_invalid_key_usage::KmsInvalidKeyUsage;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_kms_invalid_state::KmsInvalidState;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_kms_not_found::KmsNotFound;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_kms_opt_in_required::KmsOptInRequired;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
pub use crate::types::error::_kms_throttled::KmsThrottled;

#[cfg(feature = "op_send_message")]
pub use crate::types::error::_invalid_message_contents::InvalidMessageContents;

#[cfg(feature = "op_send_message_batch")]
pub use crate::types::error::_batch_request_too_long::BatchRequestTooLong;

#[cfg(any(
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message_batch",
    feature = "op_send_message_batch"
))]
mod _batch_entry_ids_not_distinct;

#[cfg(feature = "op_send_message_batch")]
mod _batch_request_too_long;

#[cfg(any(
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message_batch",
    feature = "op_send_message_batch"
))]
mod _empty_batch_request;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_cancel_message_move_task",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_create_queue",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_message_move_tasks",
    feature = "op_list_queue_tags",
    feature = "op_list_queues",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_start_message_move_task",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
mod _invalid_address;

#[cfg(any(
    feature = "op_create_queue",
    feature = "op_get_queue_attributes",
    feature = "op_set_queue_attributes"
))]
mod _invalid_attribute_name;

#[cfg(any(feature = "op_create_queue", feature = "op_set_queue_attributes"))]
mod _invalid_attribute_value;

#[cfg(any(
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message_batch",
    feature = "op_send_message_batch"
))]
mod _invalid_batch_entry_id;

#[cfg(feature = "op_delete_message")]
mod _invalid_id_format;

#[cfg(feature = "op_send_message")]
mod _invalid_message_contents;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_cancel_message_move_task",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_create_queue",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_message_move_tasks",
    feature = "op_list_queue_tags",
    feature = "op_list_queues",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_start_message_move_task",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
mod _invalid_security;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
mod _kms_access_denied;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
mod _kms_disabled;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
mod _kms_invalid_key_usage;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
mod _kms_invalid_state;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
mod _kms_not_found;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
mod _kms_opt_in_required;

#[cfg(any(
    feature = "op_receive_message",
    feature = "op_send_message",
    feature = "op_send_message_batch"
))]
mod _kms_throttled;

#[cfg(feature = "op_change_message_visibility")]
mod _message_not_inflight;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_receive_message",
    feature = "op_set_queue_attributes"
))]
mod _over_limit;

#[cfg(feature = "op_purge_queue")]
mod _purge_queue_in_progress;

#[cfg(feature = "op_create_queue")]
mod _queue_deleted_recently;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_queue_tags",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
mod _queue_does_not_exist;

#[cfg(feature = "op_create_queue")]
mod _queue_name_exists;

#[cfg(any(feature = "op_change_message_visibility", feature = "op_delete_message"))]
mod _receipt_handle_is_invalid;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_cancel_message_move_task",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_create_queue",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_message_move_tasks",
    feature = "op_list_queue_tags",
    feature = "op_list_queues",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_start_message_move_task",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
mod _request_throttled;

#[cfg(any(
    feature = "op_cancel_message_move_task",
    feature = "op_list_message_move_tasks",
    feature = "op_start_message_move_task"
))]
mod _resource_not_found_exception;

#[cfg(any(
    feature = "op_change_message_visibility_batch",
    feature = "op_delete_message_batch",
    feature = "op_send_message_batch"
))]
mod _too_many_entries_in_batch_request;

#[cfg(any(
    feature = "op_add_permission",
    feature = "op_cancel_message_move_task",
    feature = "op_change_message_visibility",
    feature = "op_change_message_visibility_batch",
    feature = "op_create_queue",
    feature = "op_delete_message",
    feature = "op_delete_message_batch",
    feature = "op_delete_queue",
    feature = "op_get_queue_attributes",
    feature = "op_get_queue_url",
    feature = "op_list_dead_letter_source_queues",
    feature = "op_list_message_move_tasks",
    feature = "op_list_queue_tags",
    feature = "op_list_queues",
    feature = "op_purge_queue",
    feature = "op_receive_message",
    feature = "op_remove_permission",
    feature = "op_send_message",
    feature = "op_send_message_batch",
    feature = "op_set_queue_attributes",
    feature = "op_start_message_move_task",
    feature = "op_tag_queue",
    feature = "op_untag_queue"
))]
mod _unsupported_operation;

/// Builders
pub mod builders;
