// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DeleteQuotaShare`](crate::operation::delete_quota_share::builders::DeleteQuotaShareFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`quota_share_arn(impl Into<String>)`](crate::operation::delete_quota_share::builders::DeleteQuotaShareFluentBuilder::quota_share_arn) / [`set_quota_share_arn(Option<String>)`](crate::operation::delete_quota_share::builders::DeleteQuotaShareFluentBuilder::set_quota_share_arn):<br>required: **true**<br><p>The Amazon Resource Name (ARN) of the quota share.</p><br>
    /// - On success, responds with [`DeleteQuotaShareOutput`](crate::operation::delete_quota_share::DeleteQuotaShareOutput)
    /// - On failure, responds with [`SdkError<DeleteQuotaShareError>`](crate::operation::delete_quota_share::DeleteQuotaShareError)
    pub fn delete_quota_share(&self) -> crate::operation::delete_quota_share::builders::DeleteQuotaShareFluentBuilder {
        crate::operation::delete_quota_share::builders::DeleteQuotaShareFluentBuilder::new(self.handle.clone())
    }
}
