// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_create_alias",
    feature = "op_create_grant",
    feature = "op_create_key",
    feature = "op_decrypt",
    feature = "op_delete_alias",
    feature = "op_delete_imported_key_material",
    feature = "op_derive_shared_secret",
    feature = "op_describe_key",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_random",
    feature = "op_get_key_last_usage",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_keys",
    feature = "op_list_retirable_grants",
    feature = "op_put_key_policy",
    feature = "op_re_encrypt",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_sign",
    feature = "op_update_alias",
    feature = "op_update_key_description",
    feature = "op_verify"
))]
pub use crate::types::error::_dependency_timeout_exception::DependencyTimeoutException;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_create_grant",
    feature = "op_create_key",
    feature = "op_delete_imported_key_material",
    feature = "op_describe_key",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_get_key_last_usage",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_key_rotations",
    feature = "op_list_resource_tags",
    feature = "op_list_retirable_grants",
    feature = "op_put_key_policy",
    feature = "op_replicate_key",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_key_description",
    feature = "op_update_primary_region"
))]
pub use crate::types::error::_invalid_arn_exception::InvalidArnException;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_connect_custom_key_store",
    feature = "op_create_alias",
    feature = "op_create_custom_key_store",
    feature = "op_create_grant",
    feature = "op_create_key",
    feature = "op_decrypt",
    feature = "op_delete_alias",
    feature = "op_delete_custom_key_store",
    feature = "op_delete_imported_key_material",
    feature = "op_derive_shared_secret",
    feature = "op_describe_custom_key_stores",
    feature = "op_describe_key",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_disconnect_custom_key_store",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_generate_random",
    feature = "op_get_key_last_usage",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_key_rotations",
    feature = "op_list_keys",
    feature = "op_list_resource_tags",
    feature = "op_list_retirable_grants",
    feature = "op_put_key_policy",
    feature = "op_re_encrypt",
    feature = "op_replicate_key",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_sign",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_alias",
    feature = "op_update_custom_key_store",
    feature = "op_update_key_description",
    feature = "op_update_primary_region",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
pub use crate::types::error::_kms_internal_exception::KmsInternalException;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_create_alias",
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_delete_alias",
    feature = "op_delete_imported_key_material",
    feature = "op_derive_shared_secret",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_key_rotations",
    feature = "op_put_key_policy",
    feature = "op_re_encrypt",
    feature = "op_replicate_key",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_sign",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_alias",
    feature = "op_update_key_description",
    feature = "op_update_primary_region",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
pub use crate::types::error::_kms_invalid_state_exception::KmsInvalidStateException;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_create_alias",
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_delete_alias",
    feature = "op_delete_imported_key_material",
    feature = "op_derive_shared_secret",
    feature = "op_describe_key",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_key_last_usage",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_key_rotations",
    feature = "op_list_resource_tags",
    feature = "op_list_retirable_grants",
    feature = "op_put_key_policy",
    feature = "op_re_encrypt",
    feature = "op_replicate_key",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_sign",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_alias",
    feature = "op_update_key_description",
    feature = "op_update_primary_region",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
pub use crate::types::error::_not_found_exception::NotFoundException;

#[cfg(any(
    feature = "op_connect_custom_key_store",
    feature = "op_create_custom_key_store",
    feature = "op_create_key",
    feature = "op_update_custom_key_store"
))]
pub use crate::types::error::_cloud_hsm_cluster_invalid_configuration_exception::CloudHsmClusterInvalidConfigurationException;

#[cfg(any(
    feature = "op_connect_custom_key_store",
    feature = "op_create_custom_key_store",
    feature = "op_update_custom_key_store"
))]
pub use crate::types::error::_cloud_hsm_cluster_not_active_exception::CloudHsmClusterNotActiveException;

#[cfg(any(
    feature = "op_connect_custom_key_store",
    feature = "op_create_key",
    feature = "op_delete_custom_key_store",
    feature = "op_disconnect_custom_key_store",
    feature = "op_generate_random",
    feature = "op_update_custom_key_store"
))]
pub use crate::types::error::_custom_key_store_invalid_state_exception::CustomKeyStoreInvalidStateException;

#[cfg(any(
    feature = "op_connect_custom_key_store",
    feature = "op_create_key",
    feature = "op_delete_custom_key_store",
    feature = "op_describe_custom_key_stores",
    feature = "op_disconnect_custom_key_store",
    feature = "op_generate_random",
    feature = "op_update_custom_key_store"
))]
pub use crate::types::error::_custom_key_store_not_found_exception::CustomKeyStoreNotFoundException;

#[cfg(any(feature = "op_create_alias", feature = "op_replicate_key"))]
pub use crate::types::error::_already_exists_exception::AlreadyExistsException;

#[cfg(feature = "op_create_alias")]
pub use crate::types::error::_invalid_alias_name_exception::InvalidAliasNameException;

#[cfg(any(
    feature = "op_create_alias",
    feature = "op_create_custom_key_store",
    feature = "op_create_grant",
    feature = "op_create_key",
    feature = "op_enable_key",
    feature = "op_put_key_policy",
    feature = "op_replicate_key",
    feature = "op_rotate_key_on_demand",
    feature = "op_tag_resource",
    feature = "op_update_alias"
))]
pub use crate::types::error::_limit_exceeded_exception::LimitExceededException;

#[cfg(feature = "op_create_custom_key_store")]
pub use crate::types::error::_cloud_hsm_cluster_in_use_exception::CloudHsmClusterInUseException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_cloud_hsm_cluster_not_found_exception::CloudHsmClusterNotFoundException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_custom_key_store_name_in_use_exception::CustomKeyStoreNameInUseException;

#[cfg(feature = "op_create_custom_key_store")]
pub use crate::types::error::_incorrect_trust_anchor_exception::IncorrectTrustAnchorException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_incorrect_authentication_credential_exception::XksProxyIncorrectAuthenticationCredentialException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_invalid_configuration_exception::XksProxyInvalidConfigurationException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_invalid_response_exception::XksProxyInvalidResponseException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_uri_endpoint_in_use_exception::XksProxyUriEndpointInUseException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_uri_in_use_exception::XksProxyUriInUseException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_uri_unreachable_exception::XksProxyUriUnreachableException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_vpc_endpoint_service_in_use_exception::XksProxyVpcEndpointServiceInUseException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_vpc_endpoint_service_invalid_configuration_exception::XksProxyVpcEndpointServiceInvalidConfigurationException;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
pub use crate::types::error::_xks_proxy_vpc_endpoint_service_not_found_exception::XksProxyVpcEndpointServiceNotFoundException;

#[cfg(any(
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_public_key",
    feature = "op_re_encrypt",
    feature = "op_replicate_key",
    feature = "op_rotate_key_on_demand",
    feature = "op_sign",
    feature = "op_update_primary_region",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
pub use crate::types::error::_disabled_exception::DisabledException;

#[cfg(any(
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_re_encrypt",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_sign",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
pub use crate::types::error::_dry_run_operation_exception::DryRunOperationException;

#[cfg(any(
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_public_key",
    feature = "op_re_encrypt",
    feature = "op_retire_grant",
    feature = "op_sign",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
pub use crate::types::error::_invalid_grant_token_exception::InvalidGrantTokenException;

#[cfg(any(
    feature = "op_create_key",
    feature = "op_put_key_policy",
    feature = "op_replicate_key"
))]
pub use crate::types::error::_malformed_policy_document_exception::MalformedPolicyDocumentException;

#[cfg(any(
    feature = "op_create_key",
    feature = "op_replicate_key",
    feature = "op_tag_resource",
    feature = "op_untag_resource"
))]
pub use crate::types::error::_tag_exception::TagException;

#[cfg(any(
    feature = "op_create_key",
    feature = "op_delete_imported_key_material",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key_rotation",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_random",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_key_rotations",
    feature = "op_put_key_policy",
    feature = "op_replicate_key",
    feature = "op_rotate_key_on_demand",
    feature = "op_update_primary_region"
))]
pub use crate::types::error::_unsupported_operation_exception::UnsupportedOperationException;

#[cfg(feature = "op_create_key")]
pub use crate::types::error::_xks_key_already_in_use_exception::XksKeyAlreadyInUseException;

#[cfg(feature = "op_create_key")]
pub use crate::types::error::_xks_key_invalid_configuration_exception::XksKeyInvalidConfigurationException;

#[cfg(feature = "op_create_key")]
pub use crate::types::error::_xks_key_not_found_exception::XksKeyNotFoundException;

#[cfg(any(feature = "op_decrypt", feature = "op_re_encrypt"))]
pub use crate::types::error::_incorrect_key_exception::IncorrectKeyException;

#[cfg(any(
    feature = "op_decrypt",
    feature = "op_import_key_material",
    feature = "op_re_encrypt"
))]
pub use crate::types::error::_invalid_ciphertext_exception::InvalidCiphertextException;

#[cfg(any(
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_public_key",
    feature = "op_re_encrypt",
    feature = "op_sign",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
pub use crate::types::error::_invalid_key_usage_exception::InvalidKeyUsageException;

#[cfg(any(
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_public_key",
    feature = "op_re_encrypt",
    feature = "op_sign",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
pub use crate::types::error::_key_unavailable_exception::KeyUnavailableException;

#[cfg(feature = "op_delete_custom_key_store")]
pub use crate::types::error::_custom_key_store_has_cmks_exception::CustomKeyStoreHasCmKsException;

#[cfg(any(
    feature = "op_describe_custom_key_stores",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_rotations",
    feature = "op_list_keys",
    feature = "op_list_resource_tags",
    feature = "op_list_retirable_grants"
))]
pub use crate::types::error::_invalid_marker_exception::InvalidMarkerException;

#[cfg(feature = "op_import_key_material")]
pub use crate::types::error::_expired_import_token_exception::ExpiredImportTokenException;

#[cfg(feature = "op_import_key_material")]
pub use crate::types::error::_incorrect_key_material_exception::IncorrectKeyMaterialException;

#[cfg(feature = "op_import_key_material")]
pub use crate::types::error::_invalid_import_token_exception::InvalidImportTokenException;

#[cfg(any(feature = "op_list_grants", feature = "op_retire_grant", feature = "op_revoke_grant"))]
pub use crate::types::error::_invalid_grant_id_exception::InvalidGrantIdException;

#[cfg(feature = "op_rotate_key_on_demand")]
pub use crate::types::error::_conflict_exception::ConflictException;

#[cfg(feature = "op_update_custom_key_store")]
pub use crate::types::error::_cloud_hsm_cluster_not_related_exception::CloudHsmClusterNotRelatedException;

#[cfg(feature = "op_verify")]
pub use crate::types::error::_kms_invalid_signature_exception::KmsInvalidSignatureException;

#[cfg(feature = "op_verify_mac")]
pub use crate::types::error::_kms_invalid_mac_exception::KmsInvalidMacException;

#[cfg(any(feature = "op_create_alias", feature = "op_replicate_key"))]
mod _already_exists_exception;

#[cfg(feature = "op_create_custom_key_store")]
mod _cloud_hsm_cluster_in_use_exception;

#[cfg(any(
    feature = "op_connect_custom_key_store",
    feature = "op_create_custom_key_store",
    feature = "op_create_key",
    feature = "op_update_custom_key_store"
))]
mod _cloud_hsm_cluster_invalid_configuration_exception;

#[cfg(any(
    feature = "op_connect_custom_key_store",
    feature = "op_create_custom_key_store",
    feature = "op_update_custom_key_store"
))]
mod _cloud_hsm_cluster_not_active_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _cloud_hsm_cluster_not_found_exception;

#[cfg(feature = "op_update_custom_key_store")]
mod _cloud_hsm_cluster_not_related_exception;

#[cfg(feature = "op_rotate_key_on_demand")]
mod _conflict_exception;

#[cfg(feature = "op_delete_custom_key_store")]
mod _custom_key_store_has_cmks_exception;

#[cfg(any(
    feature = "op_connect_custom_key_store",
    feature = "op_create_key",
    feature = "op_delete_custom_key_store",
    feature = "op_disconnect_custom_key_store",
    feature = "op_generate_random",
    feature = "op_update_custom_key_store"
))]
mod _custom_key_store_invalid_state_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _custom_key_store_name_in_use_exception;

#[cfg(any(
    feature = "op_connect_custom_key_store",
    feature = "op_create_key",
    feature = "op_delete_custom_key_store",
    feature = "op_describe_custom_key_stores",
    feature = "op_disconnect_custom_key_store",
    feature = "op_generate_random",
    feature = "op_update_custom_key_store"
))]
mod _custom_key_store_not_found_exception;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_create_alias",
    feature = "op_create_grant",
    feature = "op_create_key",
    feature = "op_decrypt",
    feature = "op_delete_alias",
    feature = "op_delete_imported_key_material",
    feature = "op_derive_shared_secret",
    feature = "op_describe_key",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_random",
    feature = "op_get_key_last_usage",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_keys",
    feature = "op_list_retirable_grants",
    feature = "op_put_key_policy",
    feature = "op_re_encrypt",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_sign",
    feature = "op_update_alias",
    feature = "op_update_key_description",
    feature = "op_verify"
))]
mod _dependency_timeout_exception;

#[cfg(any(
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_public_key",
    feature = "op_re_encrypt",
    feature = "op_replicate_key",
    feature = "op_rotate_key_on_demand",
    feature = "op_sign",
    feature = "op_update_primary_region",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
mod _disabled_exception;

#[cfg(any(
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_re_encrypt",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_sign",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
mod _dry_run_operation_exception;

#[cfg(feature = "op_import_key_material")]
mod _expired_import_token_exception;

#[cfg(any(feature = "op_decrypt", feature = "op_re_encrypt"))]
mod _incorrect_key_exception;

#[cfg(feature = "op_import_key_material")]
mod _incorrect_key_material_exception;

#[cfg(feature = "op_create_custom_key_store")]
mod _incorrect_trust_anchor_exception;

#[cfg(feature = "op_create_alias")]
mod _invalid_alias_name_exception;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_create_grant",
    feature = "op_create_key",
    feature = "op_delete_imported_key_material",
    feature = "op_describe_key",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_get_key_last_usage",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_key_rotations",
    feature = "op_list_resource_tags",
    feature = "op_list_retirable_grants",
    feature = "op_put_key_policy",
    feature = "op_replicate_key",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_key_description",
    feature = "op_update_primary_region"
))]
mod _invalid_arn_exception;

#[cfg(any(
    feature = "op_decrypt",
    feature = "op_import_key_material",
    feature = "op_re_encrypt"
))]
mod _invalid_ciphertext_exception;

#[cfg(any(feature = "op_list_grants", feature = "op_retire_grant", feature = "op_revoke_grant"))]
mod _invalid_grant_id_exception;

#[cfg(any(
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_public_key",
    feature = "op_re_encrypt",
    feature = "op_retire_grant",
    feature = "op_sign",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
mod _invalid_grant_token_exception;

#[cfg(feature = "op_import_key_material")]
mod _invalid_import_token_exception;

#[cfg(any(
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_public_key",
    feature = "op_re_encrypt",
    feature = "op_sign",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
mod _invalid_key_usage_exception;

#[cfg(any(
    feature = "op_describe_custom_key_stores",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_rotations",
    feature = "op_list_keys",
    feature = "op_list_resource_tags",
    feature = "op_list_retirable_grants"
))]
mod _invalid_marker_exception;

#[cfg(any(
    feature = "op_decrypt",
    feature = "op_derive_shared_secret",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_public_key",
    feature = "op_re_encrypt",
    feature = "op_sign",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
mod _key_unavailable_exception;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_connect_custom_key_store",
    feature = "op_create_alias",
    feature = "op_create_custom_key_store",
    feature = "op_create_grant",
    feature = "op_create_key",
    feature = "op_decrypt",
    feature = "op_delete_alias",
    feature = "op_delete_custom_key_store",
    feature = "op_delete_imported_key_material",
    feature = "op_derive_shared_secret",
    feature = "op_describe_custom_key_stores",
    feature = "op_describe_key",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_disconnect_custom_key_store",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_generate_random",
    feature = "op_get_key_last_usage",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_key_rotations",
    feature = "op_list_keys",
    feature = "op_list_resource_tags",
    feature = "op_list_retirable_grants",
    feature = "op_put_key_policy",
    feature = "op_re_encrypt",
    feature = "op_replicate_key",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_sign",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_alias",
    feature = "op_update_custom_key_store",
    feature = "op_update_key_description",
    feature = "op_update_primary_region",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
mod _kms_internal_exception;

#[cfg(feature = "op_verify_mac")]
mod _kms_invalid_mac_exception;

#[cfg(feature = "op_verify")]
mod _kms_invalid_signature_exception;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_create_alias",
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_delete_alias",
    feature = "op_delete_imported_key_material",
    feature = "op_derive_shared_secret",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_key_rotations",
    feature = "op_put_key_policy",
    feature = "op_re_encrypt",
    feature = "op_replicate_key",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_sign",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_alias",
    feature = "op_update_key_description",
    feature = "op_update_primary_region",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
mod _kms_invalid_state_exception;

#[cfg(any(
    feature = "op_create_alias",
    feature = "op_create_custom_key_store",
    feature = "op_create_grant",
    feature = "op_create_key",
    feature = "op_enable_key",
    feature = "op_put_key_policy",
    feature = "op_replicate_key",
    feature = "op_rotate_key_on_demand",
    feature = "op_tag_resource",
    feature = "op_update_alias"
))]
mod _limit_exceeded_exception;

#[cfg(any(
    feature = "op_create_key",
    feature = "op_put_key_policy",
    feature = "op_replicate_key"
))]
mod _malformed_policy_document_exception;

#[cfg(any(
    feature = "op_cancel_key_deletion",
    feature = "op_create_alias",
    feature = "op_create_grant",
    feature = "op_decrypt",
    feature = "op_delete_alias",
    feature = "op_delete_imported_key_material",
    feature = "op_derive_shared_secret",
    feature = "op_describe_key",
    feature = "op_disable_key",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key",
    feature = "op_enable_key_rotation",
    feature = "op_encrypt",
    feature = "op_generate_data_key",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_data_key_without_plaintext",
    feature = "op_generate_mac",
    feature = "op_get_key_last_usage",
    feature = "op_get_key_policy",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_aliases",
    feature = "op_list_grants",
    feature = "op_list_key_policies",
    feature = "op_list_key_rotations",
    feature = "op_list_resource_tags",
    feature = "op_list_retirable_grants",
    feature = "op_put_key_policy",
    feature = "op_re_encrypt",
    feature = "op_replicate_key",
    feature = "op_retire_grant",
    feature = "op_revoke_grant",
    feature = "op_rotate_key_on_demand",
    feature = "op_schedule_key_deletion",
    feature = "op_sign",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_alias",
    feature = "op_update_key_description",
    feature = "op_update_primary_region",
    feature = "op_verify",
    feature = "op_verify_mac"
))]
mod _not_found_exception;

#[cfg(any(
    feature = "op_create_key",
    feature = "op_replicate_key",
    feature = "op_tag_resource",
    feature = "op_untag_resource"
))]
mod _tag_exception;

#[cfg(any(
    feature = "op_create_key",
    feature = "op_delete_imported_key_material",
    feature = "op_disable_key_rotation",
    feature = "op_enable_key_rotation",
    feature = "op_generate_data_key_pair",
    feature = "op_generate_data_key_pair_without_plaintext",
    feature = "op_generate_random",
    feature = "op_get_key_rotation_status",
    feature = "op_get_parameters_for_import",
    feature = "op_get_public_key",
    feature = "op_import_key_material",
    feature = "op_list_key_rotations",
    feature = "op_put_key_policy",
    feature = "op_replicate_key",
    feature = "op_rotate_key_on_demand",
    feature = "op_update_primary_region"
))]
mod _unsupported_operation_exception;

#[cfg(feature = "op_create_key")]
mod _xks_key_already_in_use_exception;

#[cfg(feature = "op_create_key")]
mod _xks_key_invalid_configuration_exception;

#[cfg(feature = "op_create_key")]
mod _xks_key_not_found_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_incorrect_authentication_credential_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_invalid_configuration_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_invalid_response_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_uri_endpoint_in_use_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_uri_in_use_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_uri_unreachable_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_vpc_endpoint_service_in_use_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_vpc_endpoint_service_invalid_configuration_exception;

#[cfg(any(feature = "op_create_custom_key_store", feature = "op_update_custom_key_store"))]
mod _xks_proxy_vpc_endpoint_service_not_found_exception;

/// Builders
pub mod builders;
