// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_get_account_authorization_details",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_update_role_description"
))]
pub use crate::types::_role::Role;

#[cfg(feature = "op_create_access_key")]
pub use crate::types::_access_key::AccessKey;

#[cfg(any(
    feature = "op_create_delegation_request",
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
pub use crate::types::_delegation_permission::DelegationPermission;

#[cfg(any(
    feature = "op_create_group",
    feature = "op_get_group",
    feature = "op_list_groups",
    feature = "op_list_groups_for_user"
))]
pub use crate::types::_group::Group;

#[cfg(any(
    feature = "op_create_instance_profile",
    feature = "op_get_account_authorization_details",
    feature = "op_get_instance_profile",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role"
))]
pub use crate::types::_instance_profile::InstanceProfile;

#[cfg(any(feature = "op_create_login_profile", feature = "op_get_login_profile"))]
pub use crate::types::_login_profile::LoginProfile;

#[cfg(any(
    feature = "op_create_policy",
    feature = "op_get_policy",
    feature = "op_list_policies"
))]
pub use crate::types::_policy::Policy;

#[cfg(any(
    feature = "op_create_policy_version",
    feature = "op_get_account_authorization_details",
    feature = "op_get_policy_version",
    feature = "op_list_policy_versions"
))]
pub use crate::types::_policy_version::PolicyVersion;

#[cfg(any(
    feature = "op_create_saml_provider",
    feature = "op_get_saml_provider",
    feature = "op_update_saml_provider"
))]
pub use crate::types::_assertion_encryption_mode_type::AssertionEncryptionModeType;

#[cfg(any(
    feature = "op_create_service_specific_credential",
    feature = "op_reset_service_specific_credential"
))]
pub use crate::types::_service_specific_credential::ServiceSpecificCredential;

#[cfg(any(
    feature = "op_create_user",
    feature = "op_create_virtual_mfa_device",
    feature = "op_get_group",
    feature = "op_get_user",
    feature = "op_list_users",
    feature = "op_list_virtual_mfa_devices"
))]
pub use crate::types::_user::User;

#[cfg(any(
    feature = "op_create_virtual_mfa_device",
    feature = "op_list_virtual_mfa_devices"
))]
pub use crate::types::_virtual_mfa_device::VirtualMfaDevice;

#[cfg(feature = "op_generate_credential_report")]
pub use crate::types::_report_state_type::ReportStateType;

#[cfg(any(
    feature = "op_generate_service_last_accessed_details",
    feature = "op_get_service_last_accessed_details"
))]
pub use crate::types::_access_advisor_usage_granularity_type::AccessAdvisorUsageGranularityType;

#[cfg(feature = "op_get_access_key_last_used")]
pub use crate::types::_access_key_last_used::AccessKeyLastUsed;

#[cfg(feature = "op_get_account_password_policy")]
pub use crate::types::_password_policy::PasswordPolicy;

#[cfg(feature = "op_get_credential_report")]
pub use crate::types::_report_format_type::ReportFormatType;

#[cfg(any(
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
pub use crate::types::_delegation_request::DelegationRequest;

#[cfg(feature = "op_get_delegation_request")]
pub use crate::types::_permission_check_status_type::PermissionCheckStatusType;

#[cfg(feature = "op_get_delegation_request")]
pub use crate::types::_permission_check_result_type::PermissionCheckResultType;

#[cfg(feature = "op_get_human_readable_summary")]
pub use crate::types::_summary_state_type::SummaryStateType;

#[cfg(feature = "op_get_organizations_access_report")]
pub use crate::types::_sort_key_type::SortKeyType;

#[cfg(any(
    feature = "op_get_organizations_access_report",
    feature = "op_get_service_last_accessed_details",
    feature = "op_get_service_last_accessed_details_with_entities"
))]
pub use crate::types::_job_status_type::JobStatusType;

#[cfg(any(
    feature = "op_get_organizations_access_report",
    feature = "op_get_service_last_accessed_details",
    feature = "op_get_service_last_accessed_details_with_entities"
))]
pub use crate::types::_error_details::ErrorDetails;

#[cfg(feature = "op_get_role_template_version")]
pub use crate::types::_role_template_version::RoleTemplateVersion;

#[cfg(feature = "op_get_server_certificate")]
pub use crate::types::_server_certificate::ServerCertificate;

#[cfg(feature = "op_get_service_linked_role_deletion_status")]
pub use crate::types::_deletion_task_status_type::DeletionTaskStatusType;

#[cfg(feature = "op_get_service_linked_role_deletion_status")]
pub use crate::types::_deletion_task_failure_reason_type::DeletionTaskFailureReasonType;

#[cfg(feature = "op_get_ssh_public_key")]
pub use crate::types::_encoding_type::EncodingType;

#[cfg(any(
    feature = "op_get_ssh_public_key",
    feature = "op_upload_ssh_public_key"
))]
pub use crate::types::_ssh_public_key::SshPublicKey;

#[cfg(any(
    feature = "op_get_account_authorization_details",
    feature = "op_list_entities_for_policy"
))]
pub use crate::types::_entity_type::EntityType;

#[cfg(any(feature = "op_list_entities_for_policy", feature = "op_list_policies"))]
pub use crate::types::_policy_usage_type::PolicyUsageType;

#[cfg(feature = "op_list_policies")]
pub use crate::types::_policy_scope_type::PolicyScopeType;

#[cfg(feature = "op_list_virtual_mfa_devices")]
pub use crate::types::_assignment_status_type::AssignmentStatusType;

#[cfg(feature = "op_set_security_token_service_preferences")]
pub use crate::types::_global_endpoint_token_version::GlobalEndpointTokenVersion;

#[cfg(any(
    feature = "op_create_access_key",
    feature = "op_create_service_specific_credential",
    feature = "op_get_ssh_public_key",
    feature = "op_list_access_keys",
    feature = "op_list_service_specific_credentials",
    feature = "op_list_signing_certificates",
    feature = "op_list_ssh_public_keys",
    feature = "op_reset_service_specific_credential",
    feature = "op_update_access_key",
    feature = "op_update_service_specific_credential",
    feature = "op_update_signing_certificate",
    feature = "op_update_ssh_public_key",
    feature = "op_upload_signing_certificate",
    feature = "op_upload_ssh_public_key"
))]
pub use crate::types::_status_type::StatusType;

#[cfg(any(
    feature = "op_get_server_certificate",
    feature = "op_list_server_certificates",
    feature = "op_upload_server_certificate"
))]
pub use crate::types::_server_certificate_metadata::ServerCertificateMetadata;

#[cfg(any(
    feature = "op_list_signing_certificates",
    feature = "op_upload_signing_certificate"
))]
pub use crate::types::_signing_certificate::SigningCertificate;

#[cfg(feature = "op_acquire_role")]
pub use crate::types::_replacement_value_entry::ReplacementValueEntry;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_create_user",
    feature = "op_create_virtual_mfa_device",
    feature = "op_get_account_authorization_details",
    feature = "op_get_group",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_get_user",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_list_users",
    feature = "op_list_virtual_mfa_devices",
    feature = "op_update_role_description"
))]
pub use crate::types::_attached_permissions_boundary::AttachedPermissionsBoundary;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_get_account_authorization_details",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_update_role_description"
))]
pub use crate::types::_role_last_used::RoleLastUsed;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_get_account_authorization_details",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_update_role_description"
))]
pub use crate::types::_source_role_template::SourceRoleTemplate;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_open_id_connect_provider",
    feature = "op_create_policy",
    feature = "op_create_role",
    feature = "op_create_saml_provider",
    feature = "op_create_service_linked_role",
    feature = "op_create_user",
    feature = "op_create_virtual_mfa_device",
    feature = "op_get_account_authorization_details",
    feature = "op_get_group",
    feature = "op_get_instance_profile",
    feature = "op_get_open_id_connect_provider",
    feature = "op_get_policy",
    feature = "op_get_role",
    feature = "op_get_saml_provider",
    feature = "op_get_server_certificate",
    feature = "op_get_user",
    feature = "op_list_instance_profile_tags",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_mfa_device_tags",
    feature = "op_list_open_id_connect_provider_tags",
    feature = "op_list_policies",
    feature = "op_list_policy_tags",
    feature = "op_list_role_tags",
    feature = "op_list_roles",
    feature = "op_list_saml_provider_tags",
    feature = "op_list_server_certificate_tags",
    feature = "op_list_user_tags",
    feature = "op_list_users",
    feature = "op_list_virtual_mfa_devices",
    feature = "op_tag_instance_profile",
    feature = "op_tag_mfa_device",
    feature = "op_tag_open_id_connect_provider",
    feature = "op_tag_policy",
    feature = "op_tag_role",
    feature = "op_tag_saml_provider",
    feature = "op_tag_server_certificate",
    feature = "op_tag_user",
    feature = "op_update_role_description",
    feature = "op_upload_server_certificate"
))]
pub use crate::types::_tag::Tag;

#[cfg(any(
    feature = "op_disable_organizations_root_credentials_management",
    feature = "op_disable_organizations_root_sessions",
    feature = "op_enable_organizations_root_credentials_management",
    feature = "op_enable_organizations_root_sessions",
    feature = "op_list_organizations_features"
))]
pub use crate::types::_feature_type::FeatureType;

#[cfg(feature = "op_get_account_authorization_details")]
pub use crate::types::_user_detail::UserDetail;

#[cfg(feature = "op_get_account_authorization_details")]
pub use crate::types::_group_detail::GroupDetail;

#[cfg(feature = "op_get_account_authorization_details")]
pub use crate::types::_role_detail::RoleDetail;

#[cfg(feature = "op_get_account_authorization_details")]
pub use crate::types::_managed_policy_detail::ManagedPolicyDetail;

#[cfg(feature = "op_get_account_summary")]
pub use crate::types::_summary_key_type::SummaryKeyType;

#[cfg(any(
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
pub use crate::types::_state_type::StateType;

#[cfg(feature = "op_get_organizations_access_report")]
pub use crate::types::_access_detail::AccessDetail;

#[cfg(feature = "op_get_role_template_version")]
pub use crate::types::_managed_by_type_type::ManagedByTypeType;

#[cfg(feature = "op_get_saml_provider")]
pub use crate::types::_saml_private_key::SamlPrivateKey;

#[cfg(feature = "op_get_service_last_accessed_details")]
pub use crate::types::_service_last_accessed::ServiceLastAccessed;

#[cfg(feature = "op_get_service_last_accessed_details_with_entities")]
pub use crate::types::_entity_details::EntityDetails;

#[cfg(feature = "op_list_access_keys")]
pub use crate::types::_access_key_metadata::AccessKeyMetadata;

#[cfg(any(
    feature = "op_get_account_authorization_details",
    feature = "op_list_attached_group_policies",
    feature = "op_list_attached_role_policies",
    feature = "op_list_attached_user_policies"
))]
pub use crate::types::_attached_policy::AttachedPolicy;

#[cfg(feature = "op_list_entities_for_policy")]
pub use crate::types::_policy_group::PolicyGroup;

#[cfg(feature = "op_list_entities_for_policy")]
pub use crate::types::_policy_user::PolicyUser;

#[cfg(feature = "op_list_entities_for_policy")]
pub use crate::types::_policy_role::PolicyRole;

#[cfg(feature = "op_list_mfa_devices")]
pub use crate::types::_mfa_device::MfaDevice;

#[cfg(feature = "op_list_open_id_connect_providers")]
pub use crate::types::_open_id_connect_provider_list_entry::OpenIdConnectProviderListEntry;

#[cfg(feature = "op_list_policies_granting_service_access")]
pub use crate::types::_list_policies_granting_service_access_entry::ListPoliciesGrantingServiceAccessEntry;

#[cfg(feature = "op_list_saml_providers")]
pub use crate::types::_saml_provider_list_entry::SamlProviderListEntry;

#[cfg(feature = "op_list_service_specific_credentials")]
pub use crate::types::_service_specific_credential_metadata::ServiceSpecificCredentialMetadata;

#[cfg(feature = "op_list_ssh_public_keys")]
pub use crate::types::_ssh_public_key_metadata::SshPublicKeyMetadata;

#[cfg(feature = "op_simulate_custom_policy")]
pub use crate::types::_ordered_organization_policy_type::OrderedOrganizationPolicyType;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_context_entry::ContextEntry;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_evaluation_result::EvaluationResult;

#[cfg(feature = "op_simulate_principal_policy")]
pub use crate::types::_policy_identifier::PolicyIdentifier;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_create_user",
    feature = "op_create_virtual_mfa_device",
    feature = "op_get_account_authorization_details",
    feature = "op_get_group",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_get_user",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_list_users",
    feature = "op_list_virtual_mfa_devices",
    feature = "op_update_role_description"
))]
pub use crate::types::_permissions_boundary_attachment_type::PermissionsBoundaryAttachmentType;

#[cfg(any(
    feature = "op_create_delegation_request",
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
pub use crate::types::_policy_parameter::PolicyParameter;

#[cfg(feature = "op_get_role_template_version")]
pub use crate::types::_inline_policy::InlinePolicy;

#[cfg(feature = "op_get_role_template_version")]
pub use crate::types::_parameter_definition::ParameterDefinition;

#[cfg(feature = "op_get_role_template_version")]
pub use crate::types::_tag_template::TagTemplate;

#[cfg(feature = "op_get_service_last_accessed_details_with_entities")]
pub use crate::types::_entity_info::EntityInfo;

#[cfg(feature = "op_get_service_linked_role_deletion_status")]
pub use crate::types::_role_usage_type::RoleUsageType;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_context_key_type_enum::ContextKeyTypeEnum;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_policy_evaluation_decision_type::PolicyEvaluationDecisionType;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_organizations_decision_detail::OrganizationsDecisionDetail;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_permissions_boundary_decision_detail::PermissionsBoundaryDecisionDetail;

#[cfg(feature = "op_simulate_principal_policy")]
pub use crate::types::_policy_identifier_policy_type::PolicyIdentifierPolicyType;

#[cfg(feature = "op_simulate_principal_policy")]
pub use crate::types::_inline_policy_identifier_type::InlinePolicyIdentifierType;

#[cfg(any(
    feature = "op_create_delegation_request",
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
pub use crate::types::_policy_parameter_type_enum::PolicyParameterTypeEnum;

#[cfg(feature = "op_get_account_authorization_details")]
pub use crate::types::_policy_detail::PolicyDetail;

#[cfg(feature = "op_get_role_template_version")]
pub use crate::types::_parameter_type_type::ParameterTypeType;

#[cfg(feature = "op_get_service_last_accessed_details")]
pub use crate::types::_tracked_action_last_accessed::TrackedActionLastAccessed;

#[cfg(any(
    feature = "op_get_service_last_accessed_details_with_entities",
    feature = "op_list_policies_granting_service_access"
))]
pub use crate::types::_policy_owner_entity_type::PolicyOwnerEntityType;

#[cfg(feature = "op_list_policies_granting_service_access")]
pub use crate::types::_policy_granting_service_access::PolicyGrantingServiceAccess;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_statement::Statement;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_resource_specific_result::ResourceSpecificResult;

#[cfg(feature = "op_simulate_principal_policy")]
pub use crate::types::_attachment_type::AttachmentType;

#[cfg(feature = "op_list_policies_granting_service_access")]
pub use crate::types::_policy_type::PolicyType;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_policy_source_type::PolicySourceType;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
pub use crate::types::_position::Position;

#[cfg(any(
    feature = "op_generate_service_last_accessed_details",
    feature = "op_get_service_last_accessed_details"
))]
mod _access_advisor_usage_granularity_type;

#[cfg(feature = "op_get_organizations_access_report")]
mod _access_detail;

#[cfg(feature = "op_create_access_key")]
mod _access_key;

#[cfg(feature = "op_get_access_key_last_used")]
mod _access_key_last_used;

#[cfg(feature = "op_list_access_keys")]
mod _access_key_metadata;

#[cfg(any(
    feature = "op_create_saml_provider",
    feature = "op_get_saml_provider",
    feature = "op_update_saml_provider"
))]
mod _assertion_encryption_mode_type;

#[cfg(feature = "op_list_virtual_mfa_devices")]
mod _assignment_status_type;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_create_user",
    feature = "op_create_virtual_mfa_device",
    feature = "op_get_account_authorization_details",
    feature = "op_get_group",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_get_user",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_list_users",
    feature = "op_list_virtual_mfa_devices",
    feature = "op_update_role_description"
))]
mod _attached_permissions_boundary;

#[cfg(any(
    feature = "op_get_account_authorization_details",
    feature = "op_list_attached_group_policies",
    feature = "op_list_attached_role_policies",
    feature = "op_list_attached_user_policies"
))]
mod _attached_policy;

#[cfg(feature = "op_simulate_principal_policy")]
mod _attachment_type;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _context_entry;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _context_key_type_enum;

#[cfg(any(
    feature = "op_create_delegation_request",
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
mod _delegation_permission;

#[cfg(any(
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
mod _delegation_request;

#[cfg(feature = "op_get_service_linked_role_deletion_status")]
mod _deletion_task_failure_reason_type;

#[cfg(feature = "op_get_service_linked_role_deletion_status")]
mod _deletion_task_status_type;

#[cfg(feature = "op_get_ssh_public_key")]
mod _encoding_type;

#[cfg(feature = "op_get_service_last_accessed_details_with_entities")]
mod _entity_details;

#[cfg(feature = "op_get_service_last_accessed_details_with_entities")]
mod _entity_info;

#[cfg(any(
    feature = "op_get_account_authorization_details",
    feature = "op_list_entities_for_policy"
))]
mod _entity_type;

#[cfg(any(
    feature = "op_get_organizations_access_report",
    feature = "op_get_service_last_accessed_details",
    feature = "op_get_service_last_accessed_details_with_entities"
))]
mod _error_details;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _evaluation_result;

#[cfg(any(
    feature = "op_disable_organizations_root_credentials_management",
    feature = "op_disable_organizations_root_sessions",
    feature = "op_enable_organizations_root_credentials_management",
    feature = "op_enable_organizations_root_sessions",
    feature = "op_list_organizations_features"
))]
mod _feature_type;

#[cfg(feature = "op_set_security_token_service_preferences")]
mod _global_endpoint_token_version;

#[cfg(any(
    feature = "op_create_group",
    feature = "op_get_group",
    feature = "op_list_groups",
    feature = "op_list_groups_for_user"
))]
mod _group;

#[cfg(feature = "op_get_account_authorization_details")]
mod _group_detail;

#[cfg(feature = "op_get_role_template_version")]
mod _inline_policy;

#[cfg(feature = "op_simulate_principal_policy")]
mod _inline_policy_identifier_type;

#[cfg(any(
    feature = "op_create_instance_profile",
    feature = "op_get_account_authorization_details",
    feature = "op_get_instance_profile",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role"
))]
mod _instance_profile;

#[cfg(any(
    feature = "op_get_organizations_access_report",
    feature = "op_get_service_last_accessed_details",
    feature = "op_get_service_last_accessed_details_with_entities"
))]
mod _job_status_type;

#[cfg(feature = "op_list_policies_granting_service_access")]
mod _list_policies_granting_service_access_entry;

#[cfg(any(feature = "op_create_login_profile", feature = "op_get_login_profile"))]
mod _login_profile;

#[cfg(feature = "op_get_role_template_version")]
mod _managed_by_type_type;

#[cfg(feature = "op_get_account_authorization_details")]
mod _managed_policy_detail;

#[cfg(feature = "op_list_mfa_devices")]
mod _mfa_device;

#[cfg(feature = "op_list_open_id_connect_providers")]
mod _open_id_connect_provider_list_entry;

#[cfg(feature = "op_simulate_custom_policy")]
mod _ordered_organization_policy_type;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _organizations_decision_detail;

#[cfg(feature = "op_get_role_template_version")]
mod _parameter_definition;

#[cfg(feature = "op_get_role_template_version")]
mod _parameter_type_type;

#[cfg(feature = "op_get_account_password_policy")]
mod _password_policy;

#[cfg(feature = "op_get_delegation_request")]
mod _permission_check_result_type;

#[cfg(feature = "op_get_delegation_request")]
mod _permission_check_status_type;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_create_user",
    feature = "op_create_virtual_mfa_device",
    feature = "op_get_account_authorization_details",
    feature = "op_get_group",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_get_user",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_list_users",
    feature = "op_list_virtual_mfa_devices",
    feature = "op_update_role_description"
))]
mod _permissions_boundary_attachment_type;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _permissions_boundary_decision_detail;

#[cfg(any(
    feature = "op_create_policy",
    feature = "op_get_policy",
    feature = "op_list_policies"
))]
mod _policy;

#[cfg(feature = "op_get_account_authorization_details")]
mod _policy_detail;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _policy_evaluation_decision_type;

#[cfg(feature = "op_list_policies_granting_service_access")]
mod _policy_granting_service_access;

#[cfg(feature = "op_list_entities_for_policy")]
mod _policy_group;

#[cfg(feature = "op_simulate_principal_policy")]
mod _policy_identifier;

#[cfg(feature = "op_simulate_principal_policy")]
mod _policy_identifier_policy_type;

#[cfg(any(
    feature = "op_get_service_last_accessed_details_with_entities",
    feature = "op_list_policies_granting_service_access"
))]
mod _policy_owner_entity_type;

#[cfg(any(
    feature = "op_create_delegation_request",
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
mod _policy_parameter;

#[cfg(any(
    feature = "op_create_delegation_request",
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
mod _policy_parameter_type_enum;

#[cfg(feature = "op_list_entities_for_policy")]
mod _policy_role;

#[cfg(feature = "op_list_policies")]
mod _policy_scope_type;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _policy_source_type;

#[cfg(feature = "op_list_policies_granting_service_access")]
mod _policy_type;

#[cfg(any(feature = "op_list_entities_for_policy", feature = "op_list_policies"))]
mod _policy_usage_type;

#[cfg(feature = "op_list_entities_for_policy")]
mod _policy_user;

#[cfg(any(
    feature = "op_create_policy_version",
    feature = "op_get_account_authorization_details",
    feature = "op_get_policy_version",
    feature = "op_list_policy_versions"
))]
mod _policy_version;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _position;

#[cfg(feature = "op_acquire_role")]
mod _replacement_value_entry;

#[cfg(feature = "op_get_credential_report")]
mod _report_format_type;

#[cfg(feature = "op_generate_credential_report")]
mod _report_state_type;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _resource_specific_result;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_get_account_authorization_details",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_update_role_description"
))]
mod _role;

#[cfg(feature = "op_get_account_authorization_details")]
mod _role_detail;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_get_account_authorization_details",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_update_role_description"
))]
mod _role_last_used;

#[cfg(feature = "op_get_role_template_version")]
mod _role_template_version;

#[cfg(feature = "op_get_service_linked_role_deletion_status")]
mod _role_usage_type;

#[cfg(feature = "op_get_saml_provider")]
mod _saml_private_key;

#[cfg(feature = "op_list_saml_providers")]
mod _saml_provider_list_entry;

#[cfg(feature = "op_get_server_certificate")]
mod _server_certificate;

#[cfg(any(
    feature = "op_get_server_certificate",
    feature = "op_list_server_certificates",
    feature = "op_upload_server_certificate"
))]
mod _server_certificate_metadata;

#[cfg(feature = "op_get_service_last_accessed_details")]
mod _service_last_accessed;

#[cfg(any(
    feature = "op_create_service_specific_credential",
    feature = "op_reset_service_specific_credential"
))]
mod _service_specific_credential;

#[cfg(feature = "op_list_service_specific_credentials")]
mod _service_specific_credential_metadata;

#[cfg(any(
    feature = "op_list_signing_certificates",
    feature = "op_upload_signing_certificate"
))]
mod _signing_certificate;

#[cfg(feature = "op_get_organizations_access_report")]
mod _sort_key_type;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_role",
    feature = "op_create_service_linked_role",
    feature = "op_get_account_authorization_details",
    feature = "op_get_instance_profile",
    feature = "op_get_role",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_roles",
    feature = "op_update_role_description"
))]
mod _source_role_template;

#[cfg(any(
    feature = "op_get_ssh_public_key",
    feature = "op_upload_ssh_public_key"
))]
mod _ssh_public_key;

#[cfg(feature = "op_list_ssh_public_keys")]
mod _ssh_public_key_metadata;

#[cfg(any(
    feature = "op_get_delegation_request",
    feature = "op_list_delegation_requests"
))]
mod _state_type;

#[cfg(any(
    feature = "op_simulate_custom_policy",
    feature = "op_simulate_principal_policy"
))]
mod _statement;

#[cfg(any(
    feature = "op_create_access_key",
    feature = "op_create_service_specific_credential",
    feature = "op_get_ssh_public_key",
    feature = "op_list_access_keys",
    feature = "op_list_service_specific_credentials",
    feature = "op_list_signing_certificates",
    feature = "op_list_ssh_public_keys",
    feature = "op_reset_service_specific_credential",
    feature = "op_update_access_key",
    feature = "op_update_service_specific_credential",
    feature = "op_update_signing_certificate",
    feature = "op_update_ssh_public_key",
    feature = "op_upload_signing_certificate",
    feature = "op_upload_ssh_public_key"
))]
mod _status_type;

#[cfg(feature = "op_get_account_summary")]
mod _summary_key_type;

#[cfg(feature = "op_get_human_readable_summary")]
mod _summary_state_type;

#[cfg(any(
    feature = "op_acquire_role",
    feature = "op_create_instance_profile",
    feature = "op_create_open_id_connect_provider",
    feature = "op_create_policy",
    feature = "op_create_role",
    feature = "op_create_saml_provider",
    feature = "op_create_service_linked_role",
    feature = "op_create_user",
    feature = "op_create_virtual_mfa_device",
    feature = "op_get_account_authorization_details",
    feature = "op_get_group",
    feature = "op_get_instance_profile",
    feature = "op_get_open_id_connect_provider",
    feature = "op_get_policy",
    feature = "op_get_role",
    feature = "op_get_saml_provider",
    feature = "op_get_server_certificate",
    feature = "op_get_user",
    feature = "op_list_instance_profile_tags",
    feature = "op_list_instance_profiles",
    feature = "op_list_instance_profiles_for_role",
    feature = "op_list_mfa_device_tags",
    feature = "op_list_open_id_connect_provider_tags",
    feature = "op_list_policies",
    feature = "op_list_policy_tags",
    feature = "op_list_role_tags",
    feature = "op_list_roles",
    feature = "op_list_saml_provider_tags",
    feature = "op_list_server_certificate_tags",
    feature = "op_list_user_tags",
    feature = "op_list_users",
    feature = "op_list_virtual_mfa_devices",
    feature = "op_tag_instance_profile",
    feature = "op_tag_mfa_device",
    feature = "op_tag_open_id_connect_provider",
    feature = "op_tag_policy",
    feature = "op_tag_role",
    feature = "op_tag_saml_provider",
    feature = "op_tag_server_certificate",
    feature = "op_tag_user",
    feature = "op_update_role_description",
    feature = "op_upload_server_certificate"
))]
mod _tag;

#[cfg(feature = "op_get_role_template_version")]
mod _tag_template;

#[cfg(feature = "op_get_service_last_accessed_details")]
mod _tracked_action_last_accessed;

#[cfg(any(
    feature = "op_create_user",
    feature = "op_create_virtual_mfa_device",
    feature = "op_get_group",
    feature = "op_get_user",
    feature = "op_list_users",
    feature = "op_list_virtual_mfa_devices"
))]
mod _user;

#[cfg(feature = "op_get_account_authorization_details")]
mod _user_detail;

#[cfg(any(
    feature = "op_create_virtual_mfa_device",
    feature = "op_list_virtual_mfa_devices"
))]
mod _virtual_mfa_device;

/// Builders
pub mod builders;

/// Error types that AWS Identity and Access Management can respond with.
pub mod error;
