// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_batch_execute_statement",
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_create_backup",
    feature = "op_create_global_table",
    feature = "op_create_table",
    feature = "op_delete_backup",
    feature = "op_delete_item",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_describe_backup",
    feature = "op_describe_continuous_backups",
    feature = "op_describe_contributor_insights",
    feature = "op_describe_export",
    feature = "op_describe_global_table",
    feature = "op_describe_global_table_settings",
    feature = "op_describe_kinesis_streaming_destination",
    feature = "op_describe_limits",
    feature = "op_describe_table",
    feature = "op_describe_table_replica_auto_scaling",
    feature = "op_describe_time_to_live",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_export_table_to_point_in_time",
    feature = "op_get_item",
    feature = "op_get_resource_policy",
    feature = "op_list_backups",
    feature = "op_list_contributor_insights",
    feature = "op_list_exports",
    feature = "op_list_global_tables",
    feature = "op_list_tables",
    feature = "op_list_tags_of_resource",
    feature = "op_put_item",
    feature = "op_put_resource_policy",
    feature = "op_query",
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time",
    feature = "op_scan",
    feature = "op_search_vectors",
    feature = "op_tag_resource",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_untag_resource",
    feature = "op_update_continuous_backups",
    feature = "op_update_contributor_insights",
    feature = "op_update_global_table",
    feature = "op_update_global_table_settings",
    feature = "op_update_item",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_table_replica_auto_scaling",
    feature = "op_update_time_to_live"
))]
pub use crate::types::error::_internal_server_error::InternalServerError;

#[cfg(any(
    feature = "op_batch_execute_statement",
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_get_item",
    feature = "op_put_item",
    feature = "op_query",
    feature = "op_scan",
    feature = "op_search_vectors",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_update_item"
))]
pub use crate::types::error::_request_limit_exceeded::RequestLimitExceeded;

#[cfg(any(
    feature = "op_batch_execute_statement",
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_get_item",
    feature = "op_put_item",
    feature = "op_query",
    feature = "op_scan",
    feature = "op_search_vectors",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_update_item"
))]
pub use crate::types::error::_throttling_exception::ThrottlingException;

#[cfg(any(
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_create_backup",
    feature = "op_create_global_table",
    feature = "op_create_table",
    feature = "op_delete_backup",
    feature = "op_delete_item",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_describe_backup",
    feature = "op_describe_continuous_backups",
    feature = "op_describe_global_table",
    feature = "op_describe_global_table_settings",
    feature = "op_describe_kinesis_streaming_destination",
    feature = "op_describe_limits",
    feature = "op_describe_table",
    feature = "op_describe_time_to_live",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_get_item",
    feature = "op_get_resource_policy",
    feature = "op_list_backups",
    feature = "op_list_global_tables",
    feature = "op_list_tables",
    feature = "op_list_tags_of_resource",
    feature = "op_put_item",
    feature = "op_put_resource_policy",
    feature = "op_query",
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time",
    feature = "op_scan",
    feature = "op_tag_resource",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_untag_resource",
    feature = "op_update_continuous_backups",
    feature = "op_update_global_table",
    feature = "op_update_global_table_settings",
    feature = "op_update_item",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_time_to_live"
))]
pub use crate::types::error::_invalid_endpoint_exception::InvalidEndpointException;

#[cfg(any(
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_get_item",
    feature = "op_put_item",
    feature = "op_query",
    feature = "op_scan",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_update_item"
))]
pub use crate::types::error::_provisioned_throughput_exceeded_exception::ProvisionedThroughputExceededException;

#[cfg(any(
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_describe_contributor_insights",
    feature = "op_describe_kinesis_streaming_destination",
    feature = "op_describe_table",
    feature = "op_describe_table_replica_auto_scaling",
    feature = "op_describe_time_to_live",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_get_item",
    feature = "op_get_resource_policy",
    feature = "op_list_contributor_insights",
    feature = "op_list_tags_of_resource",
    feature = "op_put_item",
    feature = "op_put_resource_policy",
    feature = "op_query",
    feature = "op_scan",
    feature = "op_search_vectors",
    feature = "op_tag_resource",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_untag_resource",
    feature = "op_update_contributor_insights",
    feature = "op_update_item",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_table_replica_auto_scaling",
    feature = "op_update_time_to_live"
))]
pub use crate::types::error::_resource_not_found_exception::ResourceNotFoundException;

#[cfg(any(
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_put_item",
    feature = "op_update_item"
))]
pub use crate::types::error::_item_collection_size_limit_exceeded_exception::ItemCollectionSizeLimitExceededException;

#[cfg(any(
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_put_item",
    feature = "op_update_item"
))]
pub use crate::types::error::_replicated_write_conflict_exception::ReplicatedWriteConflictException;

#[cfg(any(
    feature = "op_create_backup",
    feature = "op_delete_backup",
    feature = "op_restore_table_from_backup"
))]
pub use crate::types::error::_backup_in_use_exception::BackupInUseException;

#[cfg(any(feature = "op_create_backup", feature = "op_update_continuous_backups"))]
pub use crate::types::error::_continuous_backups_unavailable_exception::ContinuousBackupsUnavailableException;

#[cfg(any(
    feature = "op_create_backup",
    feature = "op_create_global_table",
    feature = "op_create_table",
    feature = "op_delete_backup",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_describe_export",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_export_table_to_point_in_time",
    feature = "op_import_table",
    feature = "op_list_exports",
    feature = "op_list_imports",
    feature = "op_put_resource_policy",
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_global_table_settings",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_table_replica_auto_scaling",
    feature = "op_update_time_to_live"
))]
pub use crate::types::error::_limit_exceeded_exception::LimitExceededException;

#[cfg(any(
    feature = "op_create_backup",
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time"
))]
pub use crate::types::error::_table_in_use_exception::TableInUseException;

#[cfg(any(
    feature = "op_create_backup",
    feature = "op_create_global_table",
    feature = "op_describe_continuous_backups",
    feature = "op_export_table_to_point_in_time",
    feature = "op_restore_table_to_point_in_time",
    feature = "op_update_continuous_backups",
    feature = "op_update_global_table"
))]
pub use crate::types::error::_table_not_found_exception::TableNotFoundException;

#[cfg(feature = "op_create_global_table")]
pub use crate::types::error::_global_table_already_exists_exception::GlobalTableAlreadyExistsException;

#[cfg(any(
    feature = "op_create_table",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_import_table",
    feature = "op_put_resource_policy",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_global_table_settings",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_table_replica_auto_scaling",
    feature = "op_update_time_to_live"
))]
pub use crate::types::error::_resource_in_use_exception::ResourceInUseException;

#[cfg(any(
    feature = "op_delete_backup",
    feature = "op_describe_backup",
    feature = "op_restore_table_from_backup"
))]
pub use crate::types::error::_backup_not_found_exception::BackupNotFoundException;

#[cfg(any(
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_put_item",
    feature = "op_update_item"
))]
pub use crate::types::error::_conditional_check_failed_exception::ConditionalCheckFailedException;

#[cfg(any(
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_put_item",
    feature = "op_update_item"
))]
pub use crate::types::error::_transaction_conflict_exception::TransactionConflictException;

#[cfg(any(
    feature = "op_delete_resource_policy",
    feature = "op_get_resource_policy",
    feature = "op_put_resource_policy"
))]
pub use crate::types::error::_policy_not_found_exception::PolicyNotFoundException;

#[cfg(feature = "op_describe_export")]
pub use crate::types::error::_export_not_found_exception::ExportNotFoundException;

#[cfg(any(
    feature = "op_describe_global_table",
    feature = "op_describe_global_table_settings",
    feature = "op_update_global_table",
    feature = "op_update_global_table_settings"
))]
pub use crate::types::error::_global_table_not_found_exception::GlobalTableNotFoundException;

#[cfg(feature = "op_describe_import")]
pub use crate::types::error::_import_not_found_exception::ImportNotFoundException;

#[cfg(feature = "op_execute_statement")]
pub use crate::types::error::_duplicate_item_exception::DuplicateItemException;

#[cfg(any(feature = "op_execute_transaction", feature = "op_transact_write_items"))]
pub use crate::types::error::_idempotent_parameter_mismatch_exception::IdempotentParameterMismatchException;

#[cfg(any(
    feature = "op_execute_transaction",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items"
))]
pub use crate::types::error::_transaction_canceled_exception::TransactionCanceledException;

#[cfg(any(feature = "op_execute_transaction", feature = "op_transact_write_items"))]
pub use crate::types::error::_transaction_in_progress_exception::TransactionInProgressException;

#[cfg(feature = "op_export_table_to_point_in_time")]
pub use crate::types::error::_export_conflict_exception::ExportConflictException;

#[cfg(feature = "op_export_table_to_point_in_time")]
pub use crate::types::error::_invalid_export_time_exception::InvalidExportTimeException;

#[cfg(any(
    feature = "op_export_table_to_point_in_time",
    feature = "op_restore_table_to_point_in_time"
))]
pub use crate::types::error::_point_in_time_recovery_unavailable_exception::PointInTimeRecoveryUnavailableException;

#[cfg(feature = "op_import_table")]
pub use crate::types::error::_import_conflict_exception::ImportConflictException;

#[cfg(any(
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time"
))]
pub use crate::types::error::_table_already_exists_exception::TableAlreadyExistsException;

#[cfg(feature = "op_restore_table_to_point_in_time")]
pub use crate::types::error::_invalid_restore_time_exception::InvalidRestoreTimeException;

#[cfg(feature = "op_update_global_table")]
pub use crate::types::error::_replica_already_exists_exception::ReplicaAlreadyExistsException;

#[cfg(any(feature = "op_update_global_table", feature = "op_update_global_table_settings"))]
pub use crate::types::error::_replica_not_found_exception::ReplicaNotFoundException;

#[cfg(feature = "op_update_global_table_settings")]
pub use crate::types::error::_index_not_found_exception::IndexNotFoundException;

#[cfg(any(
    feature = "op_create_backup",
    feature = "op_delete_backup",
    feature = "op_restore_table_from_backup"
))]
mod _backup_in_use_exception;

#[cfg(any(
    feature = "op_delete_backup",
    feature = "op_describe_backup",
    feature = "op_restore_table_from_backup"
))]
mod _backup_not_found_exception;

#[cfg(any(
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_put_item",
    feature = "op_update_item"
))]
mod _conditional_check_failed_exception;

#[cfg(any(feature = "op_create_backup", feature = "op_update_continuous_backups"))]
mod _continuous_backups_unavailable_exception;

#[cfg(feature = "op_execute_statement")]
mod _duplicate_item_exception;

#[cfg(feature = "op_export_table_to_point_in_time")]
mod _export_conflict_exception;

#[cfg(feature = "op_describe_export")]
mod _export_not_found_exception;

#[cfg(feature = "op_create_global_table")]
mod _global_table_already_exists_exception;

#[cfg(any(
    feature = "op_describe_global_table",
    feature = "op_describe_global_table_settings",
    feature = "op_update_global_table",
    feature = "op_update_global_table_settings"
))]
mod _global_table_not_found_exception;

#[cfg(any(feature = "op_execute_transaction", feature = "op_transact_write_items"))]
mod _idempotent_parameter_mismatch_exception;

#[cfg(feature = "op_import_table")]
mod _import_conflict_exception;

#[cfg(feature = "op_describe_import")]
mod _import_not_found_exception;

#[cfg(feature = "op_update_global_table_settings")]
mod _index_not_found_exception;

#[cfg(any(
    feature = "op_batch_execute_statement",
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_create_backup",
    feature = "op_create_global_table",
    feature = "op_create_table",
    feature = "op_delete_backup",
    feature = "op_delete_item",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_describe_backup",
    feature = "op_describe_continuous_backups",
    feature = "op_describe_contributor_insights",
    feature = "op_describe_export",
    feature = "op_describe_global_table",
    feature = "op_describe_global_table_settings",
    feature = "op_describe_kinesis_streaming_destination",
    feature = "op_describe_limits",
    feature = "op_describe_table",
    feature = "op_describe_table_replica_auto_scaling",
    feature = "op_describe_time_to_live",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_export_table_to_point_in_time",
    feature = "op_get_item",
    feature = "op_get_resource_policy",
    feature = "op_list_backups",
    feature = "op_list_contributor_insights",
    feature = "op_list_exports",
    feature = "op_list_global_tables",
    feature = "op_list_tables",
    feature = "op_list_tags_of_resource",
    feature = "op_put_item",
    feature = "op_put_resource_policy",
    feature = "op_query",
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time",
    feature = "op_scan",
    feature = "op_search_vectors",
    feature = "op_tag_resource",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_untag_resource",
    feature = "op_update_continuous_backups",
    feature = "op_update_contributor_insights",
    feature = "op_update_global_table",
    feature = "op_update_global_table_settings",
    feature = "op_update_item",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_table_replica_auto_scaling",
    feature = "op_update_time_to_live"
))]
mod _internal_server_error;

#[cfg(any(
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_create_backup",
    feature = "op_create_global_table",
    feature = "op_create_table",
    feature = "op_delete_backup",
    feature = "op_delete_item",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_describe_backup",
    feature = "op_describe_continuous_backups",
    feature = "op_describe_global_table",
    feature = "op_describe_global_table_settings",
    feature = "op_describe_kinesis_streaming_destination",
    feature = "op_describe_limits",
    feature = "op_describe_table",
    feature = "op_describe_time_to_live",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_get_item",
    feature = "op_get_resource_policy",
    feature = "op_list_backups",
    feature = "op_list_global_tables",
    feature = "op_list_tables",
    feature = "op_list_tags_of_resource",
    feature = "op_put_item",
    feature = "op_put_resource_policy",
    feature = "op_query",
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time",
    feature = "op_scan",
    feature = "op_tag_resource",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_untag_resource",
    feature = "op_update_continuous_backups",
    feature = "op_update_global_table",
    feature = "op_update_global_table_settings",
    feature = "op_update_item",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_time_to_live"
))]
mod _invalid_endpoint_exception;

#[cfg(feature = "op_export_table_to_point_in_time")]
mod _invalid_export_time_exception;

#[cfg(feature = "op_restore_table_to_point_in_time")]
mod _invalid_restore_time_exception;

#[cfg(any(
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_put_item",
    feature = "op_update_item"
))]
mod _item_collection_size_limit_exceeded_exception;

#[cfg(any(
    feature = "op_create_backup",
    feature = "op_create_global_table",
    feature = "op_create_table",
    feature = "op_delete_backup",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_describe_export",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_export_table_to_point_in_time",
    feature = "op_import_table",
    feature = "op_list_exports",
    feature = "op_list_imports",
    feature = "op_put_resource_policy",
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_global_table_settings",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_table_replica_auto_scaling",
    feature = "op_update_time_to_live"
))]
mod _limit_exceeded_exception;

#[cfg(any(
    feature = "op_export_table_to_point_in_time",
    feature = "op_restore_table_to_point_in_time"
))]
mod _point_in_time_recovery_unavailable_exception;

#[cfg(any(
    feature = "op_delete_resource_policy",
    feature = "op_get_resource_policy",
    feature = "op_put_resource_policy"
))]
mod _policy_not_found_exception;

#[cfg(any(
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_get_item",
    feature = "op_put_item",
    feature = "op_query",
    feature = "op_scan",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_update_item"
))]
mod _provisioned_throughput_exceeded_exception;

#[cfg(feature = "op_update_global_table")]
mod _replica_already_exists_exception;

#[cfg(any(feature = "op_update_global_table", feature = "op_update_global_table_settings"))]
mod _replica_not_found_exception;

#[cfg(any(
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_put_item",
    feature = "op_update_item"
))]
mod _replicated_write_conflict_exception;

#[cfg(any(
    feature = "op_batch_execute_statement",
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_get_item",
    feature = "op_put_item",
    feature = "op_query",
    feature = "op_scan",
    feature = "op_search_vectors",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_update_item"
))]
mod _request_limit_exceeded;

#[cfg(any(
    feature = "op_create_table",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_import_table",
    feature = "op_put_resource_policy",
    feature = "op_tag_resource",
    feature = "op_untag_resource",
    feature = "op_update_global_table_settings",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_table_replica_auto_scaling",
    feature = "op_update_time_to_live"
))]
mod _resource_in_use_exception;

#[cfg(any(
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_delete_resource_policy",
    feature = "op_delete_table",
    feature = "op_describe_contributor_insights",
    feature = "op_describe_kinesis_streaming_destination",
    feature = "op_describe_table",
    feature = "op_describe_table_replica_auto_scaling",
    feature = "op_describe_time_to_live",
    feature = "op_disable_kinesis_streaming_destination",
    feature = "op_enable_kinesis_streaming_destination",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_get_item",
    feature = "op_get_resource_policy",
    feature = "op_list_contributor_insights",
    feature = "op_list_tags_of_resource",
    feature = "op_put_item",
    feature = "op_put_resource_policy",
    feature = "op_query",
    feature = "op_scan",
    feature = "op_search_vectors",
    feature = "op_tag_resource",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_untag_resource",
    feature = "op_update_contributor_insights",
    feature = "op_update_item",
    feature = "op_update_kinesis_streaming_destination",
    feature = "op_update_table",
    feature = "op_update_table_replica_auto_scaling",
    feature = "op_update_time_to_live"
))]
mod _resource_not_found_exception;

#[cfg(any(
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time"
))]
mod _table_already_exists_exception;

#[cfg(any(
    feature = "op_create_backup",
    feature = "op_restore_table_from_backup",
    feature = "op_restore_table_to_point_in_time"
))]
mod _table_in_use_exception;

#[cfg(any(
    feature = "op_create_backup",
    feature = "op_create_global_table",
    feature = "op_describe_continuous_backups",
    feature = "op_export_table_to_point_in_time",
    feature = "op_restore_table_to_point_in_time",
    feature = "op_update_continuous_backups",
    feature = "op_update_global_table"
))]
mod _table_not_found_exception;

#[cfg(any(
    feature = "op_batch_execute_statement",
    feature = "op_batch_get_item",
    feature = "op_batch_write_item",
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_execute_transaction",
    feature = "op_get_item",
    feature = "op_put_item",
    feature = "op_query",
    feature = "op_scan",
    feature = "op_search_vectors",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items",
    feature = "op_update_item"
))]
mod _throttling_exception;

#[cfg(any(
    feature = "op_execute_transaction",
    feature = "op_transact_get_items",
    feature = "op_transact_write_items"
))]
mod _transaction_canceled_exception;

#[cfg(any(
    feature = "op_delete_item",
    feature = "op_execute_statement",
    feature = "op_put_item",
    feature = "op_update_item"
))]
mod _transaction_conflict_exception;

#[cfg(any(feature = "op_execute_transaction", feature = "op_transact_write_items"))]
mod _transaction_in_progress_exception;

/// Builders
pub mod builders;
