// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_tag_instance_profile")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct TagInstanceProfileOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_tag_instance_profile")]
impl ::aws_types::request_id::RequestId for TagInstanceProfileOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_tag_instance_profile")]
impl TagInstanceProfileOutput {
    /// Creates a new builder-style object to manufacture [`TagInstanceProfileOutput`](crate::operation::tag_instance_profile::TagInstanceProfileOutput).
    pub fn builder() -> crate::operation::tag_instance_profile::builders::TagInstanceProfileOutputBuilder {
        crate::operation::tag_instance_profile::builders::TagInstanceProfileOutputBuilder::default()
    }
}

#[cfg(feature = "op_tag_instance_profile")]
/// A builder for [`TagInstanceProfileOutput`](crate::operation::tag_instance_profile::TagInstanceProfileOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct TagInstanceProfileOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_tag_instance_profile")]
impl TagInstanceProfileOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`TagInstanceProfileOutput`](crate::operation::tag_instance_profile::TagInstanceProfileOutput).
    pub fn build(self) -> crate::operation::tag_instance_profile::TagInstanceProfileOutput {
        crate::operation::tag_instance_profile::TagInstanceProfileOutput {
            _request_id: self._request_id,
        }
    }
}
