// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_syslog_configuration")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteSyslogConfigurationOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_syslog_configuration")]
impl ::aws_types::request_id::RequestId for DeleteSyslogConfigurationOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_delete_syslog_configuration")]
impl DeleteSyslogConfigurationOutput {
    /// Creates a new builder-style object to manufacture [`DeleteSyslogConfigurationOutput`](crate::operation::delete_syslog_configuration::DeleteSyslogConfigurationOutput).
    pub fn builder() -> crate::operation::delete_syslog_configuration::builders::DeleteSyslogConfigurationOutputBuilder{
        crate::operation::delete_syslog_configuration::builders::DeleteSyslogConfigurationOutputBuilder::default()
    }
}

#[cfg(feature = "op_delete_syslog_configuration")]
/// A builder for [`DeleteSyslogConfigurationOutput`](crate::operation::delete_syslog_configuration::DeleteSyslogConfigurationOutput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct DeleteSyslogConfigurationOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_syslog_configuration")]
impl DeleteSyslogConfigurationOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DeleteSyslogConfigurationOutput`](crate::operation::delete_syslog_configuration::DeleteSyslogConfigurationOutput).
    pub fn build(
        self,
    ) -> crate::operation::delete_syslog_configuration::DeleteSyslogConfigurationOutput {
        crate::operation::delete_syslog_configuration::DeleteSyslogConfigurationOutput {
            _request_id: self._request_id,
        }
    }
}
