// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_open_id_connect_provider")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteOpenIdConnectProviderOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_open_id_connect_provider")]
impl ::aws_types::request_id::RequestId for DeleteOpenIdConnectProviderOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_delete_open_id_connect_provider")]
impl DeleteOpenIdConnectProviderOutput {
    /// Creates a new builder-style object to manufacture [`DeleteOpenIdConnectProviderOutput`](crate::operation::delete_open_id_connect_provider::DeleteOpenIdConnectProviderOutput).
    pub fn builder() -> crate::operation::delete_open_id_connect_provider::builders::DeleteOpenIdConnectProviderOutputBuilder {
        crate::operation::delete_open_id_connect_provider::builders::DeleteOpenIdConnectProviderOutputBuilder::default()
    }
}

#[cfg(feature = "op_delete_open_id_connect_provider")]
/// A builder for [`DeleteOpenIdConnectProviderOutput`](crate::operation::delete_open_id_connect_provider::DeleteOpenIdConnectProviderOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DeleteOpenIdConnectProviderOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_open_id_connect_provider")]
impl DeleteOpenIdConnectProviderOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DeleteOpenIdConnectProviderOutput`](crate::operation::delete_open_id_connect_provider::DeleteOpenIdConnectProviderOutput).
    pub fn build(self) -> crate::operation::delete_open_id_connect_provider::DeleteOpenIdConnectProviderOutput {
        crate::operation::delete_open_id_connect_provider::DeleteOpenIdConnectProviderOutput {
            _request_id: self._request_id,
        }
    }
}
