// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Contains metadata about a lookup table returned by <code>DescribeLookupTables</code>.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct LookupTable {
    /// <p>The ARN of the lookup table.</p>
    pub lookup_table_arn: ::std::option::Option<::std::string::String>,
    /// <p>The name of the lookup table.</p>
    pub lookup_table_name: ::std::option::Option<::std::string::String>,
    /// <p>The description of the lookup table.</p>
    pub description: ::std::option::Option<::std::string::String>,
    /// <p>The column headers from the first row of the CSV file.</p>
    pub table_fields: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    /// <p>The number of data rows in the lookup table, excluding the header row.</p>
    pub records_count: ::std::option::Option<i64>,
    /// <p>The size of the lookup table in bytes.</p>
    pub size_bytes: ::std::option::Option<i64>,
    /// <p>The time when the lookup table was last updated, expressed as the number of milliseconds after <code>Jan 1, 1970 00:00:00 UTC</code>.</p>
    pub last_updated_time: ::std::option::Option<i64>,
    /// <p>The ARN of the KMS key used to encrypt the lookup table data, if applicable.</p>
    pub kms_key_id: ::std::option::Option<::std::string::String>,
}
impl LookupTable {
    /// <p>The ARN of the lookup table.</p>
    pub fn lookup_table_arn(&self) -> ::std::option::Option<&str> {
        self.lookup_table_arn.as_deref()
    }
    /// <p>The name of the lookup table.</p>
    pub fn lookup_table_name(&self) -> ::std::option::Option<&str> {
        self.lookup_table_name.as_deref()
    }
    /// <p>The description of the lookup table.</p>
    pub fn description(&self) -> ::std::option::Option<&str> {
        self.description.as_deref()
    }
    /// <p>The column headers from the first row of the CSV file.</p>
    ///
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.table_fields.is_none()`.
    pub fn table_fields(&self) -> &[::std::string::String] {
        self.table_fields.as_deref().unwrap_or_default()
    }
    /// <p>The number of data rows in the lookup table, excluding the header row.</p>
    pub fn records_count(&self) -> ::std::option::Option<i64> {
        self.records_count
    }
    /// <p>The size of the lookup table in bytes.</p>
    pub fn size_bytes(&self) -> ::std::option::Option<i64> {
        self.size_bytes
    }
    /// <p>The time when the lookup table was last updated, expressed as the number of milliseconds after <code>Jan 1, 1970 00:00:00 UTC</code>.</p>
    pub fn last_updated_time(&self) -> ::std::option::Option<i64> {
        self.last_updated_time
    }
    /// <p>The ARN of the KMS key used to encrypt the lookup table data, if applicable.</p>
    pub fn kms_key_id(&self) -> ::std::option::Option<&str> {
        self.kms_key_id.as_deref()
    }
}
impl LookupTable {
    /// Creates a new builder-style object to manufacture [`LookupTable`](crate::types::LookupTable).
    pub fn builder() -> crate::types::builders::LookupTableBuilder {
        crate::types::builders::LookupTableBuilder::default()
    }
}

/// A builder for [`LookupTable`](crate::types::LookupTable).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct LookupTableBuilder {
    pub(crate) lookup_table_arn: ::std::option::Option<::std::string::String>,
    pub(crate) lookup_table_name: ::std::option::Option<::std::string::String>,
    pub(crate) description: ::std::option::Option<::std::string::String>,
    pub(crate) table_fields: ::std::option::Option<::std::vec::Vec<::std::string::String>>,
    pub(crate) records_count: ::std::option::Option<i64>,
    pub(crate) size_bytes: ::std::option::Option<i64>,
    pub(crate) last_updated_time: ::std::option::Option<i64>,
    pub(crate) kms_key_id: ::std::option::Option<::std::string::String>,
}
impl LookupTableBuilder {
    /// <p>The ARN of the lookup table.</p>
    pub fn lookup_table_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.lookup_table_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ARN of the lookup table.</p>
    pub fn set_lookup_table_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.lookup_table_arn = input;
        self
    }
    /// <p>The ARN of the lookup table.</p>
    pub fn get_lookup_table_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.lookup_table_arn
    }
    /// <p>The name of the lookup table.</p>
    pub fn lookup_table_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.lookup_table_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the lookup table.</p>
    pub fn set_lookup_table_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.lookup_table_name = input;
        self
    }
    /// <p>The name of the lookup table.</p>
    pub fn get_lookup_table_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.lookup_table_name
    }
    /// <p>The description of the lookup table.</p>
    pub fn description(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.description = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The description of the lookup table.</p>
    pub fn set_description(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.description = input;
        self
    }
    /// <p>The description of the lookup table.</p>
    pub fn get_description(&self) -> &::std::option::Option<::std::string::String> {
        &self.description
    }
    /// Appends an item to `table_fields`.
    ///
    /// To override the contents of this collection use [`set_table_fields`](Self::set_table_fields).
    ///
    /// <p>The column headers from the first row of the CSV file.</p>
    pub fn table_fields(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.table_fields.unwrap_or_default();
        v.push(input.into());
        self.table_fields = ::std::option::Option::Some(v);
        self
    }
    /// <p>The column headers from the first row of the CSV file.</p>
    pub fn set_table_fields(mut self, input: ::std::option::Option<::std::vec::Vec<::std::string::String>>) -> Self {
        self.table_fields = input;
        self
    }
    /// <p>The column headers from the first row of the CSV file.</p>
    pub fn get_table_fields(&self) -> &::std::option::Option<::std::vec::Vec<::std::string::String>> {
        &self.table_fields
    }
    /// <p>The number of data rows in the lookup table, excluding the header row.</p>
    pub fn records_count(mut self, input: i64) -> Self {
        self.records_count = ::std::option::Option::Some(input);
        self
    }
    /// <p>The number of data rows in the lookup table, excluding the header row.</p>
    pub fn set_records_count(mut self, input: ::std::option::Option<i64>) -> Self {
        self.records_count = input;
        self
    }
    /// <p>The number of data rows in the lookup table, excluding the header row.</p>
    pub fn get_records_count(&self) -> &::std::option::Option<i64> {
        &self.records_count
    }
    /// <p>The size of the lookup table in bytes.</p>
    pub fn size_bytes(mut self, input: i64) -> Self {
        self.size_bytes = ::std::option::Option::Some(input);
        self
    }
    /// <p>The size of the lookup table in bytes.</p>
    pub fn set_size_bytes(mut self, input: ::std::option::Option<i64>) -> Self {
        self.size_bytes = input;
        self
    }
    /// <p>The size of the lookup table in bytes.</p>
    pub fn get_size_bytes(&self) -> &::std::option::Option<i64> {
        &self.size_bytes
    }
    /// <p>The time when the lookup table was last updated, expressed as the number of milliseconds after <code>Jan 1, 1970 00:00:00 UTC</code>.</p>
    pub fn last_updated_time(mut self, input: i64) -> Self {
        self.last_updated_time = ::std::option::Option::Some(input);
        self
    }
    /// <p>The time when the lookup table was last updated, expressed as the number of milliseconds after <code>Jan 1, 1970 00:00:00 UTC</code>.</p>
    pub fn set_last_updated_time(mut self, input: ::std::option::Option<i64>) -> Self {
        self.last_updated_time = input;
        self
    }
    /// <p>The time when the lookup table was last updated, expressed as the number of milliseconds after <code>Jan 1, 1970 00:00:00 UTC</code>.</p>
    pub fn get_last_updated_time(&self) -> &::std::option::Option<i64> {
        &self.last_updated_time
    }
    /// <p>The ARN of the KMS key used to encrypt the lookup table data, if applicable.</p>
    pub fn kms_key_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.kms_key_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ARN of the KMS key used to encrypt the lookup table data, if applicable.</p>
    pub fn set_kms_key_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.kms_key_id = input;
        self
    }
    /// <p>The ARN of the KMS key used to encrypt the lookup table data, if applicable.</p>
    pub fn get_kms_key_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.kms_key_id
    }
    /// Consumes the builder and constructs a [`LookupTable`](crate::types::LookupTable).
    pub fn build(self) -> crate::types::LookupTable {
        crate::types::LookupTable {
            lookup_table_arn: self.lookup_table_arn,
            lookup_table_name: self.lookup_table_name,
            description: self.description,
            table_fields: self.table_fields,
            records_count: self.records_count,
            size_bytes: self.size_bytes,
            last_updated_time: self.last_updated_time,
            kms_key_id: self.kms_key_id,
        }
    }
}
