// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_contact")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteContactOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_contact")]
impl ::aws_types::request_id::RequestId for DeleteContactOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_delete_contact")]
impl DeleteContactOutput {
    /// Creates a new builder-style object to manufacture [`DeleteContactOutput`](crate::operation::delete_contact::DeleteContactOutput).
    pub fn builder() -> crate::operation::delete_contact::builders::DeleteContactOutputBuilder {
        crate::operation::delete_contact::builders::DeleteContactOutputBuilder::default()
    }
}

#[cfg(feature = "op_delete_contact")]
/// A builder for [`DeleteContactOutput`](crate::operation::delete_contact::DeleteContactOutput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct DeleteContactOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_contact")]
impl DeleteContactOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DeleteContactOutput`](crate::operation::delete_contact::DeleteContactOutput).
    pub fn build(self) -> crate::operation::delete_contact::DeleteContactOutput {
        crate::operation::delete_contact::DeleteContactOutput {
            _request_id: self._request_id,
        }
    }
}
