[workspace]
members = ["crates/*", "examples/my_aws_sdk", "examples/multi_service"]
resolver = "2"

[profile.dev]
debug = 0

[profile.dev.package.syn]
opt-level = 3

[profile.dev.package.diffy]
opt-level = 3

# Keep conformance in the debug profile while optimizing its CPU-heavy paths.
[profile.dev.package.aws-sdk-conformance]
opt-level = 1

[profile.release]
debug = 0

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/notmd/better-aws"
