// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_sms_sandbox_phone_number")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct DeleteSmsSandboxPhoneNumberInput {
    /// <p>The destination phone number to delete.</p>
    pub phone_number: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_delete_sms_sandbox_phone_number")]
impl DeleteSmsSandboxPhoneNumberInput {
    /// <p>The destination phone number to delete.</p>
    pub fn phone_number(&self) -> ::std::option::Option<&str> {
        self.phone_number.as_deref()
    }
}
#[cfg(feature = "op_delete_sms_sandbox_phone_number")]
impl ::std::fmt::Debug for DeleteSmsSandboxPhoneNumberInput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("DeleteSmsSandboxPhoneNumberInput");
        formatter.field("phone_number", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
#[cfg(feature = "op_delete_sms_sandbox_phone_number")]
impl DeleteSmsSandboxPhoneNumberInput {
    /// Creates a new builder-style object to manufacture [`DeleteSmsSandboxPhoneNumberInput`](crate::operation::delete_sms_sandbox_phone_number::DeleteSmsSandboxPhoneNumberInput).
    pub fn builder() -> crate::operation::delete_sms_sandbox_phone_number::builders::DeleteSmsSandboxPhoneNumberInputBuilder{
        crate::operation::delete_sms_sandbox_phone_number::builders::DeleteSmsSandboxPhoneNumberInputBuilder::default()
    }
}

#[cfg(feature = "op_delete_sms_sandbox_phone_number")]
/// A builder for [`DeleteSmsSandboxPhoneNumberInput`](crate::operation::delete_sms_sandbox_phone_number::DeleteSmsSandboxPhoneNumberInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct DeleteSmsSandboxPhoneNumberInputBuilder {
    pub(crate) phone_number: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_delete_sms_sandbox_phone_number")]
impl DeleteSmsSandboxPhoneNumberInputBuilder {
    /// <p>The destination phone number to delete.</p>
    /// This field is required.
    pub fn phone_number(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.phone_number = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The destination phone number to delete.</p>
    pub fn set_phone_number(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.phone_number = input;
        self
    }
    /// <p>The destination phone number to delete.</p>
    pub fn get_phone_number(&self) -> &::std::option::Option<::std::string::String> {
        &self.phone_number
    }
    /// Consumes the builder and constructs a [`DeleteSmsSandboxPhoneNumberInput`](crate::operation::delete_sms_sandbox_phone_number::DeleteSmsSandboxPhoneNumberInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::delete_sms_sandbox_phone_number::DeleteSmsSandboxPhoneNumberInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::delete_sms_sandbox_phone_number::DeleteSmsSandboxPhoneNumberInput {
                phone_number: self.phone_number,
            },
        )
    }
}
#[cfg(feature = "op_delete_sms_sandbox_phone_number")]
impl ::std::fmt::Debug for DeleteSmsSandboxPhoneNumberInputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("DeleteSmsSandboxPhoneNumberInputBuilder");
        formatter.field("phone_number", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
