// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_scheduling_policy_input_input(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::operation::create_scheduling_policy::CreateSchedulingPolicyInput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.fairshare_policy {
        #[allow(unused_mut)]
        let mut object_2 = object.key("fairsharePolicy").start_object();
        crate::protocol_serde::shape_fairshare_policy::ser_fairshare_policy(&mut object_2, var_1)?;
        object_2.finish();
    }
    if let Some(var_3) = &input.name {
        object.key("name").string(var_3.as_str());
    }
    if let Some(var_4) = &input.quota_share_policy {
        #[allow(unused_mut)]
        let mut object_5 = object.key("quotaSharePolicy").start_object();
        crate::protocol_serde::shape_quota_share_policy::ser_quota_share_policy(&mut object_5, var_4)?;
        object_5.finish();
    }
    if let Some(var_6) = &input.tags {
        #[allow(unused_mut)]
        let mut object_7 = object.key("tags").start_object();
        for (key_8, value_9) in var_6 {
            {
                object_7.key(key_8.as_str()).string(value_9.as_str());
            }
        }
        object_7.finish();
    }
    Ok(())
}
