// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_data_protection_policy")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteDataProtectionPolicyOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_data_protection_policy")]
impl ::aws_types::request_id::RequestId for DeleteDataProtectionPolicyOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_delete_data_protection_policy")]
impl DeleteDataProtectionPolicyOutput {
    /// Creates a new builder-style object to manufacture [`DeleteDataProtectionPolicyOutput`](crate::operation::delete_data_protection_policy::DeleteDataProtectionPolicyOutput).
    pub fn builder() -> crate::operation::delete_data_protection_policy::builders::DeleteDataProtectionPolicyOutputBuilder{
        crate::operation::delete_data_protection_policy::builders::DeleteDataProtectionPolicyOutputBuilder::default()
    }
}

#[cfg(feature = "op_delete_data_protection_policy")]
/// A builder for [`DeleteDataProtectionPolicyOutput`](crate::operation::delete_data_protection_policy::DeleteDataProtectionPolicyOutput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct DeleteDataProtectionPolicyOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_data_protection_policy")]
impl DeleteDataProtectionPolicyOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DeleteDataProtectionPolicyOutput`](crate::operation::delete_data_protection_policy::DeleteDataProtectionPolicyOutput).
    pub fn build(
        self,
    ) -> crate::operation::delete_data_protection_policy::DeleteDataProtectionPolicyOutput {
        crate::operation::delete_data_protection_policy::DeleteDataProtectionPolicyOutput {
            _request_id: self._request_id,
        }
    }
}
