[package]
name = "my_aws_sdk"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
aws-sdk-builder-s3 = { path = "../../crates/aws-sdk-builder-s3" }
aws-runtime = "1.9.1"
aws-types = "1.5.0"
aws-smithy-runtime-api = "1.15.0"
aws-smithy-types = "1.6.2"
http-1x = { package = "http", version = "1.5.0" }

[build-dependencies]
aws-sdk-builder-s3 = { path = "../../crates/aws-sdk-builder-s3" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
