// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Specifies whether a quota share reserves, lends, or both lends and borrows idle compute capacity.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct QuotaShareResourceSharingConfiguration {
    /// <p>The resource sharing strategy for the quota share. The <code>RESERVE</code> strategy allows a quota share to reserve idle capacity for itself. <code>LEND</code> configures the share to lend its idle capacity to another share in need of capacity. The <code>LEND_AND_BORROW</code> strategy configures the share to borrow idle capacity from an underutilized share, as well as lend to another share.</p>
    pub strategy: ::std::option::Option<crate::types::QuotaShareResourceSharingStrategy>,
    /// <p>The maximum percentage of additional capacity that the quota share can borrow from other shares. <code>borrowLimit</code> can only be applied to quota shares with a strategy of <code>LEND_AND_BORROW</code>. This value is expressed as a percentage of the quota share's configured <a href="https://docs.aws.amazon.com/batch/latest/APIReference/API_QuotaShareCapacityLimit.html">CapacityLimits</a>.</p>
    /// <p>The <code>borrowLimit</code> is applied uniformly across all capacity units. For example, if the <code>borrowLimit</code> is 200, the quota share can borrow up to 200% of its configured <code>maxCapacity</code> for each capacity unit. The default <code>borrowLimit</code> is -1, which indicates unlimited borrowing.</p>
    pub borrow_limit: ::std::option::Option<i32>,
}
impl QuotaShareResourceSharingConfiguration {
    /// <p>The resource sharing strategy for the quota share. The <code>RESERVE</code> strategy allows a quota share to reserve idle capacity for itself. <code>LEND</code> configures the share to lend its idle capacity to another share in need of capacity. The <code>LEND_AND_BORROW</code> strategy configures the share to borrow idle capacity from an underutilized share, as well as lend to another share.</p>
    pub fn strategy(&self) -> ::std::option::Option<&crate::types::QuotaShareResourceSharingStrategy> {
        self.strategy.as_ref()
    }
    /// <p>The maximum percentage of additional capacity that the quota share can borrow from other shares. <code>borrowLimit</code> can only be applied to quota shares with a strategy of <code>LEND_AND_BORROW</code>. This value is expressed as a percentage of the quota share's configured <a href="https://docs.aws.amazon.com/batch/latest/APIReference/API_QuotaShareCapacityLimit.html">CapacityLimits</a>.</p>
    /// <p>The <code>borrowLimit</code> is applied uniformly across all capacity units. For example, if the <code>borrowLimit</code> is 200, the quota share can borrow up to 200% of its configured <code>maxCapacity</code> for each capacity unit. The default <code>borrowLimit</code> is -1, which indicates unlimited borrowing.</p>
    pub fn borrow_limit(&self) -> ::std::option::Option<i32> {
        self.borrow_limit
    }
}
impl QuotaShareResourceSharingConfiguration {
    /// Creates a new builder-style object to manufacture [`QuotaShareResourceSharingConfiguration`](crate::types::QuotaShareResourceSharingConfiguration).
    pub fn builder() -> crate::types::builders::QuotaShareResourceSharingConfigurationBuilder {
        crate::types::builders::QuotaShareResourceSharingConfigurationBuilder::default()
    }
}

/// A builder for [`QuotaShareResourceSharingConfiguration`](crate::types::QuotaShareResourceSharingConfiguration).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct QuotaShareResourceSharingConfigurationBuilder {
    pub(crate) strategy: ::std::option::Option<crate::types::QuotaShareResourceSharingStrategy>,
    pub(crate) borrow_limit: ::std::option::Option<i32>,
}
impl QuotaShareResourceSharingConfigurationBuilder {
    /// <p>The resource sharing strategy for the quota share. The <code>RESERVE</code> strategy allows a quota share to reserve idle capacity for itself. <code>LEND</code> configures the share to lend its idle capacity to another share in need of capacity. The <code>LEND_AND_BORROW</code> strategy configures the share to borrow idle capacity from an underutilized share, as well as lend to another share.</p>
    /// This field is required.
    pub fn strategy(mut self, input: crate::types::QuotaShareResourceSharingStrategy) -> Self {
        self.strategy = ::std::option::Option::Some(input);
        self
    }
    /// <p>The resource sharing strategy for the quota share. The <code>RESERVE</code> strategy allows a quota share to reserve idle capacity for itself. <code>LEND</code> configures the share to lend its idle capacity to another share in need of capacity. The <code>LEND_AND_BORROW</code> strategy configures the share to borrow idle capacity from an underutilized share, as well as lend to another share.</p>
    pub fn set_strategy(mut self, input: ::std::option::Option<crate::types::QuotaShareResourceSharingStrategy>) -> Self {
        self.strategy = input;
        self
    }
    /// <p>The resource sharing strategy for the quota share. The <code>RESERVE</code> strategy allows a quota share to reserve idle capacity for itself. <code>LEND</code> configures the share to lend its idle capacity to another share in need of capacity. The <code>LEND_AND_BORROW</code> strategy configures the share to borrow idle capacity from an underutilized share, as well as lend to another share.</p>
    pub fn get_strategy(&self) -> &::std::option::Option<crate::types::QuotaShareResourceSharingStrategy> {
        &self.strategy
    }
    /// <p>The maximum percentage of additional capacity that the quota share can borrow from other shares. <code>borrowLimit</code> can only be applied to quota shares with a strategy of <code>LEND_AND_BORROW</code>. This value is expressed as a percentage of the quota share's configured <a href="https://docs.aws.amazon.com/batch/latest/APIReference/API_QuotaShareCapacityLimit.html">CapacityLimits</a>.</p>
    /// <p>The <code>borrowLimit</code> is applied uniformly across all capacity units. For example, if the <code>borrowLimit</code> is 200, the quota share can borrow up to 200% of its configured <code>maxCapacity</code> for each capacity unit. The default <code>borrowLimit</code> is -1, which indicates unlimited borrowing.</p>
    pub fn borrow_limit(mut self, input: i32) -> Self {
        self.borrow_limit = ::std::option::Option::Some(input);
        self
    }
    /// <p>The maximum percentage of additional capacity that the quota share can borrow from other shares. <code>borrowLimit</code> can only be applied to quota shares with a strategy of <code>LEND_AND_BORROW</code>. This value is expressed as a percentage of the quota share's configured <a href="https://docs.aws.amazon.com/batch/latest/APIReference/API_QuotaShareCapacityLimit.html">CapacityLimits</a>.</p>
    /// <p>The <code>borrowLimit</code> is applied uniformly across all capacity units. For example, if the <code>borrowLimit</code> is 200, the quota share can borrow up to 200% of its configured <code>maxCapacity</code> for each capacity unit. The default <code>borrowLimit</code> is -1, which indicates unlimited borrowing.</p>
    pub fn set_borrow_limit(mut self, input: ::std::option::Option<i32>) -> Self {
        self.borrow_limit = input;
        self
    }
    /// <p>The maximum percentage of additional capacity that the quota share can borrow from other shares. <code>borrowLimit</code> can only be applied to quota shares with a strategy of <code>LEND_AND_BORROW</code>. This value is expressed as a percentage of the quota share's configured <a href="https://docs.aws.amazon.com/batch/latest/APIReference/API_QuotaShareCapacityLimit.html">CapacityLimits</a>.</p>
    /// <p>The <code>borrowLimit</code> is applied uniformly across all capacity units. For example, if the <code>borrowLimit</code> is 200, the quota share can borrow up to 200% of its configured <code>maxCapacity</code> for each capacity unit. The default <code>borrowLimit</code> is -1, which indicates unlimited borrowing.</p>
    pub fn get_borrow_limit(&self) -> &::std::option::Option<i32> {
        &self.borrow_limit
    }
    /// Consumes the builder and constructs a [`QuotaShareResourceSharingConfiguration`](crate::types::QuotaShareResourceSharingConfiguration).
    pub fn build(self) -> crate::types::QuotaShareResourceSharingConfiguration {
        crate::types::QuotaShareResourceSharingConfiguration {
            strategy: self.strategy,
            borrow_limit: self.borrow_limit,
        }
    }
}
