// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_ssh_public_key")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteSshPublicKeyOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_ssh_public_key")]
impl ::aws_types::request_id::RequestId for DeleteSshPublicKeyOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_delete_ssh_public_key")]
impl DeleteSshPublicKeyOutput {
    /// Creates a new builder-style object to manufacture [`DeleteSshPublicKeyOutput`](crate::operation::delete_ssh_public_key::DeleteSshPublicKeyOutput).
    pub fn builder(
    ) -> crate::operation::delete_ssh_public_key::builders::DeleteSshPublicKeyOutputBuilder {
        crate::operation::delete_ssh_public_key::builders::DeleteSshPublicKeyOutputBuilder::default(
        )
    }
}

#[cfg(feature = "op_delete_ssh_public_key")]
/// A builder for [`DeleteSshPublicKeyOutput`](crate::operation::delete_ssh_public_key::DeleteSshPublicKeyOutput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct DeleteSshPublicKeyOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_ssh_public_key")]
impl DeleteSshPublicKeyOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DeleteSshPublicKeyOutput`](crate::operation::delete_ssh_public_key::DeleteSshPublicKeyOutput).
    pub fn build(self) -> crate::operation::delete_ssh_public_key::DeleteSshPublicKeyOutput {
        crate::operation::delete_ssh_public_key::DeleteSshPublicKeyOutput {
            _request_id: self._request_id,
        }
    }
}
