// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_get_ui_customization")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct GetUiCustomizationInput {
    /// <p>The ID of the user pool that you want to query for branding settings.</p>
    pub user_pool_id: ::std::option::Option<::std::string::String>,
    /// <p>The ID of the app client that you want to query for branding settings.</p>
    pub client_id: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_get_ui_customization")]
impl GetUiCustomizationInput {
    /// <p>The ID of the user pool that you want to query for branding settings.</p>
    pub fn user_pool_id(&self) -> ::std::option::Option<&str> {
        self.user_pool_id.as_deref()
    }
    /// <p>The ID of the app client that you want to query for branding settings.</p>
    pub fn client_id(&self) -> ::std::option::Option<&str> {
        self.client_id.as_deref()
    }
}
#[cfg(feature = "op_get_ui_customization")]
impl ::std::fmt::Debug for GetUiCustomizationInput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("GetUiCustomizationInput");
        formatter.field("user_pool_id", &self.user_pool_id);
        formatter.field("client_id", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
#[cfg(feature = "op_get_ui_customization")]
impl GetUiCustomizationInput {
    /// Creates a new builder-style object to manufacture [`GetUiCustomizationInput`](crate::operation::get_ui_customization::GetUiCustomizationInput).
    pub fn builder(
    ) -> crate::operation::get_ui_customization::builders::GetUiCustomizationInputBuilder {
        crate::operation::get_ui_customization::builders::GetUiCustomizationInputBuilder::default()
    }
}

#[cfg(feature = "op_get_ui_customization")]
/// A builder for [`GetUiCustomizationInput`](crate::operation::get_ui_customization::GetUiCustomizationInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct GetUiCustomizationInputBuilder {
    pub(crate) user_pool_id: ::std::option::Option<::std::string::String>,
    pub(crate) client_id: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_get_ui_customization")]
impl GetUiCustomizationInputBuilder {
    /// <p>The ID of the user pool that you want to query for branding settings.</p>
    /// This field is required.
    pub fn user_pool_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.user_pool_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the user pool that you want to query for branding settings.</p>
    pub fn set_user_pool_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.user_pool_id = input;
        self
    }
    /// <p>The ID of the user pool that you want to query for branding settings.</p>
    pub fn get_user_pool_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.user_pool_id
    }
    /// <p>The ID of the app client that you want to query for branding settings.</p>
    pub fn client_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.client_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the app client that you want to query for branding settings.</p>
    pub fn set_client_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.client_id = input;
        self
    }
    /// <p>The ID of the app client that you want to query for branding settings.</p>
    pub fn get_client_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.client_id
    }
    /// Consumes the builder and constructs a [`GetUiCustomizationInput`](crate::operation::get_ui_customization::GetUiCustomizationInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_ui_customization::GetUiCustomizationInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::get_ui_customization::GetUiCustomizationInput {
                user_pool_id: self.user_pool_id,
                client_id: self.client_id,
            },
        )
    }
}
#[cfg(feature = "op_get_ui_customization")]
impl ::std::fmt::Debug for GetUiCustomizationInputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("GetUiCustomizationInputBuilder");
        formatter.field("user_pool_id", &self.user_pool_id);
        formatter.field("client_id", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
