// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(
    feature = "op_create_key",
    feature = "op_describe_key",
    feature = "op_replicate_key"
))]
pub(crate) fn key_metadata_correct_errors(
    mut builder: crate::types::builders::KeyMetadataBuilder,
) -> crate::types::builders::KeyMetadataBuilder {
    if builder.key_id.is_none() {
        builder.key_id = Some(Default::default())
    }
    builder
}

#[cfg(any(
    feature = "op_create_key",
    feature = "op_list_resource_tags",
    feature = "op_replicate_key",
    feature = "op_tag_resource"
))]
pub(crate) fn tag_correct_errors(
    mut builder: crate::types::builders::TagBuilder,
) -> crate::types::builders::TagBuilder {
    if builder.tag_key.is_none() {
        builder.tag_key = Some(Default::default())
    }
    if builder.tag_value.is_none() {
        builder.tag_value = Some(Default::default())
    }
    builder
}
