// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(any(feature = "op_assume_role", feature = "op_assume_role_with_saml", feature = "op_assume_role_with_web_identity", feature = "op_assume_root", feature = "op_get_delegated_access_token", feature = "op_get_federation_token", feature = "op_get_session_token"))]
pub use crate::types::_credentials::CredentialsBuilder;

#[cfg(any(feature = "op_assume_role", feature = "op_assume_role_with_saml", feature = "op_assume_role_with_web_identity"))]
pub use crate::types::_assumed_role_user::AssumedRoleUserBuilder;

#[cfg(any(feature = "op_assume_role", feature = "op_assume_role_with_saml", feature = "op_assume_role_with_web_identity", feature = "op_assume_root", feature = "op_get_federation_token"))]
pub use crate::types::_policy_descriptor_type::PolicyDescriptorTypeBuilder;

#[cfg(feature = "op_get_federation_token")]
pub use crate::types::_federated_user::FederatedUserBuilder;

#[cfg(any(feature = "op_assume_role", feature = "op_get_federation_token", feature = "op_get_web_identity_token"))]
pub use crate::types::_tag::TagBuilder;

#[cfg(feature = "op_assume_role")]
pub use crate::types::_provided_context::ProvidedContextBuilder;
