// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_get_async_invoke")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetAsyncInvokeInput {
    /// <p>The invocation's ARN.</p>
    pub invocation_arn: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_get_async_invoke")]
impl GetAsyncInvokeInput {
    /// <p>The invocation's ARN.</p>
    pub fn invocation_arn(&self) -> ::std::option::Option<&str> {
        self.invocation_arn.as_deref()
    }
}
#[cfg(feature = "op_get_async_invoke")]
impl GetAsyncInvokeInput {
    /// Creates a new builder-style object to manufacture [`GetAsyncInvokeInput`](crate::operation::get_async_invoke::GetAsyncInvokeInput).
    pub fn builder() -> crate::operation::get_async_invoke::builders::GetAsyncInvokeInputBuilder {
        crate::operation::get_async_invoke::builders::GetAsyncInvokeInputBuilder::default()
    }
}

#[cfg(feature = "op_get_async_invoke")]
/// A builder for [`GetAsyncInvokeInput`](crate::operation::get_async_invoke::GetAsyncInvokeInput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct GetAsyncInvokeInputBuilder {
    pub(crate) invocation_arn: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_get_async_invoke")]
impl GetAsyncInvokeInputBuilder {
    /// <p>The invocation's ARN.</p>
    /// This field is required.
    pub fn invocation_arn(
        mut self,
        input: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        self.invocation_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The invocation's ARN.</p>
    pub fn set_invocation_arn(
        mut self,
        input: ::std::option::Option<::std::string::String>,
    ) -> Self {
        self.invocation_arn = input;
        self
    }
    /// <p>The invocation's ARN.</p>
    pub fn get_invocation_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.invocation_arn
    }
    /// Consumes the builder and constructs a [`GetAsyncInvokeInput`](crate::operation::get_async_invoke::GetAsyncInvokeInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_async_invoke::GetAsyncInvokeInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::get_async_invoke::GetAsyncInvokeInput {
            invocation_arn: self.invocation_arn,
        })
    }
}
