// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_get_role_credentials")]
pub use crate::types::_role_credentials::RoleCredentials;

#[cfg(feature = "op_list_account_roles")]
pub use crate::types::_role_info::RoleInfo;

#[cfg(feature = "op_list_accounts")]
pub use crate::types::_account_info::AccountInfo;

#[cfg(feature = "op_list_accounts")]
mod _account_info;

#[cfg(feature = "op_get_role_credentials")]
mod _role_credentials;

#[cfg(feature = "op_list_account_roles")]
mod _role_info;

/// Builders
pub mod builders;

/// Error types that AWS Single Sign-On can respond with.
pub mod error;
