// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UpdateQuotaShareOutput {
    /// <p>The name of the quota share.</p>
    pub quota_share_name: ::std::option::Option<::std::string::String>,
    /// <p>The Amazon Resource Name (ARN) of the quota share.</p>
    pub quota_share_arn: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl UpdateQuotaShareOutput {
    /// <p>The name of the quota share.</p>
    pub fn quota_share_name(&self) -> ::std::option::Option<&str> {
        self.quota_share_name.as_deref()
    }
    /// <p>The Amazon Resource Name (ARN) of the quota share.</p>
    pub fn quota_share_arn(&self) -> ::std::option::Option<&str> {
        self.quota_share_arn.as_deref()
    }
}
impl ::aws_types::request_id::RequestId for UpdateQuotaShareOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl UpdateQuotaShareOutput {
    /// Creates a new builder-style object to manufacture [`UpdateQuotaShareOutput`](crate::operation::update_quota_share::UpdateQuotaShareOutput).
    pub fn builder() -> crate::operation::update_quota_share::builders::UpdateQuotaShareOutputBuilder {
        crate::operation::update_quota_share::builders::UpdateQuotaShareOutputBuilder::default()
    }
}

/// A builder for [`UpdateQuotaShareOutput`](crate::operation::update_quota_share::UpdateQuotaShareOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UpdateQuotaShareOutputBuilder {
    pub(crate) quota_share_name: ::std::option::Option<::std::string::String>,
    pub(crate) quota_share_arn: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl UpdateQuotaShareOutputBuilder {
    /// <p>The name of the quota share.</p>
    pub fn quota_share_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.quota_share_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the quota share.</p>
    pub fn set_quota_share_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.quota_share_name = input;
        self
    }
    /// <p>The name of the quota share.</p>
    pub fn get_quota_share_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.quota_share_name
    }
    /// <p>The Amazon Resource Name (ARN) of the quota share.</p>
    pub fn quota_share_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.quota_share_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the quota share.</p>
    pub fn set_quota_share_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.quota_share_arn = input;
        self
    }
    /// <p>The Amazon Resource Name (ARN) of the quota share.</p>
    pub fn get_quota_share_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.quota_share_arn
    }
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`UpdateQuotaShareOutput`](crate::operation::update_quota_share::UpdateQuotaShareOutput).
    pub fn build(self) -> crate::operation::update_quota_share::UpdateQuotaShareOutput {
        crate::operation::update_quota_share::UpdateQuotaShareOutput {
            quota_share_name: self.quota_share_name,
            quota_share_arn: self.quota_share_arn,
            _request_id: self._request_id,
        }
    }
}
