// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Input structure for IntrospectOAuth2TokenWithIAM operation RFC 7662 §2.1 introspection request. Contains the token to inspect and an optional hint about the token's type.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct IntrospectOAuth2TokenWithIamInput {
    /// The string value of the token to introspect. May be either an access_token or a refresh_token issued by AWS Sign-In.
    pub token: ::std::option::Option<::std::string::String>,
    /// Optional hint about the type of the token submitted for introspection. The server uses this hint to optimize lookup, but still falls back to the other token type on miss. Allowed values: access_token, refresh_token.
    pub token_type_hint: ::std::option::Option<::std::string::String>,
}
impl IntrospectOAuth2TokenWithIamInput {
    /// The string value of the token to introspect. May be either an access_token or a refresh_token issued by AWS Sign-In.
    pub fn token(&self) -> ::std::option::Option<&str> {
        self.token.as_deref()
    }
    /// Optional hint about the type of the token submitted for introspection. The server uses this hint to optimize lookup, but still falls back to the other token type on miss. Allowed values: access_token, refresh_token.
    pub fn token_type_hint(&self) -> ::std::option::Option<&str> {
        self.token_type_hint.as_deref()
    }
}
impl ::std::fmt::Debug for IntrospectOAuth2TokenWithIamInput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("IntrospectOAuth2TokenWithIamInput");
        formatter.field("token", &"*** Sensitive Data Redacted ***");
        formatter.field("token_type_hint", &self.token_type_hint);
        formatter.finish()
    }
}
impl IntrospectOAuth2TokenWithIamInput {
    /// Creates a new builder-style object to manufacture [`IntrospectOAuth2TokenWithIamInput`](crate::operation::introspect_o_auth2_token_with_iam::IntrospectOAuth2TokenWithIamInput).
    pub fn builder() -> crate::operation::introspect_o_auth2_token_with_iam::builders::IntrospectOAuth2TokenWithIamInputBuilder {
        crate::operation::introspect_o_auth2_token_with_iam::builders::IntrospectOAuth2TokenWithIamInputBuilder::default()
    }
}

/// A builder for [`IntrospectOAuth2TokenWithIamInput`](crate::operation::introspect_o_auth2_token_with_iam::IntrospectOAuth2TokenWithIamInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct IntrospectOAuth2TokenWithIamInputBuilder {
    pub(crate) token: ::std::option::Option<::std::string::String>,
    pub(crate) token_type_hint: ::std::option::Option<::std::string::String>,
}
impl IntrospectOAuth2TokenWithIamInputBuilder {
    /// The string value of the token to introspect. May be either an access_token or a refresh_token issued by AWS Sign-In.
    /// This field is required.
    pub fn token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.token = ::std::option::Option::Some(input.into());
        self
    }
    /// The string value of the token to introspect. May be either an access_token or a refresh_token issued by AWS Sign-In.
    pub fn set_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.token = input;
        self
    }
    /// The string value of the token to introspect. May be either an access_token or a refresh_token issued by AWS Sign-In.
    pub fn get_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.token
    }
    /// Optional hint about the type of the token submitted for introspection. The server uses this hint to optimize lookup, but still falls back to the other token type on miss. Allowed values: access_token, refresh_token.
    pub fn token_type_hint(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.token_type_hint = ::std::option::Option::Some(input.into());
        self
    }
    /// Optional hint about the type of the token submitted for introspection. The server uses this hint to optimize lookup, but still falls back to the other token type on miss. Allowed values: access_token, refresh_token.
    pub fn set_token_type_hint(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.token_type_hint = input;
        self
    }
    /// Optional hint about the type of the token submitted for introspection. The server uses this hint to optimize lookup, but still falls back to the other token type on miss. Allowed values: access_token, refresh_token.
    pub fn get_token_type_hint(&self) -> &::std::option::Option<::std::string::String> {
        &self.token_type_hint
    }
    /// Consumes the builder and constructs a [`IntrospectOAuth2TokenWithIamInput`](crate::operation::introspect_o_auth2_token_with_iam::IntrospectOAuth2TokenWithIamInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::introspect_o_auth2_token_with_iam::IntrospectOAuth2TokenWithIamInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::introspect_o_auth2_token_with_iam::IntrospectOAuth2TokenWithIamInput {
            token: self.token,
            token_type_hint: self.token_type_hint,
        })
    }
}
impl ::std::fmt::Debug for IntrospectOAuth2TokenWithIamInputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("IntrospectOAuth2TokenWithIamInputBuilder");
        formatter.field("token", &"*** Sensitive Data Redacted ***");
        formatter.field("token_type_hint", &self.token_type_hint);
        formatter.finish()
    }
}
