// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_add_role_to_instance_profile")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct AddRoleToInstanceProfileOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_add_role_to_instance_profile")]
impl ::aws_types::request_id::RequestId for AddRoleToInstanceProfileOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_add_role_to_instance_profile")]
impl AddRoleToInstanceProfileOutput {
    /// Creates a new builder-style object to manufacture [`AddRoleToInstanceProfileOutput`](crate::operation::add_role_to_instance_profile::AddRoleToInstanceProfileOutput).
    pub fn builder() -> crate::operation::add_role_to_instance_profile::builders::AddRoleToInstanceProfileOutputBuilder{
        crate::operation::add_role_to_instance_profile::builders::AddRoleToInstanceProfileOutputBuilder::default()
    }
}

#[cfg(feature = "op_add_role_to_instance_profile")]
/// A builder for [`AddRoleToInstanceProfileOutput`](crate::operation::add_role_to_instance_profile::AddRoleToInstanceProfileOutput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct AddRoleToInstanceProfileOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_add_role_to_instance_profile")]
impl AddRoleToInstanceProfileOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`AddRoleToInstanceProfileOutput`](crate::operation::add_role_to_instance_profile::AddRoleToInstanceProfileOutput).
    pub fn build(
        self,
    ) -> crate::operation::add_role_to_instance_profile::AddRoleToInstanceProfileOutput {
        crate::operation::add_role_to_instance_profile::AddRoleToInstanceProfileOutput {
            _request_id: self._request_id,
        }
    }
}
