// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_get_delivery_destination")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetDeliveryDestinationInput {
    /// <p>The name of the delivery destination that you want to retrieve.</p>
    pub name: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_get_delivery_destination")]
impl GetDeliveryDestinationInput {
    /// <p>The name of the delivery destination that you want to retrieve.</p>
    pub fn name(&self) -> ::std::option::Option<&str> {
        self.name.as_deref()
    }
}
#[cfg(feature = "op_get_delivery_destination")]
impl GetDeliveryDestinationInput {
    /// Creates a new builder-style object to manufacture [`GetDeliveryDestinationInput`](crate::operation::get_delivery_destination::GetDeliveryDestinationInput).
    pub fn builder(
    ) -> crate::operation::get_delivery_destination::builders::GetDeliveryDestinationInputBuilder
    {
        crate::operation::get_delivery_destination::builders::GetDeliveryDestinationInputBuilder::default()
    }
}

#[cfg(feature = "op_get_delivery_destination")]
/// A builder for [`GetDeliveryDestinationInput`](crate::operation::get_delivery_destination::GetDeliveryDestinationInput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct GetDeliveryDestinationInputBuilder {
    pub(crate) name: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_get_delivery_destination")]
impl GetDeliveryDestinationInputBuilder {
    /// <p>The name of the delivery destination that you want to retrieve.</p>
    /// This field is required.
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the delivery destination that you want to retrieve.</p>
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input;
        self
    }
    /// <p>The name of the delivery destination that you want to retrieve.</p>
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    /// Consumes the builder and constructs a [`GetDeliveryDestinationInput`](crate::operation::get_delivery_destination::GetDeliveryDestinationInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_delivery_destination::GetDeliveryDestinationInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::get_delivery_destination::GetDeliveryDestinationInput {
                name: self.name,
            },
        )
    }
}
