// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_stored_query")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteStoredQueryOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_stored_query")]
impl ::aws_types::request_id::RequestId for DeleteStoredQueryOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_delete_stored_query")]
impl DeleteStoredQueryOutput {
    /// Creates a new builder-style object to manufacture [`DeleteStoredQueryOutput`](crate::operation::delete_stored_query::DeleteStoredQueryOutput).
    pub fn builder(
    ) -> crate::operation::delete_stored_query::builders::DeleteStoredQueryOutputBuilder {
        crate::operation::delete_stored_query::builders::DeleteStoredQueryOutputBuilder::default()
    }
}

#[cfg(feature = "op_delete_stored_query")]
/// A builder for [`DeleteStoredQueryOutput`](crate::operation::delete_stored_query::DeleteStoredQueryOutput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct DeleteStoredQueryOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_stored_query")]
impl DeleteStoredQueryOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DeleteStoredQueryOutput`](crate::operation::delete_stored_query::DeleteStoredQueryOutput).
    pub fn build(self) -> crate::operation::delete_stored_query::DeleteStoredQueryOutput {
        crate::operation::delete_stored_query::DeleteStoredQueryOutput {
            _request_id: self._request_id,
        }
    }
}
