use std::path::{Path, PathBuf};

use serde_json::{json, Value};

#[derive(Debug, Clone)]
pub struct BuildConfig {
    model_file: PathBuf,
    service: String,
    output_directory: PathBuf,
    codegen_coordinate: String,
}

impl BuildConfig {
    pub fn new(
        model_file: impl AsRef<Path>,
        service: impl Into<String>,
        output_directory: impl AsRef<Path>,
        codegen_coordinate: impl Into<String>,
    ) -> Self {
        Self {
            model_file: model_file.as_ref().to_path_buf(),
            service: service.into(),
            output_directory: output_directory.as_ref().to_path_buf(),
            codegen_coordinate: codegen_coordinate.into(),
        }
    }

    pub fn to_json(&self) -> Value {
        json!({
            "version": "1.0",
            "outputDirectory": self.output_directory,
            "imports": [self.model_file],
            "maven": {
                "dependencies": [self.codegen_coordinate]
            },
            "projections": {
                "aws-sdk": {
                    "plugins": {
                        "rust-client-codegen": {
                            "service": self.service,
                            "module": module_name(&self.service),
                            "moduleVersion": "0.1.0",
                            "moduleAuthors": ["aws-sdk-build"],
                            "moduleDescription": "A modular AWS SDK client generated by aws-sdk-build.",
                            "license": "Apache-2.0",
                            "codegen": {
                                "includeFluentClient": true
                            },
                            "customizationConfig": {
                                "awsSdk": {
                                    "awsSdkBuild": false,
                                    "suppressReadme": true
                                }
                            }
                        }
                    }
                }
            }
        })
    }
}

fn module_name(service_id: &str) -> String {
    let name = service_id.rsplit('#').next().unwrap_or(service_id);
    format!("{}_sdk", snake_case(name))
}

fn snake_case(value: &str) -> String {
    let characters = value.chars().collect::<Vec<_>>();
    let mut output = String::new();
    for (index, character) in characters.iter().enumerate() {
        if character.is_ascii_alphanumeric() {
            let next_is_lowercase = characters
                .get(index + 1)
                .is_some_and(|next| next.is_ascii_lowercase());
            if character.is_ascii_uppercase()
                && !output.is_empty()
                && !output.ends_with('_')
                && (characters
                    .get(index.wrapping_sub(1))
                    .is_some_and(|previous| previous.is_ascii_lowercase())
                    || characters
                        .get(index.wrapping_sub(1))
                        .is_some_and(|previous| previous.is_ascii_digit())
                    || (characters
                        .get(index.wrapping_sub(1))
                        .is_some_and(|previous| previous.is_ascii_uppercase())
                        && next_is_lowercase))
            {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
        } else if !output.is_empty() && !output.ends_with('_') {
            output.push('_');
        }
    }
    output.trim_matches('_').to_owned()
}
