[package]
name = "multi_service"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
aws-sdk-builder = { path = "../../crates/aws-sdk-builder" }
aws-runtime = "1.9.1"
aws-types = "1.5.0"
aws-smithy-runtime-api = "1.15.0"
aws-smithy-types = "1.6.2"
http-1x = { package = "http", version = "1.5.0" }

[build-dependencies]
aws-sdk-builder-s3 = { path = "../../crates/aws-sdk-builder-s3" }
aws-sdk-builder-sqs = { path = "../../crates/aws-sdk-builder-sqs" }
