// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

#[cfg(feature = "op_get_configuration_set_event_destinations")]
/// <p>A request to obtain information about the event destinations for a configuration set.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetConfigurationSetEventDestinationsInput {
    /// <p>The name of the configuration set that contains the event destination.</p>
    pub configuration_set_name: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_get_configuration_set_event_destinations")]
impl GetConfigurationSetEventDestinationsInput {
    /// <p>The name of the configuration set that contains the event destination.</p>
    pub fn configuration_set_name(&self) -> ::std::option::Option<&str> {
        self.configuration_set_name.as_deref()
    }
}
#[cfg(feature = "op_get_configuration_set_event_destinations")]
impl GetConfigurationSetEventDestinationsInput {
    /// Creates a new builder-style object to manufacture [`GetConfigurationSetEventDestinationsInput`](crate::operation::get_configuration_set_event_destinations::GetConfigurationSetEventDestinationsInput).
    pub fn builder() -> crate::operation::get_configuration_set_event_destinations::builders::GetConfigurationSetEventDestinationsInputBuilder{
        crate::operation::get_configuration_set_event_destinations::builders::GetConfigurationSetEventDestinationsInputBuilder::default()
    }
}

#[cfg(feature = "op_get_configuration_set_event_destinations")]
/// A builder for [`GetConfigurationSetEventDestinationsInput`](crate::operation::get_configuration_set_event_destinations::GetConfigurationSetEventDestinationsInput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct GetConfigurationSetEventDestinationsInputBuilder {
    pub(crate) configuration_set_name: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_get_configuration_set_event_destinations")]
impl GetConfigurationSetEventDestinationsInputBuilder {
    /// <p>The name of the configuration set that contains the event destination.</p>
    /// This field is required.
    pub fn configuration_set_name(
        mut self,
        input: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        self.configuration_set_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the configuration set that contains the event destination.</p>
    pub fn set_configuration_set_name(
        mut self,
        input: ::std::option::Option<::std::string::String>,
    ) -> Self {
        self.configuration_set_name = input;
        self
    }
    /// <p>The name of the configuration set that contains the event destination.</p>
    pub fn get_configuration_set_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.configuration_set_name
    }
    /// Consumes the builder and constructs a [`GetConfigurationSetEventDestinationsInput`](crate::operation::get_configuration_set_event_destinations::GetConfigurationSetEventDestinationsInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::get_configuration_set_event_destinations::GetConfigurationSetEventDestinationsInput,
        ::aws_smithy_types::error::operation::BuildError,
    >{
        ::std::result::Result::Ok(
            crate::operation::get_configuration_set_event_destinations::GetConfigurationSetEventDestinationsInput {
                configuration_set_name: self.configuration_set_name,
            },
        )
    }
}
