// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_update_contact")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UpdateContactOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_update_contact")]
impl ::aws_types::request_id::RequestId for UpdateContactOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_update_contact")]
impl UpdateContactOutput {
    /// Creates a new builder-style object to manufacture [`UpdateContactOutput`](crate::operation::update_contact::UpdateContactOutput).
    pub fn builder() -> crate::operation::update_contact::builders::UpdateContactOutputBuilder {
        crate::operation::update_contact::builders::UpdateContactOutputBuilder::default()
    }
}

#[cfg(feature = "op_update_contact")]
/// A builder for [`UpdateContactOutput`](crate::operation::update_contact::UpdateContactOutput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct UpdateContactOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_update_contact")]
impl UpdateContactOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`UpdateContactOutput`](crate::operation::update_contact::UpdateContactOutput).
    pub fn build(self) -> crate::operation::update_contact::UpdateContactOutput {
        crate::operation::update_contact::UpdateContactOutput {
            _request_id: self._request_id,
        }
    }
}
