// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_set_endpoint_attributes")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct SetEndpointAttributesOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_set_endpoint_attributes")]
impl ::aws_types::request_id::RequestId for SetEndpointAttributesOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_set_endpoint_attributes")]
impl SetEndpointAttributesOutput {
    /// Creates a new builder-style object to manufacture [`SetEndpointAttributesOutput`](crate::operation::set_endpoint_attributes::SetEndpointAttributesOutput).
    pub fn builder() -> crate::operation::set_endpoint_attributes::builders::SetEndpointAttributesOutputBuilder {
        crate::operation::set_endpoint_attributes::builders::SetEndpointAttributesOutputBuilder::default()
    }
}

#[cfg(feature = "op_set_endpoint_attributes")]
/// A builder for [`SetEndpointAttributesOutput`](crate::operation::set_endpoint_attributes::SetEndpointAttributesOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct SetEndpointAttributesOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_set_endpoint_attributes")]
impl SetEndpointAttributesOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`SetEndpointAttributesOutput`](crate::operation::set_endpoint_attributes::SetEndpointAttributesOutput).
    pub fn build(self) -> crate::operation::set_endpoint_attributes::SetEndpointAttributesOutput {
        crate::operation::set_endpoint_attributes::SetEndpointAttributesOutput {
            _request_id: self._request_id,
        }
    }
}
