// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_put_bearer_token_authentication")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PutBearerTokenAuthenticationOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_put_bearer_token_authentication")]
impl ::aws_types::request_id::RequestId for PutBearerTokenAuthenticationOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_put_bearer_token_authentication")]
impl PutBearerTokenAuthenticationOutput {
    /// Creates a new builder-style object to manufacture [`PutBearerTokenAuthenticationOutput`](crate::operation::put_bearer_token_authentication::PutBearerTokenAuthenticationOutput).
    pub fn builder() -> crate::operation::put_bearer_token_authentication::builders::PutBearerTokenAuthenticationOutputBuilder {
        crate::operation::put_bearer_token_authentication::builders::PutBearerTokenAuthenticationOutputBuilder::default()
    }
}

#[cfg(feature = "op_put_bearer_token_authentication")]
/// A builder for [`PutBearerTokenAuthenticationOutput`](crate::operation::put_bearer_token_authentication::PutBearerTokenAuthenticationOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct PutBearerTokenAuthenticationOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_put_bearer_token_authentication")]
impl PutBearerTokenAuthenticationOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`PutBearerTokenAuthenticationOutput`](crate::operation::put_bearer_token_authentication::PutBearerTokenAuthenticationOutput).
    pub fn build(self) -> crate::operation::put_bearer_token_authentication::PutBearerTokenAuthenticationOutput {
        crate::operation::put_bearer_token_authentication::PutBearerTokenAuthenticationOutput {
            _request_id: self._request_id,
        }
    }
}
