// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_abort_multipart_upload")]
pub use crate::types::error::_no_such_upload::NoSuchUpload;

#[cfg(feature = "op_copy_object")]
pub use crate::types::error::_object_not_in_active_tier_error::ObjectNotInActiveTierError;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::error::_bucket_already_exists::BucketAlreadyExists;

#[cfg(feature = "op_create_bucket")]
pub use crate::types::error::_bucket_already_owned_by_you::BucketAlreadyOwnedByYou;

#[cfg(any(
    feature = "op_create_session",
    feature = "op_delete_object_annotation",
    feature = "op_get_object_annotation",
    feature = "op_list_object_annotations",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_put_object_annotation"
))]
pub use crate::types::error::_no_such_bucket::NoSuchBucket;

#[cfg(any(
    feature = "op_delete_object_annotation",
    feature = "op_get_object",
    feature = "op_get_object_acl",
    feature = "op_get_object_annotation",
    feature = "op_get_object_attributes",
    feature = "op_list_object_annotations",
    feature = "op_put_object_acl",
    feature = "op_put_object_annotation",
    feature = "op_update_object_encryption"
))]
pub use crate::types::error::_no_such_key::NoSuchKey;

#[cfg(feature = "op_get_object")]
pub use crate::types::error::_invalid_object_state::InvalidObjectState;

#[cfg(feature = "op_get_object_annotation")]
pub use crate::types::error::_no_such_annotation::NoSuchAnnotation;

#[cfg(any(feature = "op_head_bucket", feature = "op_head_object"))]
pub use crate::types::error::_not_found::NotFound;

#[cfg(feature = "op_list_object_annotations")]
pub use crate::types::error::_invalid_prefix::InvalidPrefix;

#[cfg(feature = "op_put_object")]
pub use crate::types::error::_encryption_type_mismatch::EncryptionTypeMismatch;

#[cfg(any(
    feature = "op_put_object",
    feature = "op_put_object_annotation",
    feature = "op_update_object_encryption"
))]
pub use crate::types::error::_invalid_request::InvalidRequest;

#[cfg(feature = "op_put_object")]
pub use crate::types::error::_invalid_write_offset::InvalidWriteOffset;

#[cfg(feature = "op_put_object")]
pub use crate::types::error::_too_many_parts::TooManyParts;

#[cfg(feature = "op_put_object_annotation")]
pub use crate::types::error::_annotation_limit_exceeded::AnnotationLimitExceeded;

#[cfg(feature = "op_put_object_annotation")]
pub use crate::types::error::_annotation_name_too_long::AnnotationNameTooLong;

#[cfg(feature = "op_put_object_annotation")]
pub use crate::types::error::_invalid_annotation_name::InvalidAnnotationName;

#[cfg(feature = "op_put_object_annotation")]
pub use crate::types::error::_unsupported_media_type::UnsupportedMediaType;

#[cfg(feature = "op_rename_object")]
pub use crate::types::error::_idempotency_parameter_mismatch::IdempotencyParameterMismatch;

#[cfg(feature = "op_restore_object")]
pub use crate::types::error::_object_already_in_active_tier_error::ObjectAlreadyInActiveTierError;

#[cfg(feature = "op_update_object_encryption")]
pub use crate::types::error::_access_denied::AccessDenied;

#[cfg(feature = "op_select_object_content")]
/// Error type for the `SelectObjectContentEventStreamError` operation.
#[non_exhaustive]
#[derive(::std::fmt::Debug)]
pub enum SelectObjectContentEventStreamError {
    /// An unexpected error occurred (e.g., invalid JSON returned by the service or an unknown error code).
    #[deprecated(
        note = "Matching `Unhandled` directly is not forwards compatible. Instead, match using a \
    variable wildcard pattern and check `.code()`:
     \
    &nbsp;&nbsp;&nbsp;`err if err.code() == Some(\"SpecificExceptionCode\") => { /* handle the error */ }`
     \
    See [`ProvideErrorMetadata`](#impl-ProvideErrorMetadata-for-SelectObjectContentEventStreamError) for what information is available for the error."
    )]
    Unhandled(crate::error::sealed_unhandled::Unhandled),
}
#[cfg(feature = "op_select_object_content")]
impl SelectObjectContentEventStreamError {
    /// Creates the `SelectObjectContentEventStreamError::Unhandled` variant from any error type.
    pub fn unhandled(
        err: impl ::std::convert::Into<
            ::std::boxed::Box<dyn ::std::error::Error + ::std::marker::Send + ::std::marker::Sync + 'static>,
        >,
    ) -> Self {
        Self::Unhandled(crate::error::sealed_unhandled::Unhandled {
            source: err.into(),
            meta: ::std::default::Default::default(),
        })
    }

    /// Creates the `SelectObjectContentEventStreamError::Unhandled` variant from an [`ErrorMetadata`](::aws_smithy_types::error::ErrorMetadata).
    pub fn generic(err: ::aws_smithy_types::error::ErrorMetadata) -> Self {
        Self::Unhandled(crate::error::sealed_unhandled::Unhandled {
            source: err.clone().into(),
            meta: err,
        })
    }
    ///
    /// Returns error metadata, which includes the error code, message,
    /// request ID, and potentially additional information.
    ///
    pub fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata {
        match self {
            Self::Unhandled(e) => &e.meta,
        }
    }
}
#[cfg(feature = "op_select_object_content")]
impl ::std::error::Error for SelectObjectContentEventStreamError {
    fn source(&self) -> ::std::option::Option<&(dyn ::std::error::Error + 'static)> {
        match self {
            Self::Unhandled(_inner) => ::std::option::Option::Some(&*_inner.source),
        }
    }
}
#[cfg(feature = "op_select_object_content")]
impl ::std::fmt::Display for SelectObjectContentEventStreamError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::Unhandled(_inner) => {
                if let ::std::option::Option::Some(code) =
                    ::aws_smithy_types::error::metadata::ProvideErrorMetadata::code(self)
                {
                    write!(f, "unhandled error ({code})")
                } else {
                    f.write_str("unhandled error")
                }
            }
        }
    }
}
#[cfg(feature = "op_select_object_content")]
impl ::aws_smithy_types::retry::ProvideErrorKind for SelectObjectContentEventStreamError {
    fn code(&self) -> ::std::option::Option<&str> {
        ::aws_smithy_types::error::metadata::ProvideErrorMetadata::code(self)
    }
    fn retryable_error_kind(&self) -> ::std::option::Option<::aws_smithy_types::retry::ErrorKind> {
        ::std::option::Option::None
    }
}
#[cfg(feature = "op_select_object_content")]
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for SelectObjectContentEventStreamError {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata {
        match self {
            Self::Unhandled(_inner) => &_inner.meta,
        }
    }
}
#[cfg(feature = "op_select_object_content")]
impl ::aws_smithy_runtime_api::client::result::CreateUnhandledError for SelectObjectContentEventStreamError {
    fn create_unhandled_error(
        source: ::std::boxed::Box<dyn ::std::error::Error + ::std::marker::Send + ::std::marker::Sync + 'static>,
        meta: ::std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
    ) -> Self {
        Self::Unhandled(crate::error::sealed_unhandled::Unhandled {
            source,
            meta: meta.unwrap_or_default(),
        })
    }
}
#[cfg(feature = "op_select_object_content")]
impl crate::s3_request_id::RequestIdExt for crate::types::error::SelectObjectContentEventStreamError {
    fn extended_request_id(&self) -> Option<&str> {
        self.meta().extended_request_id()
    }
}
#[cfg(feature = "op_select_object_content")]
impl ::aws_types::request_id::RequestId for crate::types::error::SelectObjectContentEventStreamError {
    fn request_id(&self) -> Option<&str> {
        self.meta().request_id()
    }
}

#[cfg(feature = "op_update_object_encryption")]
mod _access_denied;

#[cfg(feature = "op_put_object_annotation")]
mod _annotation_limit_exceeded;

#[cfg(feature = "op_put_object_annotation")]
mod _annotation_name_too_long;

#[cfg(feature = "op_create_bucket")]
mod _bucket_already_exists;

#[cfg(feature = "op_create_bucket")]
mod _bucket_already_owned_by_you;

#[cfg(feature = "op_put_object")]
mod _encryption_type_mismatch;

#[cfg(feature = "op_rename_object")]
mod _idempotency_parameter_mismatch;

#[cfg(feature = "op_put_object_annotation")]
mod _invalid_annotation_name;

#[cfg(feature = "op_get_object")]
mod _invalid_object_state;

#[cfg(feature = "op_list_object_annotations")]
mod _invalid_prefix;

#[cfg(any(
    feature = "op_put_object",
    feature = "op_put_object_annotation",
    feature = "op_update_object_encryption"
))]
mod _invalid_request;

#[cfg(feature = "op_put_object")]
mod _invalid_write_offset;

#[cfg(feature = "op_get_object_annotation")]
mod _no_such_annotation;

#[cfg(any(
    feature = "op_create_session",
    feature = "op_delete_object_annotation",
    feature = "op_get_object_annotation",
    feature = "op_list_object_annotations",
    feature = "op_list_objects",
    feature = "op_list_objects_v2",
    feature = "op_put_object_annotation"
))]
mod _no_such_bucket;

#[cfg(any(
    feature = "op_delete_object_annotation",
    feature = "op_get_object",
    feature = "op_get_object_acl",
    feature = "op_get_object_annotation",
    feature = "op_get_object_attributes",
    feature = "op_list_object_annotations",
    feature = "op_put_object_acl",
    feature = "op_put_object_annotation",
    feature = "op_update_object_encryption"
))]
mod _no_such_key;

#[cfg(feature = "op_abort_multipart_upload")]
mod _no_such_upload;

#[cfg(any(feature = "op_head_bucket", feature = "op_head_object"))]
mod _not_found;

#[cfg(feature = "op_restore_object")]
mod _object_already_in_active_tier_error;

#[cfg(feature = "op_copy_object")]
mod _object_not_in_active_tier_error;

#[cfg(feature = "op_put_object")]
mod _too_many_parts;

#[cfg(feature = "op_put_object_annotation")]
mod _unsupported_media_type;

/// Builders
pub mod builders;
