// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_generate_credential_report")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GenerateCredentialReportInput {}
#[cfg(feature = "op_generate_credential_report")]
impl GenerateCredentialReportInput {
    /// Creates a new builder-style object to manufacture [`GenerateCredentialReportInput`](crate::operation::generate_credential_report::GenerateCredentialReportInput).
    pub fn builder(
    ) -> crate::operation::generate_credential_report::builders::GenerateCredentialReportInputBuilder
    {
        crate::operation::generate_credential_report::builders::GenerateCredentialReportInputBuilder::default()
    }
}

#[cfg(feature = "op_generate_credential_report")]
/// A builder for [`GenerateCredentialReportInput`](crate::operation::generate_credential_report::GenerateCredentialReportInput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct GenerateCredentialReportInputBuilder {}
#[cfg(feature = "op_generate_credential_report")]
impl GenerateCredentialReportInputBuilder {
    /// Consumes the builder and constructs a [`GenerateCredentialReportInput`](crate::operation::generate_credential_report::GenerateCredentialReportInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::generate_credential_report::GenerateCredentialReportInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::generate_credential_report::GenerateCredentialReportInput {},
        )
    }
}
