// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[derive(Debug)]
pub(crate) struct Handle {
    pub(crate) conf: crate::Config,
    #[allow(dead_code)] // unused when a service does not provide any operations
    pub(crate) runtime_plugins: ::aws_smithy_runtime_api::client::runtime_plugin::RuntimePlugins,
}

/// Client for AWS Identity and Access Management
///
/// Client for invoking operations on AWS Identity and Access Management. Each operation on AWS Identity and Access Management is a method on this
/// this struct. `.send()` MUST be invoked on the generated operations to dispatch the request to the service.
/// ## Constructing a `Client`
///
/// A [`Config`] is required to construct a client. For most use cases, the [`aws-config`]
/// crate should be used to automatically resolve this config using
/// [`aws_config::load_from_env()`], since this will resolve an [`SdkConfig`] which can be shared
/// across multiple different AWS SDK clients. This config resolution process can be customized
/// by calling [`aws_config::from_env()`] instead, which returns a [`ConfigLoader`] that uses
/// the [builder pattern] to customize the default config.
///
/// In the simplest case, creating a client looks as follows:
/// ```rust,no_run
/// # async fn wrapper() {
/// let config = aws_config::load_from_env().await;
/// let client = aws_sdk_iam_modular::Client::new(&config);
/// # }
/// ```
///
/// Occasionally, SDKs may have additional service-specific values that can be set on the [`Config`] that
/// is absent from [`SdkConfig`], or slightly different settings for a specific client may be desired.
/// The [`Builder`](crate::config::Builder) struct implements `From<&SdkConfig>`, so setting these specific settings can be
/// done as follows:
///
/// ```rust,no_run
/// # async fn wrapper() {
/// let sdk_config = ::aws_config::load_from_env().await;
/// let config = aws_sdk_iam_modular::config::Builder::from(&sdk_config)
/// # /*
///     .some_service_specific_setting("value")
/// # */
///     .build();
/// # }
/// ```
///
/// See the [`aws-config` docs] and [`Config`] for more information on customizing configuration.
///
/// _Note:_ Client construction is expensive due to connection thread pool initialization, and should
/// be done once at application start-up.
///
/// [`Config`]: crate::Config
/// [`ConfigLoader`]: https://docs.rs/aws-config/*/aws_config/struct.ConfigLoader.html
/// [`SdkConfig`]: https://docs.rs/aws-config/*/aws_config/struct.SdkConfig.html
/// [`aws-config` docs]: https://docs.rs/aws-config/*
/// [`aws-config`]: https://crates.io/crates/aws-config
/// [`aws_config::from_env()`]: https://docs.rs/aws-config/*/aws_config/fn.from_env.html
/// [`aws_config::load_from_env()`]: https://docs.rs/aws-config/*/aws_config/fn.load_from_env.html
/// [builder pattern]: https://rust-lang.github.io/api-guidelines/type-safety.html#builders-enable-construction-of-complex-values-c-builder
/// # Using the `Client`
///
/// A client has a function for every operation that can be performed by the service.
/// For example, the [`AcceptDelegationRequest`](crate::operation::accept_delegation_request) operation has
/// a [`Client::accept_delegation_request`], function which returns a builder for that operation.
/// The fluent builder ultimately has a `send()` function that returns an async future that
/// returns a result, as illustrated below:
///
/// ```rust,ignore
/// let result = client.accept_delegation_request()
///     .delegation_request_id("example")
///     .send()
///     .await;
/// ```
///
/// The underlying HTTP requests that get made by this can be modified with the `customize_operation`
/// function on the fluent builder. See the [`customize`](crate::client::customize) module for more
/// information.
/// # Waiters
///
/// This client provides `wait_until` methods behind the [`Waiters`](crate::client::Waiters) trait.
/// To use them, simply import the trait, and then call one of the `wait_until` methods. This will
/// return a waiter fluent builder that takes various parameters, which are documented on the builder
/// type. Once parameters have been provided, the `wait` method can be called to initiate waiting.
///
/// For example, if there was a `wait_until_thing` method, it could look like:
/// ```rust,ignore
/// let result = client.wait_until_thing()
///     .thing_id("someId")
///     .wait(Duration::from_secs(120))
///     .await;
/// ```
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct Client {
    handle: ::std::sync::Arc<Handle>,
}

impl Client {
    /// Creates a new client from the service [`Config`](crate::Config).
    ///
    /// # Panics
    ///
    /// This method will panic in the following cases:
    ///
    /// - Retries or timeouts are enabled without a `sleep_impl` configured.
    /// - Identity caching is enabled without a `sleep_impl` and `time_source` configured.
    /// - No `behavior_version` is provided.
    ///
    /// The panic message for each of these will have instructions on how to resolve them.
    #[track_caller]
    pub fn from_conf(conf: crate::Config) -> Self {
        let handle = Handle {
            conf: conf.clone(),
            runtime_plugins: crate::config::base_client_runtime_plugins(conf),
        };
        if let Err(err) = Self::validate_config(&handle) {
            panic!("Invalid client configuration: {err}");
        }
        Self {
            handle: ::std::sync::Arc::new(handle),
        }
    }

    /// Returns the client's configuration.
    pub fn config(&self) -> &crate::Config {
        &self.handle.conf
    }

    fn validate_config(handle: &Handle) -> ::std::result::Result<(), ::aws_smithy_runtime_api::box_error::BoxError> {
        let mut cfg = ::aws_smithy_types::config_bag::ConfigBag::base();
        handle
            .runtime_plugins
            .apply_client_configuration(&mut cfg)?
            .validate_base_client_config(&cfg)?;
        Ok(())
    }
}

///
/// Waiter functions for the client.
///
/// Import this trait to get `wait_until` methods on the client.
///
pub trait Waiters {
    #[cfg(feature = "op_get_instance_profile")]
/// Wait for `instance_profile_exists`
    fn wait_until_instance_profile_exists(&self) -> crate::waiters::instance_profile_exists::InstanceProfileExistsFluentBuilder;
    #[cfg(feature = "op_get_policy")]
/// Wait for `policy_exists`
    fn wait_until_policy_exists(&self) -> crate::waiters::policy_exists::PolicyExistsFluentBuilder;
    #[cfg(feature = "op_get_role")]
/// Wait for `role_exists`
    fn wait_until_role_exists(&self) -> crate::waiters::role_exists::RoleExistsFluentBuilder;
    #[cfg(feature = "op_get_user")]
/// Wait for `user_exists`
    fn wait_until_user_exists(&self) -> crate::waiters::user_exists::UserExistsFluentBuilder;
}
impl Waiters for Client {
    #[cfg(feature = "op_get_instance_profile")]
fn wait_until_instance_profile_exists(&self) -> crate::waiters::instance_profile_exists::InstanceProfileExistsFluentBuilder {
        crate::waiters::instance_profile_exists::InstanceProfileExistsFluentBuilder::new(self.handle.clone())
    }
    #[cfg(feature = "op_get_policy")]
fn wait_until_policy_exists(&self) -> crate::waiters::policy_exists::PolicyExistsFluentBuilder {
        crate::waiters::policy_exists::PolicyExistsFluentBuilder::new(self.handle.clone())
    }
    #[cfg(feature = "op_get_role")]
fn wait_until_role_exists(&self) -> crate::waiters::role_exists::RoleExistsFluentBuilder {
        crate::waiters::role_exists::RoleExistsFluentBuilder::new(self.handle.clone())
    }
    #[cfg(feature = "op_get_user")]
fn wait_until_user_exists(&self) -> crate::waiters::user_exists::UserExistsFluentBuilder {
        crate::waiters::user_exists::UserExistsFluentBuilder::new(self.handle.clone())
    }
}

impl Client {
    /// Creates a new client from an [SDK Config](::aws_types::sdk_config::SdkConfig).
    ///
    /// # Panics
    ///
    /// - This method will panic if the `sdk_config` is missing an async sleep implementation. If you experience this panic, set
    ///   the `sleep_impl` on the Config passed into this function to fix it.
    /// - This method will panic if the `sdk_config` is missing an HTTP connector. If you experience this panic, set the
    ///   `http_connector` on the Config passed into this function to fix it.
    /// - This method will panic if no `BehaviorVersion` is provided. If you experience this panic, set `behavior_version` on the Config or enable the `behavior-version-latest` Cargo feature.
    #[track_caller]
    pub fn new(sdk_config: &::aws_types::sdk_config::SdkConfig) -> Self {
        Self::from_conf(sdk_config.into())
    }
}

#[cfg(feature = "op_accept_delegation_request")]
mod accept_delegation_request;

#[cfg(feature = "op_acquire_role")]
mod acquire_role;

#[cfg(feature = "op_add_client_id_to_open_id_connect_provider")]
mod add_client_id_to_open_id_connect_provider;

#[cfg(feature = "op_add_role_to_instance_profile")]
mod add_role_to_instance_profile;

#[cfg(feature = "op_add_user_to_group")]
mod add_user_to_group;

#[cfg(feature = "op_associate_delegation_request")]
mod associate_delegation_request;

#[cfg(feature = "op_attach_group_policy")]
mod attach_group_policy;

#[cfg(feature = "op_attach_role_policy")]
mod attach_role_policy;

#[cfg(feature = "op_attach_user_policy")]
mod attach_user_policy;

#[cfg(feature = "op_change_password")]
mod change_password;

#[cfg(feature = "op_create_access_key")]
mod create_access_key;

#[cfg(feature = "op_create_account_alias")]
mod create_account_alias;

#[cfg(feature = "op_create_delegation_request")]
mod create_delegation_request;

#[cfg(feature = "op_create_group")]
mod create_group;

#[cfg(feature = "op_create_instance_profile")]
mod create_instance_profile;

#[cfg(feature = "op_create_login_profile")]
mod create_login_profile;

#[cfg(feature = "op_create_open_id_connect_provider")]
mod create_open_id_connect_provider;

#[cfg(feature = "op_create_policy")]
mod create_policy;

#[cfg(feature = "op_create_policy_version")]
mod create_policy_version;

#[cfg(feature = "op_create_role")]
mod create_role;

#[cfg(feature = "op_create_saml_provider")]
mod create_saml_provider;

#[cfg(feature = "op_create_service_linked_role")]
mod create_service_linked_role;

#[cfg(feature = "op_create_service_specific_credential")]
mod create_service_specific_credential;

#[cfg(feature = "op_create_user")]
mod create_user;

#[cfg(feature = "op_create_virtual_mfa_device")]
mod create_virtual_mfa_device;

/// Operation customization and supporting types.
///
/// The underlying HTTP requests made during an operation can be customized
/// by calling the `customize()` method on the builder returned from a client
/// operation call. For example, this can be used to add an additional HTTP header:
///
/// ```ignore
/// # async fn wrapper() -> ::std::result::Result<(), aws_sdk_iam_modular::Error> {
/// # let client: aws_sdk_iam_modular::Client = unimplemented!();
/// use ::http_1x::header::{HeaderName, HeaderValue};
///
/// let result = client.accept_delegation_request()
///     .customize()
///     .mutate_request(|req| {
///         // Add `x-example-header` with value
///         req.headers_mut()
///             .insert(
///                 HeaderName::from_static("x-example-header"),
///                 HeaderValue::from_static("1"),
///             );
///     })
///     .send()
///     .await;
/// # }
/// ```
pub mod customize;

#[cfg(feature = "op_deactivate_mfa_device")]
mod deactivate_mfa_device;

#[cfg(feature = "op_delete_access_key")]
mod delete_access_key;

#[cfg(feature = "op_delete_account_alias")]
mod delete_account_alias;

#[cfg(feature = "op_delete_account_password_policy")]
mod delete_account_password_policy;

#[cfg(feature = "op_delete_group")]
mod delete_group;

#[cfg(feature = "op_delete_group_policy")]
mod delete_group_policy;

#[cfg(feature = "op_delete_instance_profile")]
mod delete_instance_profile;

#[cfg(feature = "op_delete_login_profile")]
mod delete_login_profile;

#[cfg(feature = "op_delete_open_id_connect_provider")]
mod delete_open_id_connect_provider;

#[cfg(feature = "op_delete_policy")]
mod delete_policy;

#[cfg(feature = "op_delete_policy_version")]
mod delete_policy_version;

#[cfg(feature = "op_delete_role")]
mod delete_role;

#[cfg(feature = "op_delete_role_permissions_boundary")]
mod delete_role_permissions_boundary;

#[cfg(feature = "op_delete_role_policy")]
mod delete_role_policy;

#[cfg(feature = "op_delete_saml_provider")]
mod delete_saml_provider;

#[cfg(feature = "op_delete_server_certificate")]
mod delete_server_certificate;

#[cfg(feature = "op_delete_service_linked_role")]
mod delete_service_linked_role;

#[cfg(feature = "op_delete_service_specific_credential")]
mod delete_service_specific_credential;

#[cfg(feature = "op_delete_signing_certificate")]
mod delete_signing_certificate;

#[cfg(feature = "op_delete_ssh_public_key")]
mod delete_ssh_public_key;

#[cfg(feature = "op_delete_user")]
mod delete_user;

#[cfg(feature = "op_delete_user_permissions_boundary")]
mod delete_user_permissions_boundary;

#[cfg(feature = "op_delete_user_policy")]
mod delete_user_policy;

#[cfg(feature = "op_delete_virtual_mfa_device")]
mod delete_virtual_mfa_device;

#[cfg(feature = "op_detach_group_policy")]
mod detach_group_policy;

#[cfg(feature = "op_detach_role_policy")]
mod detach_role_policy;

#[cfg(feature = "op_detach_user_policy")]
mod detach_user_policy;

#[cfg(feature = "op_disable_organizations_root_credentials_management")]
mod disable_organizations_root_credentials_management;

#[cfg(feature = "op_disable_organizations_root_sessions")]
mod disable_organizations_root_sessions;

#[cfg(feature = "op_disable_outbound_web_identity_federation")]
mod disable_outbound_web_identity_federation;

#[cfg(feature = "op_enable_mfa_device")]
mod enable_mfa_device;

#[cfg(feature = "op_enable_organizations_root_credentials_management")]
mod enable_organizations_root_credentials_management;

#[cfg(feature = "op_enable_organizations_root_sessions")]
mod enable_organizations_root_sessions;

#[cfg(feature = "op_enable_outbound_web_identity_federation")]
mod enable_outbound_web_identity_federation;

#[cfg(feature = "op_generate_credential_report")]
mod generate_credential_report;

#[cfg(feature = "op_generate_organizations_access_report")]
mod generate_organizations_access_report;

#[cfg(feature = "op_generate_service_last_accessed_details")]
mod generate_service_last_accessed_details;

#[cfg(feature = "op_get_access_key_last_used")]
mod get_access_key_last_used;

#[cfg(feature = "op_get_account_authorization_details")]
mod get_account_authorization_details;

#[cfg(feature = "op_get_account_password_policy")]
mod get_account_password_policy;

#[cfg(feature = "op_get_account_properties")]
mod get_account_properties;

#[cfg(feature = "op_get_account_summary")]
mod get_account_summary;

#[cfg(feature = "op_get_context_keys_for_custom_policy")]
mod get_context_keys_for_custom_policy;

#[cfg(feature = "op_get_context_keys_for_principal_policy")]
mod get_context_keys_for_principal_policy;

#[cfg(feature = "op_get_credential_report")]
mod get_credential_report;

#[cfg(feature = "op_get_delegation_request")]
mod get_delegation_request;

#[cfg(feature = "op_get_group")]
mod get_group;

#[cfg(feature = "op_get_group_policy")]
mod get_group_policy;

#[cfg(feature = "op_get_human_readable_summary")]
mod get_human_readable_summary;

#[cfg(feature = "op_get_instance_profile")]
mod get_instance_profile;

#[cfg(feature = "op_get_login_profile")]
mod get_login_profile;

#[cfg(feature = "op_get_mfa_device")]
mod get_mfa_device;

#[cfg(feature = "op_get_open_id_connect_provider")]
mod get_open_id_connect_provider;

#[cfg(feature = "op_get_organizations_access_report")]
mod get_organizations_access_report;

#[cfg(feature = "op_get_outbound_web_identity_federation_info")]
mod get_outbound_web_identity_federation_info;

#[cfg(feature = "op_get_policy")]
mod get_policy;

#[cfg(feature = "op_get_policy_version")]
mod get_policy_version;

#[cfg(feature = "op_get_role")]
mod get_role;

#[cfg(feature = "op_get_role_policy")]
mod get_role_policy;

#[cfg(feature = "op_get_role_template_version")]
mod get_role_template_version;

#[cfg(feature = "op_get_saml_provider")]
mod get_saml_provider;

#[cfg(feature = "op_get_server_certificate")]
mod get_server_certificate;

#[cfg(feature = "op_get_service_last_accessed_details")]
mod get_service_last_accessed_details;

#[cfg(feature = "op_get_service_last_accessed_details_with_entities")]
mod get_service_last_accessed_details_with_entities;

#[cfg(feature = "op_get_service_linked_role_deletion_status")]
mod get_service_linked_role_deletion_status;

#[cfg(feature = "op_get_ssh_public_key")]
mod get_ssh_public_key;

#[cfg(feature = "op_get_user")]
mod get_user;

#[cfg(feature = "op_get_user_policy")]
mod get_user_policy;

#[cfg(feature = "op_list_access_keys")]
mod list_access_keys;

#[cfg(feature = "op_list_account_aliases")]
mod list_account_aliases;

#[cfg(feature = "op_list_attached_group_policies")]
mod list_attached_group_policies;

#[cfg(feature = "op_list_attached_role_policies")]
mod list_attached_role_policies;

#[cfg(feature = "op_list_attached_user_policies")]
mod list_attached_user_policies;

#[cfg(feature = "op_list_delegation_requests")]
mod list_delegation_requests;

#[cfg(feature = "op_list_entities_for_policy")]
mod list_entities_for_policy;

#[cfg(feature = "op_list_group_policies")]
mod list_group_policies;

#[cfg(feature = "op_list_groups")]
mod list_groups;

#[cfg(feature = "op_list_groups_for_user")]
mod list_groups_for_user;

#[cfg(feature = "op_list_instance_profile_tags")]
mod list_instance_profile_tags;

#[cfg(feature = "op_list_instance_profiles")]
mod list_instance_profiles;

#[cfg(feature = "op_list_instance_profiles_for_role")]
mod list_instance_profiles_for_role;

#[cfg(feature = "op_list_mfa_device_tags")]
mod list_mfa_device_tags;

#[cfg(feature = "op_list_mfa_devices")]
mod list_mfa_devices;

#[cfg(feature = "op_list_open_id_connect_provider_tags")]
mod list_open_id_connect_provider_tags;

#[cfg(feature = "op_list_open_id_connect_providers")]
mod list_open_id_connect_providers;

#[cfg(feature = "op_list_organizations_features")]
mod list_organizations_features;

#[cfg(feature = "op_list_policies")]
mod list_policies;

#[cfg(feature = "op_list_policies_granting_service_access")]
mod list_policies_granting_service_access;

#[cfg(feature = "op_list_policy_tags")]
mod list_policy_tags;

#[cfg(feature = "op_list_policy_versions")]
mod list_policy_versions;

#[cfg(feature = "op_list_role_policies")]
mod list_role_policies;

#[cfg(feature = "op_list_role_tags")]
mod list_role_tags;

#[cfg(feature = "op_list_roles")]
mod list_roles;

#[cfg(feature = "op_list_saml_provider_tags")]
mod list_saml_provider_tags;

#[cfg(feature = "op_list_saml_providers")]
mod list_saml_providers;

#[cfg(feature = "op_list_server_certificate_tags")]
mod list_server_certificate_tags;

#[cfg(feature = "op_list_server_certificates")]
mod list_server_certificates;

#[cfg(feature = "op_list_service_specific_credentials")]
mod list_service_specific_credentials;

#[cfg(feature = "op_list_signing_certificates")]
mod list_signing_certificates;

#[cfg(feature = "op_list_ssh_public_keys")]
mod list_ssh_public_keys;

#[cfg(feature = "op_list_user_policies")]
mod list_user_policies;

#[cfg(feature = "op_list_user_tags")]
mod list_user_tags;

#[cfg(feature = "op_list_users")]
mod list_users;

#[cfg(feature = "op_list_virtual_mfa_devices")]
mod list_virtual_mfa_devices;

#[cfg(feature = "op_put_account_properties")]
mod put_account_properties;

#[cfg(feature = "op_put_group_policy")]
mod put_group_policy;

#[cfg(feature = "op_put_role_permissions_boundary")]
mod put_role_permissions_boundary;

#[cfg(feature = "op_put_role_policy")]
mod put_role_policy;

#[cfg(feature = "op_put_user_permissions_boundary")]
mod put_user_permissions_boundary;

#[cfg(feature = "op_put_user_policy")]
mod put_user_policy;

#[cfg(feature = "op_reject_delegation_request")]
mod reject_delegation_request;

#[cfg(feature = "op_remove_client_id_from_open_id_connect_provider")]
mod remove_client_id_from_open_id_connect_provider;

#[cfg(feature = "op_remove_role_from_instance_profile")]
mod remove_role_from_instance_profile;

#[cfg(feature = "op_remove_user_from_group")]
mod remove_user_from_group;

#[cfg(feature = "op_reset_service_specific_credential")]
mod reset_service_specific_credential;

#[cfg(feature = "op_resync_mfa_device")]
mod resync_mfa_device;

#[cfg(feature = "op_send_delegation_token")]
mod send_delegation_token;

#[cfg(feature = "op_set_default_policy_version")]
mod set_default_policy_version;

#[cfg(feature = "op_set_security_token_service_preferences")]
mod set_security_token_service_preferences;

#[cfg(feature = "op_simulate_custom_policy")]
mod simulate_custom_policy;

#[cfg(feature = "op_simulate_principal_policy")]
mod simulate_principal_policy;

#[cfg(feature = "op_tag_instance_profile")]
mod tag_instance_profile;

#[cfg(feature = "op_tag_mfa_device")]
mod tag_mfa_device;

#[cfg(feature = "op_tag_open_id_connect_provider")]
mod tag_open_id_connect_provider;

#[cfg(feature = "op_tag_policy")]
mod tag_policy;

#[cfg(feature = "op_tag_role")]
mod tag_role;

#[cfg(feature = "op_tag_saml_provider")]
mod tag_saml_provider;

#[cfg(feature = "op_tag_server_certificate")]
mod tag_server_certificate;

#[cfg(feature = "op_tag_user")]
mod tag_user;

#[cfg(feature = "op_untag_instance_profile")]
mod untag_instance_profile;

#[cfg(feature = "op_untag_mfa_device")]
mod untag_mfa_device;

#[cfg(feature = "op_untag_open_id_connect_provider")]
mod untag_open_id_connect_provider;

#[cfg(feature = "op_untag_policy")]
mod untag_policy;

#[cfg(feature = "op_untag_role")]
mod untag_role;

#[cfg(feature = "op_untag_saml_provider")]
mod untag_saml_provider;

#[cfg(feature = "op_untag_server_certificate")]
mod untag_server_certificate;

#[cfg(feature = "op_untag_user")]
mod untag_user;

#[cfg(feature = "op_update_access_key")]
mod update_access_key;

#[cfg(feature = "op_update_account_password_policy")]
mod update_account_password_policy;

#[cfg(feature = "op_update_assume_role_policy")]
mod update_assume_role_policy;

#[cfg(feature = "op_update_delegation_request")]
mod update_delegation_request;

#[cfg(feature = "op_update_group")]
mod update_group;

#[cfg(feature = "op_update_login_profile")]
mod update_login_profile;

#[cfg(feature = "op_update_open_id_connect_provider_thumbprint")]
mod update_open_id_connect_provider_thumbprint;

#[cfg(feature = "op_update_role")]
mod update_role;

#[cfg(feature = "op_update_role_description")]
mod update_role_description;

#[cfg(feature = "op_update_saml_provider")]
mod update_saml_provider;

#[cfg(feature = "op_update_server_certificate")]
mod update_server_certificate;

#[cfg(feature = "op_update_service_specific_credential")]
mod update_service_specific_credential;

#[cfg(feature = "op_update_signing_certificate")]
mod update_signing_certificate;

#[cfg(feature = "op_update_ssh_public_key")]
mod update_ssh_public_key;

#[cfg(feature = "op_update_user")]
mod update_user;

#[cfg(feature = "op_upload_server_certificate")]
mod upload_server_certificate;

#[cfg(feature = "op_upload_signing_certificate")]
mod upload_signing_certificate;

#[cfg(feature = "op_upload_ssh_public_key")]
mod upload_ssh_public_key;
