// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Output structure for CreateOAuth2TokenWithIAM operation Contains the JWT access token, token type, and expiration per RFC 6749 §5.1.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct CreateOAuth2TokenWithIamOutput {
    /// JWT access token containing principal identity, resource scope, and session metadata
    pub access_token: ::std::string::String,
    /// Always "Bearer" per OAuth 2.1 specification
    pub token_type: ::std::string::String,
    /// Token lifetime in seconds. Value is the minimum of session validity and 1 hour.
    pub expires_in: i32,
    _request_id: Option<String>,
}
impl CreateOAuth2TokenWithIamOutput {
    /// JWT access token containing principal identity, resource scope, and session metadata
    pub fn access_token(&self) -> &str {
        use std::ops::Deref;
        self.access_token.deref()
    }
    /// Always "Bearer" per OAuth 2.1 specification
    pub fn token_type(&self) -> &str {
        use std::ops::Deref;
        self.token_type.deref()
    }
    /// Token lifetime in seconds. Value is the minimum of session validity and 1 hour.
    pub fn expires_in(&self) -> i32 {
        self.expires_in
    }
}
impl ::std::fmt::Debug for CreateOAuth2TokenWithIamOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("CreateOAuth2TokenWithIamOutput");
        formatter.field("access_token", &"*** Sensitive Data Redacted ***");
        formatter.field("token_type", &self.token_type);
        formatter.field("expires_in", &self.expires_in);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
impl ::aws_types::request_id::RequestId for CreateOAuth2TokenWithIamOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl CreateOAuth2TokenWithIamOutput {
    /// Creates a new builder-style object to manufacture [`CreateOAuth2TokenWithIamOutput`](crate::operation::create_o_auth2_token_with_iam::CreateOAuth2TokenWithIamOutput).
    pub fn builder() -> crate::operation::create_o_auth2_token_with_iam::builders::CreateOAuth2TokenWithIamOutputBuilder {
        crate::operation::create_o_auth2_token_with_iam::builders::CreateOAuth2TokenWithIamOutputBuilder::default()
    }
}

/// A builder for [`CreateOAuth2TokenWithIamOutput`](crate::operation::create_o_auth2_token_with_iam::CreateOAuth2TokenWithIamOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct CreateOAuth2TokenWithIamOutputBuilder {
    pub(crate) access_token: ::std::option::Option<::std::string::String>,
    pub(crate) token_type: ::std::option::Option<::std::string::String>,
    pub(crate) expires_in: ::std::option::Option<i32>,
    _request_id: Option<String>,
}
impl CreateOAuth2TokenWithIamOutputBuilder {
    /// JWT access token containing principal identity, resource scope, and session metadata
    /// This field is required.
    pub fn access_token(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.access_token = ::std::option::Option::Some(input.into());
        self
    }
    /// JWT access token containing principal identity, resource scope, and session metadata
    pub fn set_access_token(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.access_token = input;
        self
    }
    /// JWT access token containing principal identity, resource scope, and session metadata
    pub fn get_access_token(&self) -> &::std::option::Option<::std::string::String> {
        &self.access_token
    }
    /// Always "Bearer" per OAuth 2.1 specification
    /// This field is required.
    pub fn token_type(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.token_type = ::std::option::Option::Some(input.into());
        self
    }
    /// Always "Bearer" per OAuth 2.1 specification
    pub fn set_token_type(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.token_type = input;
        self
    }
    /// Always "Bearer" per OAuth 2.1 specification
    pub fn get_token_type(&self) -> &::std::option::Option<::std::string::String> {
        &self.token_type
    }
    /// Token lifetime in seconds. Value is the minimum of session validity and 1 hour.
    /// This field is required.
    pub fn expires_in(mut self, input: i32) -> Self {
        self.expires_in = ::std::option::Option::Some(input);
        self
    }
    /// Token lifetime in seconds. Value is the minimum of session validity and 1 hour.
    pub fn set_expires_in(mut self, input: ::std::option::Option<i32>) -> Self {
        self.expires_in = input;
        self
    }
    /// Token lifetime in seconds. Value is the minimum of session validity and 1 hour.
    pub fn get_expires_in(&self) -> &::std::option::Option<i32> {
        &self.expires_in
    }
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`CreateOAuth2TokenWithIamOutput`](crate::operation::create_o_auth2_token_with_iam::CreateOAuth2TokenWithIamOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`access_token`](crate::operation::create_o_auth2_token_with_iam::builders::CreateOAuth2TokenWithIamOutputBuilder::access_token)
    /// - [`token_type`](crate::operation::create_o_auth2_token_with_iam::builders::CreateOAuth2TokenWithIamOutputBuilder::token_type)
    /// - [`expires_in`](crate::operation::create_o_auth2_token_with_iam::builders::CreateOAuth2TokenWithIamOutputBuilder::expires_in)
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::create_o_auth2_token_with_iam::CreateOAuth2TokenWithIamOutput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::create_o_auth2_token_with_iam::CreateOAuth2TokenWithIamOutput {
            access_token: self.access_token.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "access_token",
                    "access_token was not specified but it is required when building CreateOAuth2TokenWithIamOutput",
                )
            })?,
            token_type: self.token_type.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "token_type",
                    "token_type was not specified but it is required when building CreateOAuth2TokenWithIamOutput",
                )
            })?,
            expires_in: self.expires_in.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "expires_in",
                    "expires_in was not specified but it is required when building CreateOAuth2TokenWithIamOutput",
                )
            })?,
            _request_id: self._request_id,
        })
    }
}
impl ::std::fmt::Debug for CreateOAuth2TokenWithIamOutputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("CreateOAuth2TokenWithIamOutputBuilder");
        formatter.field("access_token", &"*** Sensitive Data Redacted ***");
        formatter.field("token_type", &self.token_type);
        formatter.field("expires_in", &self.expires_in);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
