// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_put_delivery_destination_policy")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PutDeliveryDestinationPolicyInput {
    /// <p>The name of the delivery destination to assign this policy to.</p>
    pub delivery_destination_name: ::std::option::Option<::std::string::String>,
    /// <p>The contents of the policy.</p>
    pub delivery_destination_policy: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_put_delivery_destination_policy")]
impl PutDeliveryDestinationPolicyInput {
    /// <p>The name of the delivery destination to assign this policy to.</p>
    pub fn delivery_destination_name(&self) -> ::std::option::Option<&str> {
        self.delivery_destination_name.as_deref()
    }
    /// <p>The contents of the policy.</p>
    pub fn delivery_destination_policy(&self) -> ::std::option::Option<&str> {
        self.delivery_destination_policy.as_deref()
    }
}
#[cfg(feature = "op_put_delivery_destination_policy")]
impl PutDeliveryDestinationPolicyInput {
    /// Creates a new builder-style object to manufacture [`PutDeliveryDestinationPolicyInput`](crate::operation::put_delivery_destination_policy::PutDeliveryDestinationPolicyInput).
    pub fn builder() -> crate::operation::put_delivery_destination_policy::builders::PutDeliveryDestinationPolicyInputBuilder {
        crate::operation::put_delivery_destination_policy::builders::PutDeliveryDestinationPolicyInputBuilder::default()
    }
}

#[cfg(feature = "op_put_delivery_destination_policy")]
/// A builder for [`PutDeliveryDestinationPolicyInput`](crate::operation::put_delivery_destination_policy::PutDeliveryDestinationPolicyInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct PutDeliveryDestinationPolicyInputBuilder {
    pub(crate) delivery_destination_name: ::std::option::Option<::std::string::String>,
    pub(crate) delivery_destination_policy: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_put_delivery_destination_policy")]
impl PutDeliveryDestinationPolicyInputBuilder {
    /// <p>The name of the delivery destination to assign this policy to.</p>
    /// This field is required.
    pub fn delivery_destination_name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.delivery_destination_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the delivery destination to assign this policy to.</p>
    pub fn set_delivery_destination_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.delivery_destination_name = input;
        self
    }
    /// <p>The name of the delivery destination to assign this policy to.</p>
    pub fn get_delivery_destination_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.delivery_destination_name
    }
    /// <p>The contents of the policy.</p>
    /// This field is required.
    pub fn delivery_destination_policy(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.delivery_destination_policy = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The contents of the policy.</p>
    pub fn set_delivery_destination_policy(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.delivery_destination_policy = input;
        self
    }
    /// <p>The contents of the policy.</p>
    pub fn get_delivery_destination_policy(&self) -> &::std::option::Option<::std::string::String> {
        &self.delivery_destination_policy
    }
    /// Consumes the builder and constructs a [`PutDeliveryDestinationPolicyInput`](crate::operation::put_delivery_destination_policy::PutDeliveryDestinationPolicyInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::put_delivery_destination_policy::PutDeliveryDestinationPolicyInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::put_delivery_destination_policy::PutDeliveryDestinationPolicyInput {
            delivery_destination_name: self.delivery_destination_name,
            delivery_destination_policy: self.delivery_destination_policy,
        })
    }
}
