// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[derive(Debug)]
pub(crate) struct Handle {
    pub(crate) conf: crate::Config,
    #[allow(dead_code)] // unused when a service does not provide any operations
    pub(crate) runtime_plugins: ::aws_smithy_runtime_api::client::runtime_plugin::RuntimePlugins,
}

/// Client for Amazon DynamoDB
///
/// Client for invoking operations on Amazon DynamoDB. Each operation on Amazon DynamoDB is a method on this
/// this struct. `.send()` MUST be invoked on the generated operations to dispatch the request to the service.
/// ## Constructing a `Client`
///
/// A [`Config`] is required to construct a client. For most use cases, the [`aws-config`]
/// crate should be used to automatically resolve this config using
/// [`aws_config::load_from_env()`], since this will resolve an [`SdkConfig`] which can be shared
/// across multiple different AWS SDK clients. This config resolution process can be customized
/// by calling [`aws_config::from_env()`] instead, which returns a [`ConfigLoader`] that uses
/// the [builder pattern] to customize the default config.
///
/// In the simplest case, creating a client looks as follows:
/// ```rust,no_run
/// # async fn wrapper() {
/// let config = aws_config::load_from_env().await;
/// let client = aws_sdk_dynamodb::Client::new(&config);
/// # }
/// ```
///
/// Occasionally, SDKs may have additional service-specific values that can be set on the [`Config`] that
/// is absent from [`SdkConfig`], or slightly different settings for a specific client may be desired.
/// The [`Builder`](crate::config::Builder) struct implements `From<&SdkConfig>`, so setting these specific settings can be
/// done as follows:
///
/// ```rust,no_run
/// # async fn wrapper() {
/// let sdk_config = ::aws_config::load_from_env().await;
/// let config = aws_sdk_dynamodb::config::Builder::from(&sdk_config)
/// # /*
///     .some_service_specific_setting("value")
/// # */
///     .build();
/// # }
/// ```
///
/// See the [`aws-config` docs] and [`Config`] for more information on customizing configuration.
///
/// _Note:_ Client construction is expensive due to connection thread pool initialization, and should
/// be done once at application start-up.
///
/// [`Config`]: crate::Config
/// [`ConfigLoader`]: https://docs.rs/aws-config/*/aws_config/struct.ConfigLoader.html
/// [`SdkConfig`]: https://docs.rs/aws-config/*/aws_config/struct.SdkConfig.html
/// [`aws-config` docs]: https://docs.rs/aws-config/*
/// [`aws-config`]: https://crates.io/crates/aws-config
/// [`aws_config::from_env()`]: https://docs.rs/aws-config/*/aws_config/fn.from_env.html
/// [`aws_config::load_from_env()`]: https://docs.rs/aws-config/*/aws_config/fn.load_from_env.html
/// [builder pattern]: https://rust-lang.github.io/api-guidelines/type-safety.html#builders-enable-construction-of-complex-values-c-builder
/// # Using the `Client`
///
/// A client has a function for every operation that can be performed by the service.
/// For example, the [`BatchExecuteStatement`](crate::operation::batch_execute_statement) operation has
/// a [`Client::batch_execute_statement`], function which returns a builder for that operation.
/// The fluent builder ultimately has a `send()` function that returns an async future that
/// returns a result, as illustrated below:
///
/// ```rust,ignore
/// let result = client.batch_execute_statement()
///     .return_consumed_capacity("example")
///     .send()
///     .await;
/// ```
///
/// The underlying HTTP requests that get made by this can be modified with the `customize_operation`
/// function on the fluent builder. See the [`customize`](crate::client::customize) module for more
/// information.
/// # Waiters
///
/// This client provides `wait_until` methods behind the [`Waiters`](crate::client::Waiters) trait.
/// To use them, simply import the trait, and then call one of the `wait_until` methods. This will
/// return a waiter fluent builder that takes various parameters, which are documented on the builder
/// type. Once parameters have been provided, the `wait` method can be called to initiate waiting.
///
/// For example, if there was a `wait_until_thing` method, it could look like:
/// ```rust,ignore
/// let result = client.wait_until_thing()
///     .thing_id("someId")
///     .wait(Duration::from_secs(120))
///     .await;
/// ```
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct Client {
    handle: ::std::sync::Arc<Handle>,
}

impl Client {
    /// Creates a new client from the service [`Config`](crate::Config).
    ///
    /// # Panics
    ///
    /// This method will panic in the following cases:
    ///
    /// - Retries or timeouts are enabled without a `sleep_impl` configured.
    /// - Identity caching is enabled without a `sleep_impl` and `time_source` configured.
    /// - No `behavior_version` is provided.
    ///
    /// The panic message for each of these will have instructions on how to resolve them.
    #[track_caller]
    pub fn from_conf(conf: crate::Config) -> Self {
        let handle = Handle {
            conf: conf.clone(),
            runtime_plugins: crate::config::base_client_runtime_plugins(conf),
        };
        if let Err(err) = Self::validate_config(&handle) {
            panic!("Invalid client configuration: {err}");
        }
        Self {
            handle: ::std::sync::Arc::new(handle),
        }
    }

    /// Returns the client's configuration.
    pub fn config(&self) -> &crate::Config {
        &self.handle.conf
    }

    fn validate_config(handle: &Handle) -> ::std::result::Result<(), ::aws_smithy_runtime_api::box_error::BoxError> {
        let mut cfg = ::aws_smithy_types::config_bag::ConfigBag::base();
        handle
            .runtime_plugins
            .apply_client_configuration(&mut cfg)?
            .validate_base_client_config(&cfg)?;
        Ok(())
    }
}

///
/// Waiter functions for the client.
///
/// Import this trait to get `wait_until` methods on the client.
///
pub trait Waiters {
    #[cfg(feature = "op_describe_contributor_insights")]
    /// Wait for `contributor_insights_enabled`
    fn wait_until_contributor_insights_enabled(
        &self,
    ) -> crate::waiters::contributor_insights_enabled::ContributorInsightsEnabledFluentBuilder;
    #[cfg(feature = "op_describe_export")]
    /// Wait for `export_completed`
    fn wait_until_export_completed(&self) -> crate::waiters::export_completed::ExportCompletedFluentBuilder;
    #[cfg(feature = "op_describe_import")]
    /// Wait for `import_completed`
    fn wait_until_import_completed(&self) -> crate::waiters::import_completed::ImportCompletedFluentBuilder;
    #[cfg(feature = "op_describe_kinesis_streaming_destination")]
    /// Wait for `kinesis_streaming_destination_active`
    fn wait_until_kinesis_streaming_destination_active(
        &self,
    ) -> crate::waiters::kinesis_streaming_destination_active::KinesisStreamingDestinationActiveFluentBuilder;
    #[cfg(feature = "op_describe_table")]
    /// Wait for `table_exists`
    fn wait_until_table_exists(&self) -> crate::waiters::table_exists::TableExistsFluentBuilder;
    #[cfg(feature = "op_describe_table")]
    /// Wait for `table_not_exists`
    fn wait_until_table_not_exists(&self) -> crate::waiters::table_not_exists::TableNotExistsFluentBuilder;
}
impl Waiters for Client {
    #[cfg(feature = "op_describe_contributor_insights")]
    fn wait_until_contributor_insights_enabled(
        &self,
    ) -> crate::waiters::contributor_insights_enabled::ContributorInsightsEnabledFluentBuilder {
        crate::waiters::contributor_insights_enabled::ContributorInsightsEnabledFluentBuilder::new(self.handle.clone())
    }
    #[cfg(feature = "op_describe_export")]
    fn wait_until_export_completed(&self) -> crate::waiters::export_completed::ExportCompletedFluentBuilder {
        crate::waiters::export_completed::ExportCompletedFluentBuilder::new(self.handle.clone())
    }
    #[cfg(feature = "op_describe_import")]
    fn wait_until_import_completed(&self) -> crate::waiters::import_completed::ImportCompletedFluentBuilder {
        crate::waiters::import_completed::ImportCompletedFluentBuilder::new(self.handle.clone())
    }
    #[cfg(feature = "op_describe_kinesis_streaming_destination")]
    fn wait_until_kinesis_streaming_destination_active(
        &self,
    ) -> crate::waiters::kinesis_streaming_destination_active::KinesisStreamingDestinationActiveFluentBuilder {
        crate::waiters::kinesis_streaming_destination_active::KinesisStreamingDestinationActiveFluentBuilder::new(
            self.handle.clone(),
        )
    }
    #[cfg(feature = "op_describe_table")]
    fn wait_until_table_exists(&self) -> crate::waiters::table_exists::TableExistsFluentBuilder {
        crate::waiters::table_exists::TableExistsFluentBuilder::new(self.handle.clone())
    }
    #[cfg(feature = "op_describe_table")]
    fn wait_until_table_not_exists(&self) -> crate::waiters::table_not_exists::TableNotExistsFluentBuilder {
        crate::waiters::table_not_exists::TableNotExistsFluentBuilder::new(self.handle.clone())
    }
}

impl Client {
    /// Creates a new client from an [SDK Config](::aws_types::sdk_config::SdkConfig).
    ///
    /// # Panics
    ///
    /// - This method will panic if the `sdk_config` is missing an async sleep implementation. If you experience this panic, set
    ///   the `sleep_impl` on the Config passed into this function to fix it.
    /// - This method will panic if the `sdk_config` is missing an HTTP connector. If you experience this panic, set the
    ///   `http_connector` on the Config passed into this function to fix it.
    /// - This method will panic if no `BehaviorVersion` is provided. If you experience this panic, set `behavior_version` on the Config or enable the `behavior-version-latest` Cargo feature.
    #[track_caller]
    pub fn new(sdk_config: &::aws_types::sdk_config::SdkConfig) -> Self {
        Self::from_conf(sdk_config.into())
    }
}

#[cfg(feature = "op_batch_execute_statement")]
mod batch_execute_statement;

#[cfg(feature = "op_batch_get_item")]
mod batch_get_item;

#[cfg(feature = "op_batch_write_item")]
mod batch_write_item;

#[cfg(feature = "op_create_backup")]
mod create_backup;

#[cfg(feature = "op_create_global_table")]
mod create_global_table;

#[cfg(feature = "op_create_table")]
mod create_table;

/// Operation customization and supporting types.
///
/// The underlying HTTP requests made during an operation can be customized
/// by calling the `customize()` method on the builder returned from a client
/// operation call. For example, this can be used to add an additional HTTP header:
///
/// ```ignore
/// # async fn wrapper() -> ::std::result::Result<(), aws_sdk_dynamodb::Error> {
/// # let client: aws_sdk_dynamodb::Client = unimplemented!();
/// use ::http_1x::header::{HeaderName, HeaderValue};
///
/// let result = client.batch_execute_statement()
///     .customize()
///     .mutate_request(|req| {
///         // Add `x-example-header` with value
///         req.headers_mut()
///             .insert(
///                 HeaderName::from_static("x-example-header"),
///                 HeaderValue::from_static("1"),
///             );
///     })
///     .send()
///     .await;
/// # }
/// ```
pub mod customize;

#[cfg(feature = "op_delete_backup")]
mod delete_backup;

#[cfg(feature = "op_delete_item")]
mod delete_item;

#[cfg(feature = "op_delete_resource_policy")]
mod delete_resource_policy;

#[cfg(feature = "op_delete_table")]
mod delete_table;

#[cfg(feature = "op_describe_backup")]
mod describe_backup;

#[cfg(feature = "op_describe_continuous_backups")]
mod describe_continuous_backups;

#[cfg(feature = "op_describe_contributor_insights")]
mod describe_contributor_insights;

#[cfg(feature = "op_describe_endpoints")]
mod describe_endpoints;

#[cfg(feature = "op_describe_export")]
mod describe_export;

#[cfg(feature = "op_describe_global_table")]
mod describe_global_table;

#[cfg(feature = "op_describe_global_table_settings")]
mod describe_global_table_settings;

#[cfg(feature = "op_describe_import")]
mod describe_import;

#[cfg(feature = "op_describe_kinesis_streaming_destination")]
mod describe_kinesis_streaming_destination;

#[cfg(feature = "op_describe_limits")]
mod describe_limits;

#[cfg(feature = "op_describe_table")]
mod describe_table;

#[cfg(feature = "op_describe_table_replica_auto_scaling")]
mod describe_table_replica_auto_scaling;

#[cfg(feature = "op_describe_time_to_live")]
mod describe_time_to_live;

#[cfg(feature = "op_disable_kinesis_streaming_destination")]
mod disable_kinesis_streaming_destination;

#[cfg(feature = "op_enable_kinesis_streaming_destination")]
mod enable_kinesis_streaming_destination;

#[cfg(feature = "op_execute_statement")]
mod execute_statement;

#[cfg(feature = "op_execute_transaction")]
mod execute_transaction;

#[cfg(feature = "op_export_table_to_point_in_time")]
mod export_table_to_point_in_time;

#[cfg(feature = "op_get_item")]
mod get_item;

#[cfg(feature = "op_get_resource_policy")]
mod get_resource_policy;

#[cfg(feature = "op_import_table")]
mod import_table;

#[cfg(feature = "op_list_backups")]
mod list_backups;

#[cfg(feature = "op_list_contributor_insights")]
mod list_contributor_insights;

#[cfg(feature = "op_list_exports")]
mod list_exports;

#[cfg(feature = "op_list_global_tables")]
mod list_global_tables;

#[cfg(feature = "op_list_imports")]
mod list_imports;

#[cfg(feature = "op_list_tables")]
mod list_tables;

#[cfg(feature = "op_list_tags_of_resource")]
mod list_tags_of_resource;

#[cfg(feature = "op_put_item")]
mod put_item;

#[cfg(feature = "op_put_resource_policy")]
mod put_resource_policy;

#[cfg(feature = "op_query")]
mod query;

#[cfg(feature = "op_restore_table_from_backup")]
mod restore_table_from_backup;

#[cfg(feature = "op_restore_table_to_point_in_time")]
mod restore_table_to_point_in_time;

#[cfg(feature = "op_scan")]
mod scan;

#[cfg(feature = "op_search_vectors")]
mod search_vectors;

#[cfg(feature = "op_tag_resource")]
mod tag_resource;

#[cfg(feature = "op_transact_get_items")]
mod transact_get_items;

#[cfg(feature = "op_transact_write_items")]
mod transact_write_items;

#[cfg(feature = "op_untag_resource")]
mod untag_resource;

#[cfg(feature = "op_update_continuous_backups")]
mod update_continuous_backups;

#[cfg(feature = "op_update_contributor_insights")]
mod update_contributor_insights;

#[cfg(feature = "op_update_global_table")]
mod update_global_table;

#[cfg(feature = "op_update_global_table_settings")]
mod update_global_table_settings;

#[cfg(feature = "op_update_item")]
mod update_item;

#[cfg(feature = "op_update_kinesis_streaming_destination")]
mod update_kinesis_streaming_destination;

#[cfg(feature = "op_update_table")]
mod update_table;

#[cfg(feature = "op_update_table_replica_auto_scaling")]
mod update_table_replica_auto_scaling;

#[cfg(feature = "op_update_time_to_live")]
mod update_time_to_live;
