// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_update_auth_event_feedback")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UpdateAuthEventFeedbackOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_update_auth_event_feedback")]
impl ::aws_types::request_id::RequestId for UpdateAuthEventFeedbackOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_update_auth_event_feedback")]
impl UpdateAuthEventFeedbackOutput {
    /// Creates a new builder-style object to manufacture [`UpdateAuthEventFeedbackOutput`](crate::operation::update_auth_event_feedback::UpdateAuthEventFeedbackOutput).
    pub fn builder() -> crate::operation::update_auth_event_feedback::builders::UpdateAuthEventFeedbackOutputBuilder {
        crate::operation::update_auth_event_feedback::builders::UpdateAuthEventFeedbackOutputBuilder::default()
    }
}

#[cfg(feature = "op_update_auth_event_feedback")]
/// A builder for [`UpdateAuthEventFeedbackOutput`](crate::operation::update_auth_event_feedback::UpdateAuthEventFeedbackOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UpdateAuthEventFeedbackOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_update_auth_event_feedback")]
impl UpdateAuthEventFeedbackOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`UpdateAuthEventFeedbackOutput`](crate::operation::update_auth_event_feedback::UpdateAuthEventFeedbackOutput).
    pub fn build(self) -> crate::operation::update_auth_event_feedback::UpdateAuthEventFeedbackOutput {
        crate::operation::update_auth_event_feedback::UpdateAuthEventFeedbackOutput {
            _request_id: self._request_id,
        }
    }
}
