// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_retention_configuration")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteRetentionConfigurationInput {
    /// <p>The name of the retention configuration to delete.</p>
    pub retention_configuration_name: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_delete_retention_configuration")]
impl DeleteRetentionConfigurationInput {
    /// <p>The name of the retention configuration to delete.</p>
    pub fn retention_configuration_name(&self) -> ::std::option::Option<&str> {
        self.retention_configuration_name.as_deref()
    }
}
#[cfg(feature = "op_delete_retention_configuration")]
impl DeleteRetentionConfigurationInput {
    /// Creates a new builder-style object to manufacture [`DeleteRetentionConfigurationInput`](crate::operation::delete_retention_configuration::DeleteRetentionConfigurationInput).
    pub fn builder() -> crate::operation::delete_retention_configuration::builders::DeleteRetentionConfigurationInputBuilder{
        crate::operation::delete_retention_configuration::builders::DeleteRetentionConfigurationInputBuilder::default()
    }
}

#[cfg(feature = "op_delete_retention_configuration")]
/// A builder for [`DeleteRetentionConfigurationInput`](crate::operation::delete_retention_configuration::DeleteRetentionConfigurationInput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct DeleteRetentionConfigurationInputBuilder {
    pub(crate) retention_configuration_name: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_delete_retention_configuration")]
impl DeleteRetentionConfigurationInputBuilder {
    /// <p>The name of the retention configuration to delete.</p>
    /// This field is required.
    pub fn retention_configuration_name(
        mut self,
        input: impl ::std::convert::Into<::std::string::String>,
    ) -> Self {
        self.retention_configuration_name = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The name of the retention configuration to delete.</p>
    pub fn set_retention_configuration_name(
        mut self,
        input: ::std::option::Option<::std::string::String>,
    ) -> Self {
        self.retention_configuration_name = input;
        self
    }
    /// <p>The name of the retention configuration to delete.</p>
    pub fn get_retention_configuration_name(
        &self,
    ) -> &::std::option::Option<::std::string::String> {
        &self.retention_configuration_name
    }
    /// Consumes the builder and constructs a [`DeleteRetentionConfigurationInput`](crate::operation::delete_retention_configuration::DeleteRetentionConfigurationInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::delete_retention_configuration::DeleteRetentionConfigurationInput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::delete_retention_configuration::DeleteRetentionConfigurationInput {
                retention_configuration_name: self.retention_configuration_name,
            },
        )
    }
}
