// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>An object that represents the details of the first <code>RUNNABLE</code> job in each named quota share associated with a single job queue.</p>
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct FrontOfQuotaSharesDetail {
    /// <p>Contains a list of the first <code>RUNNABLE</code> job in each named quota share.</p>
    pub quota_shares:
        ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::vec::Vec<crate::types::FrontOfQuotaShareJobSummary>>>,
    /// <p>The Unix timestamp (in milliseconds) for when the first <code>RUNNABLE</code> job per quota share were all last updated.</p>
    pub last_updated_at: ::std::option::Option<i64>,
}
impl FrontOfQuotaSharesDetail {
    /// <p>Contains a list of the first <code>RUNNABLE</code> job in each named quota share.</p>
    pub fn quota_shares(
        &self,
    ) -> ::std::option::Option<&::std::collections::HashMap<::std::string::String, ::std::vec::Vec<crate::types::FrontOfQuotaShareJobSummary>>> {
        self.quota_shares.as_ref()
    }
    /// <p>The Unix timestamp (in milliseconds) for when the first <code>RUNNABLE</code> job per quota share were all last updated.</p>
    pub fn last_updated_at(&self) -> ::std::option::Option<i64> {
        self.last_updated_at
    }
}
impl FrontOfQuotaSharesDetail {
    /// Creates a new builder-style object to manufacture [`FrontOfQuotaSharesDetail`](crate::types::FrontOfQuotaSharesDetail).
    pub fn builder() -> crate::types::builders::FrontOfQuotaSharesDetailBuilder {
        crate::types::builders::FrontOfQuotaSharesDetailBuilder::default()
    }
}

/// A builder for [`FrontOfQuotaSharesDetail`](crate::types::FrontOfQuotaSharesDetail).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct FrontOfQuotaSharesDetailBuilder {
    pub(crate) quota_shares:
        ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::vec::Vec<crate::types::FrontOfQuotaShareJobSummary>>>,
    pub(crate) last_updated_at: ::std::option::Option<i64>,
}
impl FrontOfQuotaSharesDetailBuilder {
    /// Adds a key-value pair to `quota_shares`.
    ///
    /// To override the contents of this collection use [`set_quota_shares`](Self::set_quota_shares).
    ///
    /// <p>Contains a list of the first <code>RUNNABLE</code> job in each named quota share.</p>
    pub fn quota_shares(
        mut self,
        k: impl ::std::convert::Into<::std::string::String>,
        v: ::std::vec::Vec<crate::types::FrontOfQuotaShareJobSummary>,
    ) -> Self {
        let mut hash_map = self.quota_shares.unwrap_or_default();
        hash_map.insert(k.into(), v);
        self.quota_shares = ::std::option::Option::Some(hash_map);
        self
    }
    /// <p>Contains a list of the first <code>RUNNABLE</code> job in each named quota share.</p>
    pub fn set_quota_shares(
        mut self,
        input: ::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::vec::Vec<crate::types::FrontOfQuotaShareJobSummary>>>,
    ) -> Self {
        self.quota_shares = input;
        self
    }
    /// <p>Contains a list of the first <code>RUNNABLE</code> job in each named quota share.</p>
    pub fn get_quota_shares(
        &self,
    ) -> &::std::option::Option<::std::collections::HashMap<::std::string::String, ::std::vec::Vec<crate::types::FrontOfQuotaShareJobSummary>>> {
        &self.quota_shares
    }
    /// <p>The Unix timestamp (in milliseconds) for when the first <code>RUNNABLE</code> job per quota share were all last updated.</p>
    pub fn last_updated_at(mut self, input: i64) -> Self {
        self.last_updated_at = ::std::option::Option::Some(input);
        self
    }
    /// <p>The Unix timestamp (in milliseconds) for when the first <code>RUNNABLE</code> job per quota share were all last updated.</p>
    pub fn set_last_updated_at(mut self, input: ::std::option::Option<i64>) -> Self {
        self.last_updated_at = input;
        self
    }
    /// <p>The Unix timestamp (in milliseconds) for when the first <code>RUNNABLE</code> job per quota share were all last updated.</p>
    pub fn get_last_updated_at(&self) -> &::std::option::Option<i64> {
        &self.last_updated_at
    }
    /// Consumes the builder and constructs a [`FrontOfQuotaSharesDetail`](crate::types::FrontOfQuotaSharesDetail).
    pub fn build(self) -> crate::types::FrontOfQuotaSharesDetail {
        crate::types::FrontOfQuotaSharesDetail {
            quota_shares: self.quota_shares,
            last_updated_at: self.last_updated_at,
        }
    }
}
