// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_cancel_import_task")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CancelImportTaskInput {
    /// <p>The ID of the import task to cancel.</p>
    pub import_id: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_cancel_import_task")]
impl CancelImportTaskInput {
    /// <p>The ID of the import task to cancel.</p>
    pub fn import_id(&self) -> ::std::option::Option<&str> {
        self.import_id.as_deref()
    }
}
#[cfg(feature = "op_cancel_import_task")]
impl CancelImportTaskInput {
    /// Creates a new builder-style object to manufacture [`CancelImportTaskInput`](crate::operation::cancel_import_task::CancelImportTaskInput).
    pub fn builder() -> crate::operation::cancel_import_task::builders::CancelImportTaskInputBuilder {
        crate::operation::cancel_import_task::builders::CancelImportTaskInputBuilder::default()
    }
}

#[cfg(feature = "op_cancel_import_task")]
/// A builder for [`CancelImportTaskInput`](crate::operation::cancel_import_task::CancelImportTaskInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CancelImportTaskInputBuilder {
    pub(crate) import_id: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_cancel_import_task")]
impl CancelImportTaskInputBuilder {
    /// <p>The ID of the import task to cancel.</p>
    /// This field is required.
    pub fn import_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.import_id = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ID of the import task to cancel.</p>
    pub fn set_import_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.import_id = input;
        self
    }
    /// <p>The ID of the import task to cancel.</p>
    pub fn get_import_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.import_id
    }
    /// Consumes the builder and constructs a [`CancelImportTaskInput`](crate::operation::cancel_import_task::CancelImportTaskInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::cancel_import_task::CancelImportTaskInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::cancel_import_task::CancelImportTaskInput { import_id: self.import_id })
    }
}
