// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_group_policy")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteGroupPolicyOutput {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_group_policy")]
impl ::aws_types::request_id::RequestId for DeleteGroupPolicyOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
#[cfg(feature = "op_delete_group_policy")]
impl DeleteGroupPolicyOutput {
    /// Creates a new builder-style object to manufacture [`DeleteGroupPolicyOutput`](crate::operation::delete_group_policy::DeleteGroupPolicyOutput).
    pub fn builder(
    ) -> crate::operation::delete_group_policy::builders::DeleteGroupPolicyOutputBuilder {
        crate::operation::delete_group_policy::builders::DeleteGroupPolicyOutputBuilder::default()
    }
}

#[cfg(feature = "op_delete_group_policy")]
/// A builder for [`DeleteGroupPolicyOutput`](crate::operation::delete_group_policy::DeleteGroupPolicyOutput).
#[derive(
    ::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug,
)]
#[non_exhaustive]
pub struct DeleteGroupPolicyOutputBuilder {
    _request_id: Option<String>,
}
#[cfg(feature = "op_delete_group_policy")]
impl DeleteGroupPolicyOutputBuilder {
    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }
    /// Consumes the builder and constructs a [`DeleteGroupPolicyOutput`](crate::operation::delete_group_policy::DeleteGroupPolicyOutput).
    pub fn build(self) -> crate::operation::delete_group_policy::DeleteGroupPolicyOutput {
        crate::operation::delete_group_policy::DeleteGroupPolicyOutput {
            _request_id: self._request_id,
        }
    }
}
