// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[cfg(feature = "op_delete_lookup_table")]
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteLookupTableInput {
    /// <p>The ARN of the lookup table to delete.</p>
    pub lookup_table_arn: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_delete_lookup_table")]
impl DeleteLookupTableInput {
    /// <p>The ARN of the lookup table to delete.</p>
    pub fn lookup_table_arn(&self) -> ::std::option::Option<&str> {
        self.lookup_table_arn.as_deref()
    }
}
#[cfg(feature = "op_delete_lookup_table")]
impl DeleteLookupTableInput {
    /// Creates a new builder-style object to manufacture [`DeleteLookupTableInput`](crate::operation::delete_lookup_table::DeleteLookupTableInput).
    pub fn builder() -> crate::operation::delete_lookup_table::builders::DeleteLookupTableInputBuilder {
        crate::operation::delete_lookup_table::builders::DeleteLookupTableInputBuilder::default()
    }
}

#[cfg(feature = "op_delete_lookup_table")]
/// A builder for [`DeleteLookupTableInput`](crate::operation::delete_lookup_table::DeleteLookupTableInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DeleteLookupTableInputBuilder {
    pub(crate) lookup_table_arn: ::std::option::Option<::std::string::String>,
}
#[cfg(feature = "op_delete_lookup_table")]
impl DeleteLookupTableInputBuilder {
    /// <p>The ARN of the lookup table to delete.</p>
    /// This field is required.
    pub fn lookup_table_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.lookup_table_arn = ::std::option::Option::Some(input.into());
        self
    }
    /// <p>The ARN of the lookup table to delete.</p>
    pub fn set_lookup_table_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.lookup_table_arn = input;
        self
    }
    /// <p>The ARN of the lookup table to delete.</p>
    pub fn get_lookup_table_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.lookup_table_arn
    }
    /// Consumes the builder and constructs a [`DeleteLookupTableInput`](crate::operation::delete_lookup_table::DeleteLookupTableInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::delete_lookup_table::DeleteLookupTableInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::delete_lookup_table::DeleteLookupTableInput {
            lookup_table_arn: self.lookup_table_arn,
        })
    }
}
